const data = [
  {
    element: {
      id: "ActivityDefinition.meta",
      path: "ActivityDefinition.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "ActivityDefinition.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.implicitRules",
      path: "ActivityDefinition.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "ActivityDefinition.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.language",
      path: "ActivityDefinition.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "ActivityDefinition.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "ActivityDefinition.contained",
      path: "ActivityDefinition.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source: "http://hl7.org/fhir/StructureDefinition/ActivityDefinition",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "ActivityDefinition.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.url",
      path: "ActivityDefinition.url",
      short:
        "Canonical identifier for this activity definition, represented as a URI (globally unique)",
      definition:
        "An absolute URI that is used to identify this activity definition when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this activity definition is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the activity definition is stored on different servers.",
      comment:
        "Can be a urn:uuid: or a urn:oid: but real http: addresses are preferred.  Multiple instances may share the same URL if they have a distinct version.\n\nThe determination of when to create a new version of a resource (same url, new version) vs. defining a new artifact is up to the author.  Considerations for making this decision are found in [Technical and Business Versions](resource.html#versions). \n\nIn some cases, the resource can no longer be found at the stated url, but the url itself cannot change. Implementations can use the [meta.source](resource.html#meta) element to indicate where the current master source of the resource can be found.",
      requirements:
        "Allows the activity definition to be referenced by a single globally unique identifier.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.url", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.url" },
        { identity: "w5", map: "FiveWs.identifier" },
        { identity: "rim", map: ".identifier[scope=BUSN;reliability=ISS]" },
      ],
    },
    dataPath: "root.url",
    parentDataPath: "root",
    basePath: "root.url",
    baseId: "ActivityDefinition.url",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.version",
      path: "ActivityDefinition.version",
      short: "Business version of the activity definition",
      definition:
        "The identifier that is used to identify this version of the activity definition when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the activity definition author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence. To provide a version consistent with the Decision Support Service specification, use the format Major.Minor.Revision (e.g. 1.0.0). For more information on versioning knowledge assets, refer to the Decision Support Service specification. Note that a version is required for non-experimental active assets.",
      comment:
        "There may be different activity definition instances that have the same identifier but different versions.  The version can be appended to the url in a reference to allow a reference to a particular business version of the activity definition with the format [url]|[version].",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.version", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.version" },
        { identity: "w5", map: "FiveWs.version" },
        { identity: "rim", map: "N/A (to add?)" },
      ],
    },
    dataPath: "root.version",
    parentDataPath: "root",
    basePath: "root.version",
    baseId: "ActivityDefinition.version",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.name",
      path: "ActivityDefinition.name",
      short: "Name for this activity definition (computer friendly)",
      definition:
        "A natural language name identifying the activity definition. This name should be usable as an identifier for the module by machine processing applications such as code generation.",
      comment:
        "The name is not expected to be globally unique. The name should be a simple alphanumeric type name to ensure that it is machine-processing friendly.",
      requirements: "Support human navigation and code generation.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.name", min: 0, max: "1" },
      type: [{ code: "string" }],
      condition: ["cnl-0"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.name",
    parentDataPath: "root",
    basePath: "root.name",
    baseId: "ActivityDefinition.name",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.title",
      path: "ActivityDefinition.title",
      short: "Name for this activity definition (human friendly)",
      definition:
        "A short, descriptive, user-friendly title for the activity definition.",
      comment:
        "This name does not need to be machine-processing friendly and may contain punctuation, white-space, etc.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.title", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.title" },
        { identity: "rim", map: ".title" },
      ],
    },
    dataPath: "root.title",
    parentDataPath: "root",
    basePath: "root.title",
    baseId: "ActivityDefinition.title",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.subtitle",
      path: "ActivityDefinition.subtitle",
      short: "Subordinate title of the activity definition",
      definition:
        "An explanatory or alternate title for the activity definition giving additional information about its content.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.subtitle", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A (to add?)" }],
    },
    dataPath: "root.subtitle",
    parentDataPath: "root",
    basePath: "root.subtitle",
    baseId: "ActivityDefinition.subtitle",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.status",
      path: "ActivityDefinition.status",
      short: "draft | active | retired | unknown",
      definition:
        "The status of this activity definition. Enables tracking the life-cycle of the content.",
      comment:
        "Allows filtering of activity definitions that are appropriate for use versus not.",
      min: 1,
      max: "1",
      base: { path: "ActivityDefinition.status", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        'This is labeled as "Is Modifier" because applications should not use a retired {{title}} without due consideration',
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "PublicationStatus",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "required",
        description: "The lifecycle status of an artifact.",
        valueSet: "http://hl7.org/fhir/ValueSet/publication-status|4.3.0",
      },
      mapping: [
        { identity: "workflow", map: "Definition.status {different ValueSet}" },
        { identity: "w5", map: "FiveWs.status" },
        { identity: "rim", map: ".status" },
      ],
    },
    dataPath: "root.status",
    parentDataPath: "root",
    basePath: "root.status",
    baseId: "ActivityDefinition.status",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "draft",
        display: "Draft",
      },
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "active",
        display: "Active",
      },
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "retired",
        display: "Retired",
      },
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "unknown",
        display: "Unknown",
      },
    ],
  },
  {
    element: {
      id: "ActivityDefinition.experimental",
      path: "ActivityDefinition.experimental",
      short: "For testing purposes, not real usage",
      definition:
        "A Boolean value to indicate that this activity definition is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage.",
      comment:
        "Allows filtering of activity definitions that are appropriate for use versus not.",
      requirements:
        "Enables experimental content to be developed following the same lifecycle that would be used for a production-level activity definition.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.experimental", min: 0, max: "1" },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.experimental" },
        { identity: "w5", map: "FiveWs.class" },
        { identity: "rim", map: "N/A (to add?)" },
      ],
    },
    dataPath: "root.experimental",
    parentDataPath: "root",
    basePath: "root.experimental",
    baseId: "ActivityDefinition.experimental",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.subject[x]",
      path: "ActivityDefinition.subject[x]",
      short: "Type of individual the activity definition is intended for",
      definition:
        "A code, group definition, or canonical reference that describes  or identifies the intended subject of the activity being defined.  Canonical references are allowed to support the definition of protocols for drug and substance quality specifications, and is allowed to reference a MedicinalProductDefinition, SubstanceDefinition, AdministrableProductDefinition, ManufacturedItemDefinition, or PackagedProductDefinition resource.",
      comment:
        "Note that the choice of canonical for the subject element was introduced in R4B to support pharmaceutical quality use cases. To ensure as much backwards-compatibility as possible, it is recommended to only use the new canonical type with these use cases.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.subject[x]", min: 0, max: "1" },
      type: [
        { code: "CodeableConcept" },
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Group"],
        },
        { code: "canonical" },
      ],
      meaningWhenMissing: "Patient",
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "SubjectType",
          },
        ],
        strength: "extensible",
        description:
          "The possible types of subjects for an activity (E.g. Patient, Practitioner, Organization, Location, etc.).",
        valueSet: "http://hl7.org/fhir/ValueSet/subject-type",
      },
      mapping: [
        { identity: "workflow", map: "Definition.subject" },
        {
          identity: "rim",
          map: "N/A (to add?) { only applies for subject Patient? }",
        },
      ],
    },
    dataPath: "root.subject[x]",
    parentDataPath: "root",
    basePath: "root.subject[x]",
    baseId: "ActivityDefinition.subject[x]",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "Patient" },
      { code: "Practitioner" },
      { code: "Organization" },
      { code: "Location" },
      { code: "Device" },
    ],
  },
  {
    element: {
      id: "ActivityDefinition.date",
      path: "ActivityDefinition.date",
      short: "Date last changed",
      definition:
        "The date  (and optionally time) when the activity definition was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the activity definition changes.",
      comment:
        "Note that this is not the same as the resource last-modified-date, since the resource may be a secondary representation of the activity definition. Additional specific dates may be added as extensions or be found by consulting Provenances associated with past versions of the resource.",
      alias: ["Revision Date"],
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.date", min: 0, max: "1" },
      type: [{ code: "dateTime" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.date" },
        { identity: "w5", map: "FiveWs.recorded" },
        { identity: "rim", map: ".participation[typeCode=AUT].time" },
      ],
    },
    dataPath: "root.date",
    parentDataPath: "root",
    basePath: "root.date",
    baseId: "ActivityDefinition.date",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.publisher",
      path: "ActivityDefinition.publisher",
      short: "Name of the publisher (organization or individual)",
      definition:
        "The name of the organization or individual that published the activity definition.",
      comment:
        "Usually an organization but may be an individual. The publisher (or steward) of the activity definition is the organization or individual primarily responsible for the maintenance and upkeep of the activity definition. This is not necessarily the same individual or organization that developed and initially authored the content. The publisher is the primary point of contact for questions or issues with the activity definition. This item SHOULD be populated unless the information is available from context.",
      requirements:
        'Helps establish the "authority/credibility" of the activity definition.  May also allow for contact.',
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.publisher", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        {
          identity: "workflow",
          map: "Definition.publisher {as string instead of CodeableConcept}",
        },
        { identity: "w5", map: "FiveWs.witness" },
        { identity: "rim", map: ".participation[typeCode=AUT].role" },
      ],
    },
    dataPath: "root.publisher",
    parentDataPath: "root",
    basePath: "root.publisher",
    baseId: "ActivityDefinition.publisher",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.description",
      path: "ActivityDefinition.description",
      short: "Natural language description of the activity definition",
      definition:
        "A free text natural language description of the activity definition from a consumer's perspective.",
      comment:
        "This description can be used to capture details such as why the activity definition was built, comments about misuse, instructions for clinical use and interpretation, literature references, examples from the paper world, etc. It is not a rendering of the activity definition as conveyed in the 'text' field of the resource itself. This item SHOULD be populated unless the information is available from context (e.g. the language of the activity definition is presumed to be the predominant language in the place the activity definition was created).",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.description", min: 0, max: "1" },
      type: [{ code: "markdown" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.description" },
        { identity: "rim", map: ".text" },
      ],
    },
    dataPath: "root.description",
    parentDataPath: "root",
    basePath: "root.description",
    baseId: "ActivityDefinition.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.jurisdiction",
      path: "ActivityDefinition.jurisdiction",
      short: "Intended jurisdiction for activity definition (if applicable)",
      definition:
        "A legal or geographic region in which the activity definition is intended to be used.",
      comment:
        "It may be possible for the activity definition to be used in jurisdictions other than those for which it was originally designed or intended.",
      min: 0,
      max: "*",
      base: { path: "ActivityDefinition.jurisdiction", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Jurisdiction",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "extensible",
        description:
          "Countries and regions within which this artifact is targeted for use.",
        valueSet: "http://hl7.org/fhir/ValueSet/jurisdiction",
      },
      mapping: [
        { identity: "workflow", map: "Definition.jurisdiction" },
        { identity: "rim", map: "N/A (to add?)" },
      ],
    },
    dataPath: "root.jurisdiction[0]",
    parentDataPath: "root",
    basePath: "root.jurisdiction",
    baseId: "ActivityDefinition.jurisdiction",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.purpose",
      path: "ActivityDefinition.purpose",
      short: "Why this activity definition is defined",
      definition:
        "Explanation of why this activity definition is needed and why it has been designed as it has.",
      comment:
        "This element does not describe the usage of the activity definition. Instead, it provides traceability of ''why'' the resource is either needed or ''why'' it is defined as it is.  This may be used to point to source materials or specifications that drove the structure of this activity definition.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.purpose", min: 0, max: "1" },
      type: [{ code: "markdown" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "workflow", map: "Definition.purpose" },
        { identity: "w5", map: "FiveWs.why[x]" },
        { identity: "rim", map: ".reasonCode.text" },
        { identity: "objimpl", map: "no-gen-base" },
      ],
    },
    dataPath: "root.purpose",
    parentDataPath: "root",
    basePath: "root.purpose",
    baseId: "ActivityDefinition.purpose",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.usage",
      path: "ActivityDefinition.usage",
      short: "Describes the clinical usage of the activity definition",
      definition:
        "A detailed description of how the activity definition is used from a clinical perspective.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.usage", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A (to add?)" }],
    },
    dataPath: "root.usage",
    parentDataPath: "root",
    basePath: "root.usage",
    baseId: "ActivityDefinition.usage",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.copyright",
      path: "ActivityDefinition.copyright",
      short: "Use and/or publishing restrictions",
      definition:
        "A copyright statement relating to the activity definition and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the activity definition.",
      requirements:
        "Consumers must be able to determine any legal restrictions on the use of the activity definition and/or its content.",
      alias: ["License", "Restrictions"],
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.copyright", min: 0, max: "1" },
      type: [{ code: "markdown" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "workflow", map: "Definition.copyright" },
        { identity: "rim", map: "N/A (to add?)" },
        { identity: "objimpl", map: "no-gen-base" },
      ],
    },
    dataPath: "root.copyright",
    parentDataPath: "root",
    basePath: "root.copyright",
    baseId: "ActivityDefinition.copyright",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.approvalDate",
      path: "ActivityDefinition.approvalDate",
      short: "When the activity definition was approved by publisher",
      definition:
        "The date on which the resource content was approved by the publisher. Approval happens once when the content is officially approved for usage.",
      comment:
        "The 'date' element may be more recent than the approval date because of minor changes or editorial corrections.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.approvalDate", min: 0, max: "1" },
      type: [{ code: "date" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "workflow", map: "Definition.approvalDate" },
        {
          identity: "rim",
          map: '.outboundRelationship[typeCode="SUBJ"].act[classCode=CACT;moodCode=EVN;code="approval"].effectiveTime',
        },
        { identity: "objimpl", map: "no-gen-base" },
      ],
    },
    dataPath: "root.approvalDate",
    parentDataPath: "root",
    basePath: "root.approvalDate",
    baseId: "ActivityDefinition.approvalDate",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.lastReviewDate",
      path: "ActivityDefinition.lastReviewDate",
      short: "When the activity definition was last reviewed",
      definition:
        "The date on which the resource content was last reviewed. Review happens periodically after approval but does not change the original approval date.",
      comment: "If specified, this date follows the original approval date.",
      requirements:
        'Gives a sense of how "current" the content is.  Resources that have not been reviewed in a long time may have a risk of being less appropriate/relevant.',
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.lastReviewDate", min: 0, max: "1" },
      type: [{ code: "date" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "workflow", map: "Definition.lastReviewDate" },
        {
          identity: "rim",
          map: '.outboundRelationship[typeCode="SUBJ"; subsetCode="RECENT"].act[classCode=CACT;moodCode=EVN;code="review"].effectiveTime',
        },
        { identity: "objimpl", map: "no-gen-base" },
      ],
    },
    dataPath: "root.lastReviewDate",
    parentDataPath: "root",
    basePath: "root.lastReviewDate",
    baseId: "ActivityDefinition.lastReviewDate",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.topic",
      path: "ActivityDefinition.topic",
      short: "E.g. Education, Treatment, Assessment, etc.",
      definition:
        "Descriptive topics related to the content of the activity. Topics provide a high-level categorization of the activity that can be useful for filtering and searching.",
      requirements:
        "Repositories must be able to determine how to categorize the activity definition so that it can be found by topical searches.",
      min: 0,
      max: "*",
      base: { path: "ActivityDefinition.topic", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "DefinitionTopic",
          },
        ],
        strength: "example",
        description:
          "High-level categorization of the definition, used for searching, sorting, and filtering.",
        valueSet: "http://hl7.org/fhir/ValueSet/definition-topic",
      },
      mapping: [{ identity: "rim", map: "N/A (to add?)" }],
    },
    dataPath: "root.topic[0]",
    parentDataPath: "root",
    basePath: "root.topic",
    baseId: "ActivityDefinition.topic",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://terminology.hl7.org/CodeSystem/definition-topic",
        code: "treatment",
        display: "Treatment",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/definition-topic",
        code: "education",
        display: "Education",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/definition-topic",
        code: "assessment",
        display: "Assessment",
      },
    ],
  },
  {
    element: {
      id: "ActivityDefinition.editor",
      path: "ActivityDefinition.editor",
      short: "Who edited the content",
      definition:
        "An individual or organization primarily responsible for internal coherence of the content.",
      min: 0,
      max: "*",
      base: { path: "ActivityDefinition.editor", min: 0, max: "*" },
      type: [{ code: "ContactDetail" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".participation[typeCode=AUT] { not a great match, but there does not appear to be an editor concept in V3 participation }",
        },
      ],
    },
    dataPath: "root.editor[0]",
    parentDataPath: "root",
    basePath: "root.editor",
    baseId: "ActivityDefinition.editor",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.endorser",
      path: "ActivityDefinition.endorser",
      short: "Who endorsed the content",
      definition:
        "An individual or organization responsible for officially endorsing the content for use in some setting.",
      min: 0,
      max: "*",
      base: { path: "ActivityDefinition.endorser", min: 0, max: "*" },
      type: [{ code: "ContactDetail" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".participation[typeCode=VRF] {not clear whether VRF best corresponds to reviewer or endorser}",
        },
      ],
    },
    dataPath: "root.endorser[0]",
    parentDataPath: "root",
    basePath: "root.endorser",
    baseId: "ActivityDefinition.endorser",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.library",
      path: "ActivityDefinition.library",
      short: "Logic used by the activity definition",
      definition:
        "A reference to a Library resource containing any formal logic used by the activity definition.",
      min: 0,
      max: "*",
      base: { path: "ActivityDefinition.library", min: 0, max: "*" },
      type: [
        {
          code: "canonical",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Library"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=USE].target[classCode=GROUPER,moodCode=EVN]",
        },
      ],
    },
    dataPath: "root.library[0]",
    parentDataPath: "root",
    basePath: "root.library",
    baseId: "ActivityDefinition.library",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.kind",
      path: "ActivityDefinition.kind",
      short: "Kind of resource",
      definition:
        "A description of the kind of resource the activity definition is representing. For example, a MedicationRequest, a ServiceRequest, or a CommunicationRequest. Typically, but not always, this is a Request resource.",
      comment: "May determine what types of extensions are permitted.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.kind", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ActivityDefinitionKind",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "required",
        description: "The kind of activity the definition is describing.",
        valueSet: "http://hl7.org/fhir/ValueSet/request-resource-types|4.3.0",
      },
      mapping: [{ identity: "rim", map: ".classCode" }],
    },
    dataPath: "root.kind",
    parentDataPath: "root",
    basePath: "root.kind",
    baseId: "ActivityDefinition.kind",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "Appointment",
        display: "Appointment",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "AppointmentResponse",
        display: "AppointmentResponse",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "CarePlan",
        display: "CarePlan",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "Claim",
        display: "Claim",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "CommunicationRequest",
        display: "CommunicationRequest",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "Contract",
        display: "Contract",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "DeviceRequest",
        display: "DeviceRequest",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "EnrollmentRequest",
        display: "EnrollmentRequest",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "ImmunizationRecommendation",
        display: "ImmunizationRecommendation",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "MedicationRequest",
        display: "MedicationRequest",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "NutritionOrder",
        display: "NutritionOrder",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "ServiceRequest",
        display: "ServiceRequest",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "SupplyRequest",
        display: "SupplyRequest",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "Task",
        display: "Task",
      },
      {
        system: "http://hl7.org/fhir/request-resource-types",
        code: "VisionPrescription",
        display: "VisionPrescription",
      },
    ],
  },
  {
    element: {
      id: "ActivityDefinition.profile",
      path: "ActivityDefinition.profile",
      short: "What profile the resource needs to conform to",
      definition:
        "A profile to which the target of the activity definition is expected to conform.",
      requirements:
        "Allows profiles to be used to describe the types of activities that can be performed within a workflow, protocol, or order set.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.profile", min: 0, max: "1" },
      type: [
        {
          code: "canonical",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/StructureDefinition",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: ".templateId" }],
    },
    dataPath: "root.profile",
    parentDataPath: "root",
    basePath: "root.profile",
    baseId: "ActivityDefinition.profile",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.intent",
      path: "ActivityDefinition.intent",
      short:
        "proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | option",
      definition:
        "Indicates the level of authority/intentionality associated with the activity and where the request should fit into the workflow chain.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.intent", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "RequestIntent",
          },
        ],
        strength: "required",
        description:
          "Codes indicating the degree of authority/intentionality associated with a request.",
        valueSet: "http://hl7.org/fhir/ValueSet/request-intent|4.3.0",
      },
      mapping: [
        { identity: "rim", map: ".moodCode { of the realized Activity }" },
      ],
    },
    dataPath: "root.intent",
    parentDataPath: "root",
    basePath: "root.intent",
    baseId: "ActivityDefinition.intent",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/request-intent",
        code: "proposal",
        display: "Proposal",
      },
      {
        system: "http://hl7.org/fhir/request-intent",
        code: "plan",
        display: "Plan",
      },
      {
        system: "http://hl7.org/fhir/request-intent",
        code: "directive",
        display: "Directive",
      },
      {
        system: "http://hl7.org/fhir/request-intent",
        code: "order",
        display: "Order",
      },
      {
        system: "http://hl7.org/fhir/request-intent",
        code: "original-order",
        display: "Original Order",
      },
      {
        system: "http://hl7.org/fhir/request-intent",
        code: "reflex-order",
        display: "Reflex Order",
      },
      {
        system: "http://hl7.org/fhir/request-intent",
        code: "filler-order",
        display: "Filler Order",
      },
      {
        system: "http://hl7.org/fhir/request-intent",
        code: "instance-order",
        display: "Instance Order",
      },
      {
        system: "http://hl7.org/fhir/request-intent",
        code: "option",
        display: "Option",
      },
    ],
  },
  {
    element: {
      id: "ActivityDefinition.priority",
      path: "ActivityDefinition.priority",
      short: "routine | urgent | asap | stat",
      definition:
        "Indicates how quickly the activity  should be addressed with respect to other requests.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.priority", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "RequestPriority",
          },
        ],
        strength: "required",
        description:
          "Identifies the level of importance to be assigned to actioning the request.",
        valueSet: "http://hl7.org/fhir/ValueSet/request-priority|4.3.0",
      },
      mapping: [
        { identity: "rim", map: ".priority { of the realized activity }" },
      ],
    },
    dataPath: "root.priority",
    parentDataPath: "root",
    basePath: "root.priority",
    baseId: "ActivityDefinition.priority",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/request-priority",
        code: "routine",
        display: "Routine",
      },
      {
        system: "http://hl7.org/fhir/request-priority",
        code: "urgent",
        display: "Urgent",
      },
      {
        system: "http://hl7.org/fhir/request-priority",
        code: "asap",
        display: "ASAP",
      },
      {
        system: "http://hl7.org/fhir/request-priority",
        code: "stat",
        display: "STAT",
      },
    ],
  },
  {
    element: {
      id: "ActivityDefinition.doNotPerform",
      path: "ActivityDefinition.doNotPerform",
      short: "True if the activity should not be performed",
      definition:
        "Set this to true if the definition is to indicate that a particular activity should NOT be performed. If true, this element should be interpreted to reinforce a negative coding. For example NPO as a code with a doNotPerform of true would still indicate to NOT perform the action.",
      comment:
        'This element is not intended to be used to communicate a decision support response to cancel an order in progress. That should be done with the "remove" type of a PlanDefinition or RequestGroup.',
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.doNotPerform", min: 0, max: "1" },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "If true this element negates the specified action. For Example,  instead of a request for a procedure, it is a request for the procedure to not occur.",
      isSummary: true,
      mapping: [
        { identity: "rim", map: ".negationInd { of the realized activity }" },
      ],
    },
    dataPath: "root.doNotPerform",
    parentDataPath: "root",
    basePath: "root.doNotPerform",
    baseId: "ActivityDefinition.doNotPerform",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.location",
      path: "ActivityDefinition.location",
      short: "Where it should happen",
      definition:
        "Identifies the facility where the activity will occur; e.g. home, hospital, specific clinic, etc.",
      comment:
        "May reference a specific clinical location or may just identify a type of location.",
      requirements: "Helps in planning of activity.",
      alias: ["facility"],
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.location", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Location"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: ".participation[typeCode=LOC].role" }],
    },
    dataPath: "root.location",
    parentDataPath: "root",
    basePath: "root.location",
    baseId: "ActivityDefinition.location",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.participant",
      path: "ActivityDefinition.participant",
      short: "Who should participate in the action",
      definition:
        "Indicates who should participate in performing the action described.",
      min: 0,
      max: "*",
      base: { path: "ActivityDefinition.participant", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: ".participation[typeCode=PFM]" }],
    },
    dataPath: "root.participant[0]",
    parentDataPath: "root",
    basePath: "root.participant",
    baseId: "ActivityDefinition.participant",
    isPrimitive: false,
    childPaths: ["root.participant.type", "root.participant.role"],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.participant.type",
      path: "ActivityDefinition.participant.type",
      short: "patient | practitioner | related-person | device",
      definition: "The type of participant in the action.",
      min: 1,
      max: "1",
      base: { path: "ActivityDefinition.participant.type", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ActivityParticipantType",
          },
        ],
        strength: "required",
        description: "The type of participant in the activity.",
        valueSet: "http://hl7.org/fhir/ValueSet/action-participant-type|4.3.0",
      },
      mapping: [{ identity: "rim", map: ".role.classCode" }],
    },
    dataPath: "root.participant.type",
    parentDataPath: "root.participant[0]",
    basePath: "root.type",
    baseId: "ActivityDefinition.participant.type",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/action-participant-type",
        code: "patient",
        display: "Patient",
      },
      {
        system: "http://hl7.org/fhir/action-participant-type",
        code: "practitioner",
        display: "Practitioner",
      },
      {
        system: "http://hl7.org/fhir/action-participant-type",
        code: "related-person",
        display: "Related Person",
      },
      {
        system: "http://hl7.org/fhir/action-participant-type",
        code: "device",
        display: "Device",
      },
    ],
  },
  {
    element: {
      id: "ActivityDefinition.product[x]",
      path: "ActivityDefinition.product[x]",
      short: "What's administered/supplied",
      definition:
        "Identifies the food, drug or other product being consumed or supplied in the activity.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.product[x]", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Medication",
            "http://hl7.org/fhir/StructureDefinition/Substance",
            "http://hl7.org/fhir/StructureDefinition/Ingredient",
          ],
        },
        { code: "CodeableConcept" },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ActivityProduct",
          },
        ],
        strength: "example",
        description: "Code describing the type of substance or medication.",
        valueSet: "http://hl7.org/fhir/ValueSet/medication-codes",
      },
      mapping: [{ identity: "rim", map: ".participation[typeCode=CSM].role" }],
    },
    dataPath: "root.product[x]",
    parentDataPath: "root",
    basePath: "root.product[x]",
    baseId: "ActivityDefinition.product[x]",
    isPrimitive: false,
    childPaths: [],
    multiTypeType: "Reference",
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.dosage",
      path: "ActivityDefinition.dosage",
      short: "Detailed dosage instructions",
      definition:
        "Provides detailed dosage instructions in the same way that they are described for MedicationRequest resources.",
      comment:
        "If a dosage instruction is used, the definition should not specify timing or quantity.",
      min: 0,
      max: "*",
      base: { path: "ActivityDefinition.dosage", min: 0, max: "*" },
      type: [{ code: "Dosage" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP].target[classCode=SBADM; moodCode=DEFN]",
        },
      ],
    },
    dataPath: "root.dosage[0]",
    parentDataPath: "root",
    basePath: "root.dosage",
    baseId: "ActivityDefinition.dosage",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.specimenRequirement",
      path: "ActivityDefinition.specimenRequirement",
      short: "What specimens are required to perform this action",
      definition:
        "Defines specimen requirements for the action to be performed, such as required specimens for a lab test.",
      requirements: "Needed to represent lab order definitions.",
      min: 0,
      max: "*",
      base: {
        path: "ActivityDefinition.specimenRequirement",
        min: 0,
        max: "*",
      },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/SpecimenDefinition",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.specimenRequirement[0]",
    parentDataPath: "root",
    basePath: "root.specimenRequirement",
    baseId: "ActivityDefinition.specimenRequirement",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.observationResultRequirement",
      path: "ActivityDefinition.observationResultRequirement",
      short: "What observations must be produced by this action",
      definition:
        "Defines the observations that are expected to be produced by the action.",
      min: 0,
      max: "*",
      base: {
        path: "ActivityDefinition.observationResultRequirement",
        min: 0,
        max: "*",
      },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/ObservationDefinition",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.observationResultRequirement[0]",
    parentDataPath: "root",
    basePath: "root.observationResultRequirement",
    baseId: "ActivityDefinition.observationResultRequirement",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.transform",
      path: "ActivityDefinition.transform",
      short: "Transform to apply the template",
      definition:
        "A reference to a StructureMap resource that defines a transform that can be executed to produce the intent resource using the ActivityDefinition instance as the input.",
      comment:
        "Note that if both a transform and dynamic values are specified, the dynamic values will be applied to the result of the transform.",
      min: 0,
      max: "1",
      base: { path: "ActivityDefinition.transform", min: 0, max: "1" },
      type: [
        {
          code: "canonical",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/StructureMap",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.transform",
    parentDataPath: "root",
    basePath: "root.transform",
    baseId: "ActivityDefinition.transform",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.dynamicValue",
      path: "ActivityDefinition.dynamicValue",
      short: "Dynamic aspects of the definition",
      definition:
        "Dynamic values that will be evaluated to produce values for elements of the resulting resource. For example, if the dosage of a medication must be computed based on the patient's weight, a dynamic value would be used to specify an expression that calculated the weight, and the path on the request resource that would contain the result.",
      comment:
        "Dynamic values are applied in the order in which they are defined in the ActivityDefinition. Note that if both a transform and dynamic values are specified, the dynamic values will be applied to the result of the transform.",
      min: 0,
      max: "*",
      base: { path: "ActivityDefinition.dynamicValue", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.dynamicValue[0]",
    parentDataPath: "root",
    basePath: "root.dynamicValue",
    baseId: "ActivityDefinition.dynamicValue",
    isPrimitive: false,
    childPaths: ["root.dynamicValue.path", "root.dynamicValue.expression"],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition.dynamicValue.path",
      path: "ActivityDefinition.dynamicValue.path",
      short: "The path to the element to be set dynamically",
      definition:
        "The path to the element to be customized. This is the path on the resource that will hold the result of the calculation defined by the expression. The specified path SHALL be a FHIRPath resolveable on the specified target type of the ActivityDefinition, and SHALL consist only of identifiers, constant indexers, and a restricted subset of functions. The path is allowed to contain qualifiers (.) to traverse sub-elements, as well as indexers ([x]) to traverse multiple-cardinality sub-elements (see the [Simple FHIRPath Profile](fhirpath.html#simple) for full details).",
      comment:
        "The path attribute contains a [Simple FHIRPath Subset](fhirpath.html#simple) that allows path traversal, but not calculation.",
      min: 1,
      max: "1",
      base: { path: "ActivityDefinition.dynamicValue.path", min: 1, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.dynamicValue.path",
    parentDataPath: "root.dynamicValue[0]",
    basePath: "root.path",
    baseId: "ActivityDefinition.dynamicValue.path",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ActivityDefinition",
      path: "ActivityDefinition",
      short:
        "The definition of a specific activity to be taken, independent of any particular patient or context",
      definition:
        "This resource allows for the definition of some activity to be performed, independent of a particular patient, practitioner, or other performance context.",
      min: 0,
      max: "*",
      base: { path: "ActivityDefinition", min: 0, max: "*" },
      constraint: [
        {
          key: "cnl-0",
          severity: "warning",
          human:
            "Name should be usable as an identifier for the module by machine processing applications such as code generation",
          expression:
            "name.exists() implies name.matches('[A-Z]([A-Za-z0-9_]){0,254}')",
          xpath:
            "not(exists(f:name/@value)) or matches(f:name/@value, '[A-Z]([A-Za-z0-9_]){0,254}')",
          source: "http://hl7.org/fhir/StructureDefinition/ActivityDefinition",
        },
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "workflow", map: "Definition" },
        { identity: "rim", map: "Act[classCode=ACT; moodCode=DEFN]" },
        { identity: "w5", map: "clinical.general" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "ActivityDefinition",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
