const data = [
  {
    element: {
      id: "CarePlan.meta",
      path: "CarePlan.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "CarePlan.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.implicitRules",
      path: "CarePlan.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "CarePlan.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.language",
      path: "CarePlan.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "CarePlan.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "CarePlan.contained",
      path: "CarePlan.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source: "http://hl7.org/fhir/StructureDefinition/CarePlan",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "CarePlan.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.instantiatesCanonical",
      path: "CarePlan.instantiatesCanonical",
      short: "Instantiates FHIR protocol or definition",
      definition:
        "The URL pointing to a FHIR-defined protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan.",
      min: 0,
      max: "*",
      base: { path: "CarePlan.instantiatesCanonical", min: 0, max: "*" },
      type: [
        {
          code: "canonical",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/PlanDefinition",
            "http://hl7.org/fhir/StructureDefinition/Questionnaire",
            "http://hl7.org/fhir/StructureDefinition/Measure",
            "http://hl7.org/fhir/StructureDefinition/ActivityDefinition",
            "http://hl7.org/fhir/StructureDefinition/OperationDefinition",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Request.instantiatesCanonical" },
        { identity: "rim", map: ".outboundRelationship[typeCode=DEFN].target" },
      ],
    },
    dataPath: "root.instantiatesCanonical[0]",
    parentDataPath: "root",
    basePath: "root.instantiatesCanonical",
    baseId: "CarePlan.instantiatesCanonical",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.instantiatesUri",
      path: "CarePlan.instantiatesUri",
      short: "Instantiates external protocol or definition",
      definition:
        "The URL pointing to an externally maintained protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan.",
      comment:
        "This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier.",
      min: 0,
      max: "*",
      base: { path: "CarePlan.instantiatesUri", min: 0, max: "*" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Request.instantiatesUri" },
        { identity: "rim", map: ".outboundRelationship[typeCode=DEFN].target" },
      ],
    },
    dataPath: "root.instantiatesUri[0]",
    parentDataPath: "root",
    basePath: "root.instantiatesUri",
    baseId: "CarePlan.instantiatesUri",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.replaces",
      path: "CarePlan.replaces",
      short: "CarePlan replaced by this CarePlan",
      definition:
        "Completed or terminated care plan whose function is taken by this new care plan.",
      comment:
        "The replacement could be because the initial care plan was immediately rejected (due to an issue) or because the previous care plan was completed, but the need for the action described by the care plan remains ongoing.",
      requirements:
        "Allows tracing the continuation of a therapy or administrative process instantiated through multiple care plans.",
      alias: ["supersedes"],
      min: 0,
      max: "*",
      base: { path: "CarePlan.replaces", min: 0, max: "*" },
      type: [
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/structuredefinition-hierarchy",
              valueBoolean: true,
            },
          ],
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/CarePlan"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "workflow", map: "Request.replaces" }],
    },
    dataPath: "root.replaces[0]",
    parentDataPath: "root",
    basePath: "root.replaces",
    baseId: "CarePlan.replaces",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.status",
      path: "CarePlan.status",
      short:
        "draft | active | on-hold | revoked | completed | entered-in-error | unknown",
      definition:
        "Indicates whether the plan is currently being acted upon, represents future intentions or is now a historical record.",
      comment:
        "The unknown code is not to be used to convey other statuses.  The unknown code should be used when one of the statuses applies, but the authoring system doesn't know the current state of the care plan.\n\nThis element is labeled as a modifier because the status contains the code entered-in-error that marks the plan as not currently valid.",
      requirements:
        "Allows clinicians to determine whether the plan is actionable or not.",
      min: 1,
      max: "1",
      base: { path: "CarePlan.status", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid",
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CarePlanStatus",
          },
        ],
        strength: "required",
        description:
          "Indicates whether the plan is currently being acted upon, represents future intentions or is now a historical record.",
        valueSet: "http://hl7.org/fhir/ValueSet/request-status|4.3.0",
      },
      mapping: [
        {
          identity: "workflow",
          map: "Request.status {uses different ValueSet}",
        },
        { identity: "w5", map: "FiveWs.status" },
        { identity: "v2", map: "PTH-5" },
        {
          identity: "rim",
          map: ".statusCode planned = new active = active completed = completed",
        },
      ],
    },
    dataPath: "root.status",
    parentDataPath: "root",
    basePath: "root.status",
    baseId: "CarePlan.status",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/request-status",
        code: "draft",
        display: "Draft",
      },
      {
        system: "http://hl7.org/fhir/request-status",
        code: "active",
        display: "Active",
      },
      {
        system: "http://hl7.org/fhir/request-status",
        code: "on-hold",
        display: "On Hold",
      },
      {
        system: "http://hl7.org/fhir/request-status",
        code: "revoked",
        display: "Revoked",
      },
      {
        system: "http://hl7.org/fhir/request-status",
        code: "completed",
        display: "Completed",
      },
      {
        system: "http://hl7.org/fhir/request-status",
        code: "entered-in-error",
        display: "Entered in Error",
      },
      {
        system: "http://hl7.org/fhir/request-status",
        code: "unknown",
        display: "Unknown",
      },
    ],
  },
  {
    element: {
      id: "CarePlan.intent",
      path: "CarePlan.intent",
      short: "proposal | plan | order | option",
      definition:
        "Indicates the level of authority/intentionality associated with the care plan and where the care plan fits into the workflow chain.",
      comment:
        "This element is labeled as a modifier because the intent alters when and how the resource is actually applicable.",
      requirements:
        "Proposals/recommendations, plans and orders all use the same structure and can exist in the same fulfillment chain.",
      min: 1,
      max: "1",
      base: { path: "CarePlan.intent", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        'This element changes the interpretation of all descriptive attributes. For example "the time the request is recommended to occur" vs. "the time the request is authorized to occur" or "who is recommended to perform the request" vs. "who is authorized to perform the request"',
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CarePlanIntent",
          },
        ],
        strength: "required",
        description:
          "Codes indicating the degree of authority/intentionality associated with a care plan.",
        valueSet: "http://hl7.org/fhir/ValueSet/care-plan-intent|4.3.0",
      },
      mapping: [{ identity: "workflow", map: "Request.intent" }],
    },
    dataPath: "root.intent",
    parentDataPath: "root",
    basePath: "root.intent",
    baseId: "CarePlan.intent",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "proposal" },
      { code: "plan" },
      { code: "order" },
      { code: "option" },
    ],
  },
  {
    element: {
      id: "CarePlan.title",
      path: "CarePlan.title",
      short: "Human-friendly name for the care plan",
      definition: "Human-friendly name for the care plan.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.title", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.title",
    parentDataPath: "root",
    basePath: "root.title",
    baseId: "CarePlan.title",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.description",
      path: "CarePlan.description",
      short: "Summary of nature of plan",
      definition: "A description of the scope and nature of the plan.",
      requirements: "Provides more detail than conveyed by category.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.description", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "w5", map: "FiveWs.what[x]" }],
    },
    dataPath: "root.description",
    parentDataPath: "root",
    basePath: "root.description",
    baseId: "CarePlan.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.encounter",
      path: "CarePlan.encounter",
      short: "Encounter created as part of",
      definition:
        "The Encounter during which this CarePlan was created or to which the creation of this record is tightly associated.",
      comment:
        "This will typically be the encounter the event occurred within, but some activities may be initiated prior to or after the official completion of an encounter but still be tied to the context of the encounter. CarePlan activities conducted as a result of the care plan may well occur as part of other encounters.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.encounter", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Encounter"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Request.context" },
        { identity: "w5", map: "FiveWs.context" },
        { identity: "v2", map: "Associated PV1" },
        { identity: "rim", map: "." },
      ],
    },
    dataPath: "root.encounter",
    parentDataPath: "root",
    basePath: "root.encounter",
    baseId: "CarePlan.encounter",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.created",
      path: "CarePlan.created",
      short: "Date record was first recorded",
      definition:
        "Represents when this particular CarePlan record was created in the system, which is often a system-generated date.",
      alias: ["authoredOn"],
      min: 0,
      max: "1",
      base: { path: "CarePlan.created", min: 0, max: "1" },
      type: [{ code: "dateTime" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Request.authoredOn" },
        { identity: "w5", map: "FiveWs.recorded" },
        { identity: "rim", map: ".participation[typeCode=AUT].time" },
      ],
    },
    dataPath: "root.created",
    parentDataPath: "root",
    basePath: "root.created",
    baseId: "CarePlan.created",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.contributor",
      path: "CarePlan.contributor",
      short: "Who provided the content of the care plan",
      definition:
        "Identifies the individual(s) or organization who provided the contents of the care plan.",
      comment: "Collaborative care plans may have multiple contributors.",
      min: 0,
      max: "*",
      base: { path: "CarePlan.contributor", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Patient",
            "http://hl7.org/fhir/StructureDefinition/Practitioner",
            "http://hl7.org/fhir/StructureDefinition/PractitionerRole",
            "http://hl7.org/fhir/StructureDefinition/Device",
            "http://hl7.org/fhir/StructureDefinition/RelatedPerson",
            "http://hl7.org/fhir/StructureDefinition/Organization",
            "http://hl7.org/fhir/StructureDefinition/CareTeam",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.contributor[0]",
    parentDataPath: "root",
    basePath: "root.contributor",
    baseId: "CarePlan.contributor",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.addresses",
      path: "CarePlan.addresses",
      short: "Health issues this plan addresses",
      definition:
        "Identifies the conditions/problems/concerns/diagnoses/etc. whose management and/or mitigation are handled by this plan.",
      comment:
        "When the diagnosis is related to an allergy or intolerance, the Condition and AllergyIntolerance resources can both be used. However, to be actionable for decision support, using Condition alone is not sufficient as the allergy or intolerance condition needs to be represented as an AllergyIntolerance.",
      requirements:
        'Links plan to the conditions it manages.  The element can identify risks addressed by the plan as well as active conditions.  (The Condition resource can include things like "at risk for hypertension" or "fall risk".)  Also scopes plans - multiple plans may exist addressing different concerns.',
      min: 0,
      max: "*",
      base: { path: "CarePlan.addresses", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Condition"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Request.reasonReference" },
        { identity: "w5", map: "FiveWs.why[x]" },
        { identity: "v2", map: "PRB-4" },
        {
          identity: "rim",
          map: ".actRelationship[typeCode=SUBJ].target[classCode=CONC, moodCode=EVN]",
        },
      ],
    },
    dataPath: "root.addresses[0]",
    parentDataPath: "root",
    basePath: "root.addresses",
    baseId: "CarePlan.addresses",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.goal",
      path: "CarePlan.goal",
      short: "Desired outcome of plan",
      definition:
        "Describes the intended objective(s) of carrying out the care plan.",
      comment:
        "Goal can be achieving a particular change or merely maintaining a current state or even slowing a decline.",
      requirements:
        "Provides context for plan.  Allows plan effectiveness to be evaluated by clinicians.",
      min: 0,
      max: "*",
      base: { path: "CarePlan.goal", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Goal"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "v2", map: "GOL.1" },
        { identity: "rim", map: ".outboundRelationship[typeCode<=OBJ]." },
      ],
    },
    dataPath: "root.goal[0]",
    parentDataPath: "root",
    basePath: "root.goal",
    baseId: "CarePlan.goal",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity",
      path: "CarePlan.activity",
      short: "Action to occur as part of plan",
      definition:
        "Identifies a planned action to occur as part of the plan.  For example, a medication to be used, lab tests to perform, self-monitoring, education, etc.",
      requirements:
        "Allows systems to prompt for performance of planned activities, and validate plans against best practice.",
      min: 0,
      max: "*",
      base: { path: "CarePlan.activity", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "cpl-3",
          severity: "error",
          human: "Provide a reference or detail, not both",
          expression: "detail.empty() or reference.empty()",
          xpath: "not(exists(f:detail)) or not(exists(f:reference))",
          source: "http://hl7.org/fhir/StructureDefinition/CarePlan",
        },
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "workflow",
          map: "{no mapping\nNOTE: This is a list of contained Request-Event tuples!}",
        },
        { identity: "rim", map: ".outboundRelationship[typeCode=COMP].target" },
      ],
    },
    dataPath: "root.activity[0]",
    parentDataPath: "root",
    basePath: "root.activity",
    baseId: "CarePlan.activity",
    isPrimitive: false,
    childPaths: [
      "root.activity.outcomeCodeableConcept[0]",
      "root.activity.outcomeReference[0]",
      "root.activity.progress[0]",
      "root.activity.reference",
      "root.activity.detail",
    ],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.outcomeReference",
      path: "CarePlan.activity.outcomeReference",
      short: "Appointment, Encounter, Procedure, etc.",
      definition:
        'Details of the outcome or action resulting from the activity.  The reference to an "event" resource, such as Procedure or Encounter or Observation, is the result/outcome of the activity itself.  The activity can be conveyed using CarePlan.activity.detail OR using the CarePlan.activity.reference (a reference to a “request” resource).',
      comment:
        "The activity outcome is independent of the outcome of the related goal(s).  For example, if the goal is to achieve a target body weight of 150 lbs and an activity is defined to diet, then the activity outcome could be calories consumed whereas the goal outcome is an observation for the actual body weight measured.",
      requirements: "Links plan to resulting actions.",
      min: 0,
      max: "*",
      base: { path: "CarePlan.activity.outcomeReference", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Resource"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "workflow",
          map: "{Event that is outcome of Request in activity.reference}",
        },
        { identity: "rim", map: ".inboundRelationship[typeCode=FLFS].source" },
      ],
    },
    dataPath: "root.activity.outcomeReference[0]",
    parentDataPath: "root.activity[0]",
    basePath: "root.outcomeReference",
    baseId: "CarePlan.activity.outcomeReference",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.reference",
      path: "CarePlan.activity.reference",
      short: "Activity details defined in specific resource",
      definition:
        "The details of the proposed activity represented in a specific resource.",
      comment:
        'Standard extension exists ([resource-pertainsToGoal](extension-resource-pertainstogoal.html)) that allows goals to be referenced from any of the referenced resources in CarePlan.activity.reference.  \rThe goal should be visible when the resource referenced by CarePlan.activity.reference is viewed independently from the CarePlan.  Requests that are pointed to by a CarePlan using this element should *not* point to this CarePlan using the "basedOn" element.  i.e. Requests that are part of a CarePlan are not "based on" the CarePlan.',
      requirements:
        "Details in a form consistent with other applications and contexts of use.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.activity.reference", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Appointment",
            "http://hl7.org/fhir/StructureDefinition/CommunicationRequest",
            "http://hl7.org/fhir/StructureDefinition/DeviceRequest",
            "http://hl7.org/fhir/StructureDefinition/MedicationRequest",
            "http://hl7.org/fhir/StructureDefinition/NutritionOrder",
            "http://hl7.org/fhir/StructureDefinition/Task",
            "http://hl7.org/fhir/StructureDefinition/ServiceRequest",
            "http://hl7.org/fhir/StructureDefinition/VisionPrescription",
            "http://hl7.org/fhir/StructureDefinition/RequestGroup",
          ],
        },
      ],
      condition: ["cpl-3"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "workflow",
          map: "{Request that resulted in Event in activity.actionResulting}",
        },
        { identity: "rim", map: ".outboundRelationship[typeCode=COMP].target" },
      ],
    },
    dataPath: "root.activity.reference",
    parentDataPath: "root.activity[0]",
    basePath: "root.reference",
    baseId: "CarePlan.activity.reference",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail",
      path: "CarePlan.activity.detail",
      short: "In-line definition of activity",
      definition:
        "A simple summary of a planned activity suitable for a general care plan system (e.g. form driven) that doesn't know about specific resources such as procedure etc.",
      requirements: "Details in a simple form for generic care plan systems.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.activity.detail", min: 0, max: "1" },
      type: [{ code: "BackboneElement" }],
      condition: ["cpl-3"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP, subsetCode=SUMM].target",
        },
      ],
    },
    dataPath: "root.activity.detail",
    parentDataPath: "root.activity[0]",
    basePath: "root.detail",
    baseId: "CarePlan.activity.detail",
    isPrimitive: false,
    childPaths: [
      "root.activity.detail.kind",
      "root.activity.detail.instantiatesCanonical[0]",
      "root.activity.detail.instantiatesUri[0]",
      "root.activity.detail.code",
      "root.activity.detail.reasonCode[0]",
      "root.activity.detail.reasonReference[0]",
      "root.activity.detail.goal[0]",
      "root.activity.detail.status",
      "root.activity.detail.statusReason",
      "root.activity.detail.doNotPerform",
      "root.activity.detail.scheduled[x]",
      "root.activity.detail.location",
      "root.activity.detail.performer[0]",
      "root.activity.detail.product[x]",
      "root.activity.detail.dailyAmount",
      "root.activity.detail.quantity",
      "root.activity.detail.description",
    ],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail.kind",
      path: "CarePlan.activity.detail.kind",
      short:
        "Appointment | CommunicationRequest | DeviceRequest | MedicationRequest | NutritionOrder | Task | ServiceRequest | VisionPrescription",
      definition:
        "A description of the kind of resource the in-line definition of a care plan activity is representing.  The CarePlan.activity.detail is an in-line definition when a resource is not referenced using CarePlan.activity.reference.  For example, a MedicationRequest, a ServiceRequest, or a CommunicationRequest.",
      requirements: "May determine what types of extensions are permitted.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.activity.detail.kind", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CarePlanActivityKind",
          },
        ],
        strength: "required",
        description:
          "Resource types defined as part of FHIR that can be represented as in-line definitions of a care plan activity.",
        valueSet: "http://hl7.org/fhir/ValueSet/care-plan-activity-kind|4.3.0",
      },
      mapping: [
        {
          identity: "rim",
          map: ".inboundRelationship[typeCode=COMP].source[classCode=LIST].code",
        },
      ],
    },
    dataPath: "root.activity.detail.kind",
    parentDataPath: "root.activity.detail",
    basePath: "root.kind",
    baseId: "CarePlan.activity.detail.kind",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "Appointment" },
      { code: "CommunicationRequest" },
      { code: "DeviceRequest" },
      { code: "MedicationRequest" },
      { code: "NutritionOrder" },
      { code: "Task" },
      { code: "ServiceRequest" },
      { code: "VisionPrescription" },
    ],
  },
  {
    element: {
      id: "CarePlan.activity.detail.instantiatesCanonical",
      path: "CarePlan.activity.detail.instantiatesCanonical",
      short: "Instantiates FHIR protocol or definition",
      definition:
        "The URL pointing to a FHIR-defined protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan activity.",
      requirements:
        "Allows Questionnaires that the patient (or practitioner) should fill in to fulfill the care plan activity.",
      min: 0,
      max: "*",
      base: {
        path: "CarePlan.activity.detail.instantiatesCanonical",
        min: 0,
        max: "*",
      },
      type: [
        {
          code: "canonical",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/PlanDefinition",
            "http://hl7.org/fhir/StructureDefinition/ActivityDefinition",
            "http://hl7.org/fhir/StructureDefinition/Questionnaire",
            "http://hl7.org/fhir/StructureDefinition/Measure",
            "http://hl7.org/fhir/StructureDefinition/OperationDefinition",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "workflow", map: "Request.instantiatesCanonical" },
        { identity: "rim", map: ".outboundRelationship[typeCode=DEFN].target" },
      ],
    },
    dataPath: "root.activity.detail.instantiatesCanonical[0]",
    parentDataPath: "root.activity.detail",
    basePath: "root.instantiatesCanonical",
    baseId: "CarePlan.activity.detail.instantiatesCanonical",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail.instantiatesUri",
      path: "CarePlan.activity.detail.instantiatesUri",
      short: "Instantiates external protocol or definition",
      definition:
        "The URL pointing to an externally maintained protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan activity.",
      comment:
        "This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier.",
      requirements:
        "Allows Questionnaires that the patient (or practitioner) should fill in to fulfill the care plan activity.",
      min: 0,
      max: "*",
      base: {
        path: "CarePlan.activity.detail.instantiatesUri",
        min: 0,
        max: "*",
      },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "workflow", map: "Request.instantiatesUri" },
        { identity: "rim", map: ".outboundRelationship[typeCode=DEFN].target" },
      ],
    },
    dataPath: "root.activity.detail.instantiatesUri[0]",
    parentDataPath: "root.activity.detail",
    basePath: "root.instantiatesUri",
    baseId: "CarePlan.activity.detail.instantiatesUri",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail.reasonCode",
      path: "CarePlan.activity.detail.reasonCode",
      short: "Why activity should be done or why activity was prohibited",
      definition:
        "Provides the rationale that drove the inclusion of this particular activity as part of the plan or the reason why the activity was prohibited.",
      comment:
        "This could be a diagnosis code.  If a full condition record exists or additional detail is needed, use reasonCondition instead.",
      min: 0,
      max: "*",
      base: { path: "CarePlan.activity.detail.reasonCode", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CarePlanActivityReason",
          },
        ],
        strength: "example",
        description:
          'Identifies why a care plan activity is needed.  Can include any health condition codes as well as such concepts as "general wellness", prophylaxis, surgical preparation, etc.',
        valueSet: "http://hl7.org/fhir/ValueSet/clinical-findings",
      },
      mapping: [{ identity: "workflow", map: "Request.reasonCode" }],
    },
    dataPath: "root.activity.detail.reasonCode[0]",
    parentDataPath: "root.activity.detail",
    basePath: "root.reasonCode",
    baseId: "CarePlan.activity.detail.reasonCode",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail.goal",
      path: "CarePlan.activity.detail.goal",
      short: "Goals this activity relates to",
      definition:
        "Internal reference that identifies the goals that this activity is intended to contribute towards meeting.",
      requirements: "So that participants know the link explicitly.",
      min: 0,
      max: "*",
      base: { path: "CarePlan.activity.detail.goal", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Goal"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: ".outboundRelationship[typeCode<=OBJ]." },
      ],
    },
    dataPath: "root.activity.detail.goal[0]",
    parentDataPath: "root.activity.detail",
    basePath: "root.goal",
    baseId: "CarePlan.activity.detail.goal",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail.status",
      path: "CarePlan.activity.detail.status",
      short:
        "not-started | scheduled | in-progress | on-hold | completed | cancelled | stopped | unknown | entered-in-error",
      definition:
        "Identifies what progress is being made for the specific activity.",
      comment:
        'Some aspects of status can be inferred based on the resources linked in actionTaken.  Note that "status" is only as current as the plan was most recently updated.  \nThe unknown code is not to be used to convey other statuses.  The unknown code should be used when one of the statuses applies, but the authoring system doesn\'t know the current state of the activity.',
      requirements:
        "Indicates progress against the plan, whether the activity is still relevant for the plan.",
      min: 1,
      max: "1",
      base: { path: "CarePlan.activity.detail.status", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the activity should not be treated as valid",
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CarePlanActivityStatus",
          },
        ],
        strength: "required",
        description:
          "Codes that reflect the current state of a care plan activity within its overall life cycle.",
        valueSet:
          "http://hl7.org/fhir/ValueSet/care-plan-activity-status|4.3.0",
      },
      mapping: [
        { identity: "workflow", map: "Request.status" },
        { identity: "v2", map: "ORC-5?" },
        {
          identity: "rim",
          map: ".statusCode not-started = new scheduled = not-started (and fulfillment relationship to appointent) in-progress = active on-hold = suspended completed = completed cancelled = aborted",
        },
      ],
    },
    dataPath: "root.activity.detail.status",
    parentDataPath: "root.activity.detail",
    basePath: "root.status",
    baseId: "CarePlan.activity.detail.status",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/care-plan-activity-status",
        code: "not-started",
        display: "Not Started",
      },
      {
        system: "http://hl7.org/fhir/care-plan-activity-status",
        code: "scheduled",
        display: "Scheduled",
      },
      {
        system: "http://hl7.org/fhir/care-plan-activity-status",
        code: "in-progress",
        display: "In Progress",
      },
      {
        system: "http://hl7.org/fhir/care-plan-activity-status",
        code: "on-hold",
        display: "On Hold",
      },
      {
        system: "http://hl7.org/fhir/care-plan-activity-status",
        code: "completed",
        display: "Completed",
      },
      {
        system: "http://hl7.org/fhir/care-plan-activity-status",
        code: "cancelled",
        display: "Cancelled",
      },
      {
        system: "http://hl7.org/fhir/care-plan-activity-status",
        code: "stopped",
        display: "Stopped",
      },
      {
        system: "http://hl7.org/fhir/care-plan-activity-status",
        code: "unknown",
        display: "Unknown",
      },
      {
        system: "http://hl7.org/fhir/care-plan-activity-status",
        code: "entered-in-error",
        display: "Entered in Error",
      },
    ],
  },
  {
    element: {
      id: "CarePlan.activity.detail.doNotPerform",
      path: "CarePlan.activity.detail.doNotPerform",
      short: "If true, activity is prohibiting action",
      definition:
        "If true, indicates that the described activity is one that must NOT be engaged in when following the plan.  If false, or missing, indicates that the described activity is one that should be engaged in when following the plan.",
      comment:
        "This element is labeled as a modifier because it marks an activity as an activity that is not to be performed.",
      requirements:
        "Captures intention to not do something that may have been previously typical.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.activity.detail.doNotPerform", min: 0, max: "1" },
      type: [{ code: "boolean" }],
      meaningWhenMissing:
        "If missing indicates that the described activity is one that should be engaged in when following the plan.",
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "If true this element negates the specified action. For example, instead of a request for a procedure, it is a request for the procedure to not occur.",
      isSummary: false,
      mapping: [
        { identity: "workflow", map: "Request.doNotPerform" },
        { identity: "rim", map: "actionNegationInd" },
      ],
    },
    dataPath: "root.activity.detail.doNotPerform",
    parentDataPath: "root.activity.detail",
    basePath: "root.doNotPerform",
    baseId: "CarePlan.activity.detail.doNotPerform",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail.location",
      path: "CarePlan.activity.detail.location",
      short: "Where it should happen",
      definition:
        "Identifies the facility where the activity will occur; e.g. home, hospital, specific clinic, etc.",
      comment:
        "May reference a specific clinical location or may identify a type of location.",
      requirements: "Helps in planning of activity.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.activity.detail.location", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Location"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "v2", map: "OBR-24(???!!)" },
        { identity: "rim", map: ".participation[typeCode=LOC].role" },
      ],
    },
    dataPath: "root.activity.detail.location",
    parentDataPath: "root.activity.detail",
    basePath: "root.location",
    baseId: "CarePlan.activity.detail.location",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail.product[x]",
      path: "CarePlan.activity.detail.product[x]",
      short: "What is to be administered/supplied",
      definition:
        "Identifies the food, drug or other product to be consumed or supplied in the activity.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.activity.detail.product[x]", min: 0, max: "1" },
      type: [
        { code: "CodeableConcept" },
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Medication",
            "http://hl7.org/fhir/StructureDefinition/Substance",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CarePlanProduct",
          },
        ],
        strength: "example",
        description:
          "A product supplied or administered as part of a care plan activity.",
        valueSet: "http://hl7.org/fhir/ValueSet/medication-codes",
      },
      mapping: [
        { identity: "v2", map: "RXE-2 / RXO-1 / RXD-2" },
        { identity: "rim", map: ".participation[typeCode=PRD].role" },
      ],
    },
    dataPath: "root.activity.detail.product[x]",
    parentDataPath: "root.activity.detail",
    basePath: "root.product[x]",
    baseId: "CarePlan.activity.detail.product[x]",
    isPrimitive: false,
    childPaths: [],
    multiTypeType: "CodeableConcept",
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail.quantity",
      path: "CarePlan.activity.detail.quantity",
      short: "How much to administer/supply/consume",
      definition:
        "Identifies the quantity expected to be supplied, administered or consumed by the subject.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.activity.detail.quantity", min: 0, max: "1" },
      type: [
        {
          code: "Quantity",
          profile: ["http://hl7.org/fhir/StructureDefinition/SimpleQuantity"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "v2",
          map: "RXO-11 / RXE-10 / RXD-4 / RXG-5 / RXA-6 /  TQ1-2.1  *and*  RXO-12 /  RXE-11 / RXD-5 / RXG-7 / RXA-7 / TQ1-2.2",
        },
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP][classCode=SPLY].quantity",
        },
      ],
    },
    dataPath: "root.activity.detail.quantity",
    parentDataPath: "root.activity.detail",
    basePath: "root.quantity",
    baseId: "CarePlan.activity.detail.quantity",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan.activity.detail.description",
      path: "CarePlan.activity.detail.description",
      short: "Extra info describing activity to perform",
      definition:
        "This provides a textual description of constraints on the intended activity occurrence, including relation to other activities.  It may also include objectives, pre-conditions and end-conditions.  Finally, it may convey specifics about the activity such as body site, method, route, etc.",
      min: 0,
      max: "1",
      base: { path: "CarePlan.activity.detail.description", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "v2", map: "NTE?" },
        { identity: "rim", map: ".text" },
      ],
    },
    dataPath: "root.activity.detail.description",
    parentDataPath: "root.activity.detail",
    basePath: "root.description",
    baseId: "CarePlan.activity.detail.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "CarePlan",
      path: "CarePlan",
      short: "Healthcare plan for patient or group",
      definition:
        "Describes the intention of how one or more practitioners intend to deliver care for a particular patient, group or community for a period of time, possibly limited to care for a specific condition or set of conditions.",
      alias: ["Care Team"],
      min: 0,
      max: "*",
      base: { path: "CarePlan", min: 0, max: "*" },
      constraint: [
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "workflow", map: "Request" },
        { identity: "rim", map: "Act[classCode=PCPR, moodCode=INT]" },
        { identity: "w5", map: "clinical.careprovision" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "CarePlan",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
