const data = [
  {
    element: {
      id: "Communication.meta",
      path: "Communication.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "Communication.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.implicitRules",
      path: "Communication.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "Communication.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.language",
      path: "Communication.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "Communication.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "Communication.contained",
      path: "Communication.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source: "http://hl7.org/fhir/StructureDefinition/Communication",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "Communication.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.instantiatesCanonical",
      path: "Communication.instantiatesCanonical",
      short: "Instantiates FHIR protocol or definition",
      definition:
        "The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this Communication.",
      min: 0,
      max: "*",
      base: { path: "Communication.instantiatesCanonical", min: 0, max: "*" },
      type: [
        {
          code: "canonical",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/PlanDefinition",
            "http://hl7.org/fhir/StructureDefinition/ActivityDefinition",
            "http://hl7.org/fhir/StructureDefinition/Measure",
            "http://hl7.org/fhir/StructureDefinition/OperationDefinition",
            "http://hl7.org/fhir/StructureDefinition/Questionnaire",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.instantiatesCanonical" },
        { identity: "rim", map: ".outboundRelationship[typeCode=DEFN].target" },
      ],
    },
    dataPath: "root.instantiatesCanonical[0]",
    parentDataPath: "root",
    basePath: "root.instantiatesCanonical",
    baseId: "Communication.instantiatesCanonical",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.instantiatesUri",
      path: "Communication.instantiatesUri",
      short: "Instantiates external protocol or definition",
      definition:
        "The URL pointing to an externally maintained protocol, guideline, orderset or other definition that is adhered to in whole or in part by this Communication.",
      comment:
        "This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier.",
      min: 0,
      max: "*",
      base: { path: "Communication.instantiatesUri", min: 0, max: "*" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.instantiatesUri" },
        { identity: "rim", map: ".outboundRelationship[typeCode=DEFN].target" },
      ],
    },
    dataPath: "root.instantiatesUri[0]",
    parentDataPath: "root",
    basePath: "root.instantiatesUri",
    baseId: "Communication.instantiatesUri",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.partOf",
      path: "Communication.partOf",
      short: "Part of this action",
      definition: "Part of this action.",
      alias: ["container"],
      min: 0,
      max: "*",
      base: { path: "Communication.partOf", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Resource"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "workflow", map: "Event.partOf" }],
    },
    dataPath: "root.partOf[0]",
    parentDataPath: "root",
    basePath: "root.partOf",
    baseId: "Communication.partOf",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.status",
      path: "Communication.status",
      short:
        "preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown",
      definition: "The status of the transmission.",
      comment:
        "This element is labeled as a modifier because the status contains the codes aborted and entered-in-error that mark the communication as not currently valid.",
      min: 1,
      max: "1",
      base: { path: "Communication.status", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid",
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CommunicationStatus",
          },
        ],
        strength: "required",
        description: "The status of the communication.",
        valueSet: "http://hl7.org/fhir/ValueSet/event-status|4.3.0",
      },
      mapping: [
        { identity: "workflow", map: "Event.status" },
        { identity: "w5", map: "FiveWs.status" },
      ],
    },
    dataPath: "root.status",
    parentDataPath: "root",
    basePath: "root.status",
    baseId: "Communication.status",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/event-status",
        code: "preparation",
        display: "Preparation",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "in-progress",
        display: "In Progress",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "not-done",
        display: "Not Done",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "on-hold",
        display: "On Hold",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "stopped",
        display: "Stopped",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "completed",
        display: "Completed",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "entered-in-error",
        display: "Entered in Error",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "unknown",
        display: "Unknown",
      },
    ],
  },
  {
    element: {
      id: "Communication.statusReason",
      path: "Communication.statusReason",
      short: "Reason for current status",
      definition:
        "Captures the reason for the current state of the Communication.",
      comment:
        'This is generally only used for "exception" statuses such as "not-done", "suspended" or "aborted". The reason for performing the event at all is captured in reasonCode, not here.',
      alias: ["Suspended Reason", "Cancelled Reason"],
      min: 0,
      max: "1",
      base: { path: "Communication.statusReason", min: 0, max: "1" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CommunicationNotDoneReason",
          },
        ],
        strength: "example",
        description: "Codes for the reason why a communication did not happen.",
        valueSet: "http://hl7.org/fhir/ValueSet/communication-not-done-reason",
      },
      mapping: [{ identity: "workflow", map: "Event.statusReason" }],
    },
    dataPath: "root.statusReason",
    parentDataPath: "root",
    basePath: "root.statusReason",
    baseId: "Communication.statusReason",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system:
          "http://terminology.hl7.org/CodeSystem/communication-not-done-reason",
        code: "unknown",
        display: "Unknown",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/communication-not-done-reason",
        code: "system-error",
        display: "System Error",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/communication-not-done-reason",
        code: "invalid-phone-number",
        display: "Invalid Phone Number",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/communication-not-done-reason",
        code: "recipient-unavailable",
        display: "Recipient Unavailable",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/communication-not-done-reason",
        code: "family-objection",
        display: "Family Objection",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/communication-not-done-reason",
        code: "patient-objection",
        display: "Patient Objection",
      },
    ],
  },
  {
    element: {
      id: "Communication.category",
      path: "Communication.category",
      short: "Message category",
      definition:
        "The type of message conveyed such as alert, notification, reminder, instruction, etc.",
      comment:
        "There may be multiple axes of categorization and one communication may serve multiple purposes.",
      min: 0,
      max: "*",
      base: { path: "Communication.category", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CommunicationCategory",
          },
        ],
        strength: "example",
        description:
          "Codes for general categories of communications such as alerts, instructions, etc.",
        valueSet: "http://hl7.org/fhir/ValueSet/communication-category",
      },
      mapping: [{ identity: "w5", map: "FiveWs.class" }],
    },
    dataPath: "root.category[0]",
    parentDataPath: "root",
    basePath: "root.category",
    baseId: "Communication.category",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-category",
        code: "alert",
        display: "Alert",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-category",
        code: "notification",
        display: "Notification",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-category",
        code: "reminder",
        display: "Reminder",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-category",
        code: "instruction",
        display: "Instruction",
      },
    ],
  },
  {
    element: {
      id: "Communication.priority",
      path: "Communication.priority",
      short: "routine | urgent | asap | stat",
      definition:
        "Characterizes how quickly the planned or in progress communication must be addressed. Includes concepts such as stat, urgent, routine.",
      comment:
        "Used to prioritize workflow (such as which communication to read first) when the communication is planned or in progress.",
      min: 0,
      max: "1",
      base: { path: "Communication.priority", min: 0, max: "1" },
      type: [{ code: "code" }],
      meaningWhenMissing:
        "If missing, this communication should be treated with normal priority",
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CommunicationPriority",
          },
        ],
        strength: "required",
        description:
          "Codes indicating the relative importance of a communication.",
        valueSet: "http://hl7.org/fhir/ValueSet/request-priority|4.3.0",
      },
      mapping: [{ identity: "w5", map: "FiveWs.grade" }],
    },
    dataPath: "root.priority",
    parentDataPath: "root",
    basePath: "root.priority",
    baseId: "Communication.priority",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/request-priority",
        code: "routine",
        display: "Routine",
      },
      {
        system: "http://hl7.org/fhir/request-priority",
        code: "urgent",
        display: "Urgent",
      },
      {
        system: "http://hl7.org/fhir/request-priority",
        code: "asap",
        display: "ASAP",
      },
      {
        system: "http://hl7.org/fhir/request-priority",
        code: "stat",
        display: "STAT",
      },
    ],
  },
  {
    element: {
      id: "Communication.medium",
      path: "Communication.medium",
      short: "A channel of communication",
      definition:
        "A channel that was used for this communication (e.g. email, fax).",
      min: 0,
      max: "*",
      base: { path: "Communication.medium", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CommunicationMedium",
          },
        ],
        strength: "example",
        description:
          "Codes for communication mediums such as phone, fax, email, in person, etc.",
        valueSet: "http://terminology.hl7.org/ValueSet/v3-ParticipationMode",
      },
    },
    dataPath: "root.medium[0]",
    parentDataPath: "root",
    basePath: "root.medium",
    baseId: "Communication.medium",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [{ code: "PHYSICAL" }, { code: "REMOTE" }],
  },
  {
    element: {
      id: "Communication.topic",
      path: "Communication.topic",
      short: "Description of the purpose/content",
      definition:
        "Description of the purpose/content, similar to a subject line in an email.",
      comment: "Communication.topic.text can be used without any codings.",
      min: 0,
      max: "1",
      base: { path: "Communication.topic", min: 0, max: "1" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CommunicationTopic",
          },
        ],
        strength: "example",
        description:
          "Codes describing the purpose or content of the communication.",
        valueSet: "http://hl7.org/fhir/ValueSet/communication-topic",
      },
      mapping: [{ identity: "w5", map: "FiveWs.context" }],
    },
    dataPath: "root.topic",
    parentDataPath: "root",
    basePath: "root.topic",
    baseId: "Communication.topic",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-topic",
        code: "prescription-refill-request",
        display: "Prescription Refill Request",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-topic",
        code: "progress-update",
        display: "Progress Update",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-topic",
        code: "report-labs",
        display: "Report Labs",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-topic",
        code: "appointment-reminder",
        display: "Appointment Reminder",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-topic",
        code: "phone-consult",
        display: "Phone Consult",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/communication-topic",
        code: "summary-report",
        display: "Summary Report",
      },
    ],
  },
  {
    element: {
      id: "Communication.encounter",
      path: "Communication.encounter",
      short: "Encounter created as part of",
      definition:
        "The Encounter during which this Communication was created or to which the creation of this record is tightly associated.",
      comment:
        "This will typically be the encounter the event occurred within, but some activities may be initiated prior to or after the official completion of an encounter but still be tied to the context of the encounter.",
      min: 0,
      max: "1",
      base: { path: "Communication.encounter", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Encounter"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.context" },
        { identity: "w5", map: "FiveWs.context" },
      ],
    },
    dataPath: "root.encounter",
    parentDataPath: "root",
    basePath: "root.encounter",
    baseId: "Communication.encounter",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.sent",
      path: "Communication.sent",
      short: "When sent",
      definition: "The time when this communication was sent.",
      min: 0,
      max: "1",
      base: { path: "Communication.sent", min: 0, max: "1" },
      type: [{ code: "dateTime" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "workflow",
          map: "Event.occurrence[x] {Invariant: maps to period.start}",
        },
        { identity: "w5", map: "FiveWs.done[x]" },
      ],
    },
    dataPath: "root.sent",
    parentDataPath: "root",
    basePath: "root.sent",
    baseId: "Communication.sent",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.received",
      path: "Communication.received",
      short: "When received",
      definition:
        "The time when this communication arrived at the destination.",
      min: 0,
      max: "1",
      base: { path: "Communication.received", min: 0, max: "1" },
      type: [{ code: "dateTime" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "workflow",
          map: "Event.occurrence[x] {Invariant: maps to period.end}",
        },
        { identity: "w5", map: "FiveWs.done[x]" },
      ],
    },
    dataPath: "root.received",
    parentDataPath: "root",
    basePath: "root.received",
    baseId: "Communication.received",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.sender",
      path: "Communication.sender",
      short: "Message sender",
      definition:
        "The entity (e.g. person, organization, clinical information system, or device) which was the source of the communication.",
      min: 0,
      max: "1",
      base: { path: "Communication.sender", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Device",
            "http://hl7.org/fhir/StructureDefinition/Organization",
            "http://hl7.org/fhir/StructureDefinition/Patient",
            "http://hl7.org/fhir/StructureDefinition/Practitioner",
            "http://hl7.org/fhir/StructureDefinition/PractitionerRole",
            "http://hl7.org/fhir/StructureDefinition/RelatedPerson",
            "http://hl7.org/fhir/StructureDefinition/HealthcareService",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "workflow", map: "Event.performer.actor" },
        { identity: "w5", map: "FiveWs.actor" },
      ],
    },
    dataPath: "root.sender",
    parentDataPath: "root",
    basePath: "root.sender",
    baseId: "Communication.sender",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.reasonReference",
      path: "Communication.reasonReference",
      short: "Why was communication done?",
      definition:
        "Indicates another resource whose existence justifies this communication.",
      min: 0,
      max: "*",
      base: { path: "Communication.reasonReference", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Condition",
            "http://hl7.org/fhir/StructureDefinition/Observation",
            "http://hl7.org/fhir/StructureDefinition/DiagnosticReport",
            "http://hl7.org/fhir/StructureDefinition/DocumentReference",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.reasonReference" },
        { identity: "w5", map: "FiveWs.why[x]" },
        { identity: "rim", map: ".outboundRelationship[typeCode=RSON].target" },
      ],
    },
    dataPath: "root.reasonReference[0]",
    parentDataPath: "root",
    basePath: "root.reasonReference",
    baseId: "Communication.reasonReference",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication.payload",
      path: "Communication.payload",
      short: "Message payload",
      definition:
        "Text, attachment(s), or resource(s) that was communicated to the recipient.",
      min: 0,
      max: "*",
      base: { path: "Communication.payload", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.payload[0]",
    parentDataPath: "root",
    basePath: "root.payload",
    baseId: "Communication.payload",
    isPrimitive: false,
    childPaths: ["root.payload.content[x]"],
    value: "",
  },
  {
    element: {
      id: "Communication.note",
      path: "Communication.note",
      short: "Comments made about the communication",
      definition:
        "Additional notes or commentary about the communication by the sender, receiver or other interested parties.",
      min: 0,
      max: "*",
      base: { path: "Communication.note", min: 0, max: "*" },
      type: [{ code: "Annotation" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "workflow", map: "Event.note" }],
    },
    dataPath: "root.note[0]",
    parentDataPath: "root",
    basePath: "root.note",
    baseId: "Communication.note",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Communication",
      path: "Communication",
      short: "A record of information transmitted from a sender to a receiver",
      definition:
        "An occurrence of information being transmitted; e.g. an alert that was sent to a responsible provider, a public health agency that was notified about a reportable condition.",
      min: 0,
      max: "*",
      base: { path: "Communication", min: 0, max: "*" },
      constraint: [
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "workflow", map: "Event" },
        { identity: "w5", map: "workflow.encounter" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "Communication",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
