const data = [
  {
    element: {
      id: "EvidenceVariable.meta",
      path: "EvidenceVariable.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "EvidenceVariable.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.implicitRules",
      path: "EvidenceVariable.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "EvidenceVariable.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.language",
      path: "EvidenceVariable.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "EvidenceVariable.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "EvidenceVariable.contained",
      path: "EvidenceVariable.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source: "http://hl7.org/fhir/StructureDefinition/EvidenceVariable",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "EvidenceVariable.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.url",
      path: "EvidenceVariable.url",
      short:
        "Canonical identifier for this evidence variable, represented as a URI (globally unique)",
      definition:
        "An absolute URI that is used to identify this evidence variable when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this evidence variable is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the evidence variable is stored on different servers.",
      comment:
        "Can be a urn:uuid: or a urn:oid: but real http: addresses are preferred.  Multiple instances may share the same URL if they have a distinct version.\n\nThe determination of when to create a new version of a resource (same url, new version) vs. defining a new artifact is up to the author.  Considerations for making this decision are found in [Technical and Business Versions](resource.html#versions). \n\nIn some cases, the resource can no longer be found at the stated url, but the url itself cannot change. Implementations can use the [meta.source](resource.html#meta) element to indicate where the current master source of the resource can be found.",
      requirements:
        "Allows the evidence variable to be referenced by a single globally unique identifier.",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.url", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.url" },
        { identity: "w5", map: "FiveWs.identifier" },
      ],
    },
    dataPath: "root.url",
    parentDataPath: "root",
    basePath: "root.url",
    baseId: "EvidenceVariable.url",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.version",
      path: "EvidenceVariable.version",
      short: "Business version of the evidence variable",
      definition:
        "The identifier that is used to identify this version of the evidence variable when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the evidence variable author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence. To provide a version consistent with the Decision Support Service specification, use the format Major.Minor.Revision (e.g. 1.0.0). For more information on versioning knowledge assets, refer to the Decision Support Service specification. Note that a version is required for non-experimental active artifacts.",
      comment:
        "There may be different evidence variable instances that have the same identifier but different versions.  The version can be appended to the url in a reference to allow a reference to a particular business version of the evidence variable with the format [url]|[version].",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.version", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.version" },
        { identity: "w5", map: "FiveWs.version" },
      ],
    },
    dataPath: "root.version",
    parentDataPath: "root",
    basePath: "root.version",
    baseId: "EvidenceVariable.version",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.name",
      path: "EvidenceVariable.name",
      short: "Name for this evidence variable (computer friendly)",
      definition:
        "A natural language name identifying the evidence variable. This name should be usable as an identifier for the module by machine processing applications such as code generation.",
      comment:
        "The name is not expected to be globally unique. The name should be a simple alphanumeric type name to ensure that it is machine-processing friendly.",
      requirements: "Support human navigation and code generation.",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.name", min: 0, max: "1" },
      type: [{ code: "string" }],
      condition: ["cnl-0"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.name",
    parentDataPath: "root",
    basePath: "root.name",
    baseId: "EvidenceVariable.name",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.title",
      path: "EvidenceVariable.title",
      short: "Name for this evidence variable (human friendly)",
      definition:
        "A short, descriptive, user-friendly title for the evidence variable.",
      comment:
        "This name does not need to be machine-processing friendly and may contain punctuation, white-space, etc.",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.title", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "workflow", map: "Definition.title" }],
    },
    dataPath: "root.title",
    parentDataPath: "root",
    basePath: "root.title",
    baseId: "EvidenceVariable.title",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.shortTitle",
      path: "EvidenceVariable.shortTitle",
      short: "Title for use in informal contexts",
      definition:
        "The short title provides an alternate title for use in informal descriptive contexts where the full, formal title is not necessary.",
      requirements:
        "Need to be able to reference the content by a short description, but still provide a longer, more formal title for the content.",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.shortTitle", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.shortTitle",
    parentDataPath: "root",
    basePath: "root.shortTitle",
    baseId: "EvidenceVariable.shortTitle",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.subtitle",
      path: "EvidenceVariable.subtitle",
      short: "Subordinate title of the EvidenceVariable",
      definition:
        "An explanatory or alternate title for the EvidenceVariable giving additional information about its content.",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.subtitle", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.subtitle",
    parentDataPath: "root",
    basePath: "root.subtitle",
    baseId: "EvidenceVariable.subtitle",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.status",
      path: "EvidenceVariable.status",
      short: "draft | active | retired | unknown",
      definition:
        "The status of this evidence variable. Enables tracking the life-cycle of the content.",
      comment:
        "Allows filtering of evidence variables that are appropriate for use versus not.",
      min: 1,
      max: "1",
      base: { path: "EvidenceVariable.status", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        'This is labeled as "Is Modifier" because applications should not use a retired {{title}} without due consideration',
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "PublicationStatus",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "required",
        description: "The lifecycle status of an artifact.",
        valueSet: "http://hl7.org/fhir/ValueSet/publication-status|4.3.0",
      },
      mapping: [
        { identity: "workflow", map: "Definition.status" },
        { identity: "w5", map: "FiveWs.status" },
      ],
    },
    dataPath: "root.status",
    parentDataPath: "root",
    basePath: "root.status",
    baseId: "EvidenceVariable.status",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "draft",
        display: "Draft",
      },
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "active",
        display: "Active",
      },
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "retired",
        display: "Retired",
      },
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "unknown",
        display: "Unknown",
      },
    ],
  },
  {
    element: {
      id: "EvidenceVariable.date",
      path: "EvidenceVariable.date",
      short: "Date last changed",
      definition:
        "The date  (and optionally time) when the evidence variable was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the evidence variable changes.",
      comment:
        "Note that this is not the same as the resource last-modified-date, since the resource may be a secondary representation of the evidence variable. Additional specific dates may be added as extensions or be found by consulting Provenances associated with past versions of the resource.",
      alias: ["Revision Date"],
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.date", min: 0, max: "1" },
      type: [{ code: "dateTime" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.date" },
        { identity: "w5", map: "FiveWs.recorded" },
      ],
    },
    dataPath: "root.date",
    parentDataPath: "root",
    basePath: "root.date",
    baseId: "EvidenceVariable.date",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.description",
      path: "EvidenceVariable.description",
      short: "Natural language description of the evidence variable",
      definition:
        "A free text natural language description of the evidence variable from a consumer's perspective.",
      comment:
        "This description can be used to capture details such as why the evidence variable was built, comments about misuse, instructions for clinical use and interpretation, literature references, examples from the paper world, etc. It is not a rendering of the evidence variable as conveyed in the 'text' field of the resource itself. This item SHOULD be populated unless the information is available from context (e.g. the language of the evidence variable is presumed to be the predominant language in the place the evidence variable was created).",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.description", min: 0, max: "1" },
      type: [{ code: "markdown" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "workflow", map: "Definition.description" }],
    },
    dataPath: "root.description",
    parentDataPath: "root",
    basePath: "root.description",
    baseId: "EvidenceVariable.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.useContext",
      path: "EvidenceVariable.useContext",
      short: "The context that the content is intended to support",
      definition:
        "The content was developed with a focus and intent of supporting the contexts that are listed. These contexts may be general categories (gender, age, ...) or may be references to specific programs (insurance plans, studies, ...) and may be used to assist with indexing and searching for appropriate evidence variable instances.",
      comment:
        "When multiple useContexts are specified, there is no expectation that all or any of the contexts apply.",
      requirements: "Assist in searching for appropriate content.",
      min: 0,
      max: "*",
      base: { path: "EvidenceVariable.useContext", min: 0, max: "*" },
      type: [{ code: "UsageContext" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "workflow", map: "Definition.useContext" }],
    },
    dataPath: "root.useContext[0]",
    parentDataPath: "root",
    basePath: "root.useContext",
    baseId: "EvidenceVariable.useContext",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.publisher",
      path: "EvidenceVariable.publisher",
      short: "Name of the publisher (organization or individual)",
      definition:
        "The name of the organization or individual that published the evidence variable.",
      comment:
        "Usually an organization but may be an individual. The publisher (or steward) of the evidence variable is the organization or individual primarily responsible for the maintenance and upkeep of the evidence variable. This is not necessarily the same individual or organization that developed and initially authored the content. The publisher is the primary point of contact for questions or issues with the evidence variable. This item SHOULD be populated unless the information is available from context.",
      requirements:
        'Helps establish the "authority/credibility" of the evidence variable.  May also allow for contact.',
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.publisher", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.publisher" },
        { identity: "w5", map: "FiveWs.witness" },
      ],
    },
    dataPath: "root.publisher",
    parentDataPath: "root",
    basePath: "root.publisher",
    baseId: "EvidenceVariable.publisher",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.author",
      path: "EvidenceVariable.author",
      short: "Who authored the content",
      definition:
        "An individiual or organization primarily involved in the creation and maintenance of the content.",
      comment:
        "Extensions to ContactDetail include: contactReference, contactAddress, and contributionTime (Details at: http://build.fhir.org/clinicalreasoning-module.html).",
      min: 0,
      max: "*",
      base: { path: "EvidenceVariable.author", min: 0, max: "*" },
      type: [{ code: "ContactDetail" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: ".participation[typeCode=AUT]" }],
    },
    dataPath: "root.author[0]",
    parentDataPath: "root",
    basePath: "root.author",
    baseId: "EvidenceVariable.author",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.reviewer",
      path: "EvidenceVariable.reviewer",
      short: "Who reviewed the content",
      definition:
        "An individual or organization primarily responsible for review of some aspect of the content.",
      comment:
        "Extensions to ContactDetail include: contactReference, contactAddress, and contributionTime (Details at: http://build.fhir.org/clinicalreasoning-module.html).",
      min: 0,
      max: "*",
      base: { path: "EvidenceVariable.reviewer", min: 0, max: "*" },
      type: [{ code: "ContactDetail" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".participation[typeCode=VRF] {not clear whether VRF best corresponds to reviewer or endorser}",
        },
      ],
    },
    dataPath: "root.reviewer[0]",
    parentDataPath: "root",
    basePath: "root.reviewer",
    baseId: "EvidenceVariable.reviewer",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.relatedArtifact",
      path: "EvidenceVariable.relatedArtifact",
      short: "Additional documentation, citations, etc.",
      definition:
        "Related artifacts such as additional documentation, justification, or bibliographic references.",
      comment:
        "Each related artifact is either an attachment, or a reference to another resource, but not both.",
      requirements:
        "EvidenceVariables must be able to provide enough information for consumers of the content (and/or interventions or results produced by the content) to be able to determine and understand the justification for and evidence in support of the content.",
      min: 0,
      max: "*",
      base: { path: "EvidenceVariable.relatedArtifact", min: 0, max: "*" },
      type: [{ code: "RelatedArtifact" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.relatedArtifact[0]",
    parentDataPath: "root",
    basePath: "root.relatedArtifact",
    baseId: "EvidenceVariable.relatedArtifact",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.actual",
      path: "EvidenceVariable.actual",
      short: "Actual or conceptual",
      definition:
        "True if the actual variable measured, false if a conceptual representation of the intended variable.",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.actual", min: 0, max: "1" },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.actual",
    parentDataPath: "root",
    basePath: "root.actual",
    baseId: "EvidenceVariable.actual",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.characteristicCombination",
      path: "EvidenceVariable.characteristicCombination",
      short: "intersection | union",
      definition:
        "Used to specify if two or more characteristics are combined with OR or AND.",
      min: 0,
      max: "1",
      base: {
        path: "EvidenceVariable.characteristicCombination",
        min: 0,
        max: "1",
      },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CharacteristicCombination",
          },
        ],
        strength: "required",
        description: "Logical grouping of characteristics.",
        valueSet:
          "http://hl7.org/fhir/ValueSet/characteristic-combination|4.3.0",
      },
    },
    dataPath: "root.characteristicCombination",
    parentDataPath: "root",
    basePath: "root.characteristicCombination",
    baseId: "EvidenceVariable.characteristicCombination",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/characteristic-combination",
        code: "intersection",
        display: "intersection",
      },
      {
        system: "http://hl7.org/fhir/characteristic-combination",
        code: "union",
        display: "union",
      },
    ],
  },
  {
    element: {
      id: "EvidenceVariable.characteristic",
      path: "EvidenceVariable.characteristic",
      short: "What defines the members of the evidence element",
      definition:
        'A characteristic that defines the members of the evidence element. Multiple characteristics are applied with "and" semantics.',
      comment:
        "Characteristics can be defined flexibly to accommodate different use cases for membership criteria, ranging from simple codes, all the way to using an expression language to express the criteria.",
      min: 0,
      max: "*",
      base: { path: "EvidenceVariable.characteristic", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.characteristic[0]",
    parentDataPath: "root",
    basePath: "root.characteristic",
    baseId: "EvidenceVariable.characteristic",
    isPrimitive: false,
    childPaths: [
      "root.characteristic.description",
      "root.characteristic.definition[x]",
      "root.characteristic.method",
      "root.characteristic.device",
      "root.characteristic.exclude",
      "root.characteristic.timeFromStart",
      "root.characteristic.groupMeasure",
    ],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.characteristic.description",
      path: "EvidenceVariable.characteristic.description",
      short: "Natural language description of the characteristic",
      definition:
        "A short, natural language description of the characteristic that could be used to communicate the criteria to an end-user.",
      requirements:
        "Need to be able to describe characteristics in natural language so that end users can understand the criteria.",
      min: 0,
      max: "1",
      base: {
        path: "EvidenceVariable.characteristic.description",
        min: 0,
        max: "1",
      },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.characteristic.description",
    parentDataPath: "root.characteristic[0]",
    basePath: "root.description",
    baseId: "EvidenceVariable.characteristic.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.characteristic.method",
      path: "EvidenceVariable.characteristic.method",
      short: "Method used for describing characteristic",
      definition: "Method used for describing characteristic.",
      min: 0,
      max: "1",
      base: {
        path: "EvidenceVariable.characteristic.method",
        min: 0,
        max: "1",
      },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CharacteristicMethod",
          },
        ],
        strength: "example",
        description:
          "The method used to determine the characteristic(s) of the variable.",
        valueSet: "http://hl7.org/fhir/ValueSet/characteristic-method",
      },
    },
    dataPath: "root.characteristic.method",
    parentDataPath: "root.characteristic[0]",
    basePath: "root.method",
    baseId: "EvidenceVariable.characteristic.method",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://terminology.hl7.org/CodeSystem/characteristic-method",
        code: "Default",
        display: "Default",
      },
    ],
  },
  {
    element: {
      id: "EvidenceVariable.characteristic.exclude",
      path: "EvidenceVariable.characteristic.exclude",
      short: "Whether the characteristic includes or excludes members",
      definition:
        "When true, members with this characteristic are excluded from the element.",
      min: 0,
      max: "1",
      base: {
        path: "EvidenceVariable.characteristic.exclude",
        min: 0,
        max: "1",
      },
      type: [{ code: "boolean" }],
      meaningWhenMissing: "False",
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.characteristic.exclude",
    parentDataPath: "root.characteristic[0]",
    basePath: "root.exclude",
    baseId: "EvidenceVariable.characteristic.exclude",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.characteristic.timeFromStart",
      path: "EvidenceVariable.characteristic.timeFromStart",
      short: "Observation time from study start",
      definition:
        "Indicates duration, period, or point of observation from the participant's study entry.",
      min: 0,
      max: "1",
      base: {
        path: "EvidenceVariable.characteristic.timeFromStart",
        min: 0,
        max: "1",
      },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.characteristic.timeFromStart",
    parentDataPath: "root.characteristic[0]",
    basePath: "root.timeFromStart",
    baseId: "EvidenceVariable.characteristic.timeFromStart",
    isPrimitive: false,
    childPaths: [
      "root.characteristic.timeFromStart.description",
      "root.characteristic.timeFromStart.quantity",
      "root.characteristic.timeFromStart.range",
      "root.characteristic.timeFromStart.note[0]",
    ],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.characteristic.timeFromStart.description",
      path: "EvidenceVariable.characteristic.timeFromStart.description",
      short: "Human readable description",
      definition: "A short, natural language description.",
      min: 0,
      max: "1",
      base: {
        path: "EvidenceVariable.characteristic.timeFromStart.description",
        min: 0,
        max: "1",
      },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.characteristic.timeFromStart.description",
    parentDataPath: "root.characteristic.timeFromStart",
    basePath: "root.description",
    baseId: "EvidenceVariable.characteristic.timeFromStart.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.characteristic.timeFromStart.range",
      path: "EvidenceVariable.characteristic.timeFromStart.range",
      short:
        "Used to express the observation within a period after the study start",
      definition:
        "Used to express the observation within a period after the study start.",
      min: 0,
      max: "1",
      base: {
        path: "EvidenceVariable.characteristic.timeFromStart.range",
        min: 0,
        max: "1",
      },
      type: [{ code: "Range" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.characteristic.timeFromStart.range",
    parentDataPath: "root.characteristic.timeFromStart",
    basePath: "root.range",
    baseId: "EvidenceVariable.characteristic.timeFromStart.range",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.characteristic.groupMeasure",
      path: "EvidenceVariable.characteristic.groupMeasure",
      short:
        "mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-median",
      definition:
        "Indicates how elements are aggregated within the study effective period.",
      min: 0,
      max: "1",
      base: {
        path: "EvidenceVariable.characteristic.groupMeasure",
        min: 0,
        max: "1",
      },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "GroupMeasure",
          },
        ],
        strength: "required",
        description: "Possible group measure aggregates (E.g. Mean, Median).",
        valueSet: "http://hl7.org/fhir/ValueSet/group-measure|4.3.0",
      },
    },
    dataPath: "root.characteristic.groupMeasure",
    parentDataPath: "root.characteristic[0]",
    basePath: "root.groupMeasure",
    baseId: "EvidenceVariable.characteristic.groupMeasure",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/group-measure",
        code: "mean",
        display: "Mean",
      },
      {
        system: "http://hl7.org/fhir/group-measure",
        code: "median",
        display: "Median",
      },
      {
        system: "http://hl7.org/fhir/group-measure",
        code: "mean-of-mean",
        display: "Mean of Study Means",
      },
      {
        system: "http://hl7.org/fhir/group-measure",
        code: "mean-of-median",
        display: "Mean of Study Medins",
      },
      {
        system: "http://hl7.org/fhir/group-measure",
        code: "median-of-mean",
        display: "Median of Study Means",
      },
      {
        system: "http://hl7.org/fhir/group-measure",
        code: "median-of-median",
        display: "Median of Study Medians",
      },
    ],
  },
  {
    element: {
      id: "EvidenceVariable.handling",
      path: "EvidenceVariable.handling",
      short: "continuous | dichotomous | ordinal | polychotomous",
      definition: "Used for an outcome to classify.",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.handling", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "EvidenceVariableHandling",
          },
        ],
        strength: "required",
        description:
          "The handling of the variable in statistical analysis for exposures or outcomes (E.g. Dichotomous, Continuous, Descriptive).",
        valueSet: "http://hl7.org/fhir/ValueSet/variable-handling|4.3.0",
      },
    },
    dataPath: "root.handling",
    parentDataPath: "root",
    basePath: "root.handling",
    baseId: "EvidenceVariable.handling",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/variable-handling",
        code: "continuous",
        display: "continuous variable",
      },
      {
        system: "http://hl7.org/fhir/variable-handling",
        code: "dichotomous",
        display: "dichotomous variable",
      },
      {
        system: "http://hl7.org/fhir/variable-handling",
        code: "ordinal",
        display: "ordinal variable",
      },
      {
        system: "http://hl7.org/fhir/variable-handling",
        code: "polychotomous",
        display: "polychotomous variable",
      },
    ],
  },
  {
    element: {
      id: "EvidenceVariable.category",
      path: "EvidenceVariable.category",
      short: "A grouping for ordinal or polychotomous variables",
      definition:
        "A grouping (or set of values) described along with other groupings to specify the set of groupings allowed for the variable.",
      min: 0,
      max: "*",
      base: { path: "EvidenceVariable.category", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.category[0]",
    parentDataPath: "root",
    basePath: "root.category",
    baseId: "EvidenceVariable.category",
    isPrimitive: false,
    childPaths: ["root.category.name", "root.category.value[x]"],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable.category.name",
      path: "EvidenceVariable.category.name",
      short: "Description of the grouping",
      definition: "A human-readable title or representation of the grouping.",
      min: 0,
      max: "1",
      base: { path: "EvidenceVariable.category.name", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.category.name",
    parentDataPath: "root.category[0]",
    basePath: "root.name",
    baseId: "EvidenceVariable.category.name",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "EvidenceVariable",
      path: "EvidenceVariable",
      short: "A definition of an exposure, outcome, or other variable",
      definition:
        "The EvidenceVariable resource describes an element that knowledge (Evidence) is about.",
      comment:
        "The EvidenceVariable may be an exposure variable (intervention, condition, or state), a measured variable (outcome or observed parameter), or other variable (such as confounding factor).",
      min: 0,
      max: "*",
      base: { path: "EvidenceVariable", min: 0, max: "*" },
      constraint: [
        {
          key: "cnl-0",
          severity: "warning",
          human:
            "Name should be usable as an identifier for the module by machine processing applications such as code generation",
          expression:
            "name.exists() implies name.matches('[A-Z]([A-Za-z0-9_]){0,254}')",
          xpath:
            "not(exists(f:name/@value)) or matches(f:name/@value, '[A-Z]([A-Za-z0-9_]){0,254}')",
          source: "http://hl7.org/fhir/StructureDefinition/EvidenceVariable",
        },
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "workflow", map: "Definition" },
        { identity: "w5", map: "clinical.general" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "EvidenceVariable",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
