const data = [
  {
    element: {
      id: "ImagingStudy.meta",
      path: "ImagingStudy.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "ImagingStudy.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.implicitRules",
      path: "ImagingStudy.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "ImagingStudy.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.language",
      path: "ImagingStudy.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "ImagingStudy.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "ImagingStudy.contained",
      path: "ImagingStudy.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source: "http://hl7.org/fhir/StructureDefinition/ImagingStudy",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "ImagingStudy.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.status",
      path: "ImagingStudy.status",
      short: "registered | available | cancelled | entered-in-error | unknown",
      definition: "The current state of the ImagingStudy.",
      comment:
        'Unknown does not represent "other" - one of the defined statuses must apply.  Unknown is used when the authoring system is not sure what the current status is.',
      min: 1,
      max: "1",
      base: { path: "ImagingStudy.status", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid",
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ImagingStudyStatus",
          },
        ],
        strength: "required",
        description: "The status of the ImagingStudy.",
        valueSet: "http://hl7.org/fhir/ValueSet/imagingstudy-status|4.3.0",
      },
      mapping: [
        { identity: "workflow", map: "Event.status" },
        { identity: "w5", map: "FiveWs.status" },
        { identity: "v2", map: "Varies by domain" },
        { identity: "rim", map: ".status" },
      ],
    },
    dataPath: "root.status",
    parentDataPath: "root",
    basePath: "root.status",
    baseId: "ImagingStudy.status",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/imagingstudy-status",
        code: "registered",
        display: "Registered",
      },
      {
        system: "http://hl7.org/fhir/imagingstudy-status",
        code: "available",
        display: "Available",
      },
      {
        system: "http://hl7.org/fhir/imagingstudy-status",
        code: "cancelled",
        display: "Cancelled",
      },
      {
        system: "http://hl7.org/fhir/imagingstudy-status",
        code: "entered-in-error",
        display: "Entered in Error",
      },
      {
        system: "http://hl7.org/fhir/imagingstudy-status",
        code: "unknown",
        display: "Unknown",
      },
    ],
  },
  {
    element: {
      id: "ImagingStudy.subject",
      extension: [
        {
          url: "http://hl7.org/fhir/StructureDefinition/structuredefinition-display-hint",
          valueString:
            "dicom=http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.2.2.html",
        },
      ],
      path: "ImagingStudy.subject",
      short: "Who or what is the subject of the study",
      definition: "The subject, typically a patient, of the imaging study.",
      comment:
        "QA phantoms can be recorded with a Device; multiple subjects (such as mice) can be recorded with a Group.",
      min: 1,
      max: "1",
      base: { path: "ImagingStudy.subject", min: 1, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Patient",
            "http://hl7.org/fhir/StructureDefinition/Device",
            "http://hl7.org/fhir/StructureDefinition/Group",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.subject" },
        { identity: "w5", map: "FiveWs.subject[x]" },
        { identity: "rim", map: ".participation[typeCode=SBJ].role" },
        { identity: "dicom", map: "(0010/*)" },
        { identity: "w5", map: "FiveWs.subject" },
      ],
    },
    dataPath: "root.subject",
    parentDataPath: "root",
    basePath: "root.subject",
    baseId: "ImagingStudy.subject",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.started",
      extension: [
        {
          url: "http://hl7.org/fhir/StructureDefinition/structuredefinition-display-hint",
          valueString:
            "dicom=http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.2.html#sect_C.7.2.1",
        },
      ],
      path: "ImagingStudy.started",
      short: "When the study was started",
      definition: "Date and time the study started.",
      alias: ["StudyDate", "StudyTime"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.started", min: 0, max: "1" },
      type: [{ code: "dateTime" }],
      example: [
        { label: "General", valueDateTime: "2011-01-01T11:01:20+03:00" },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.occurrence[x]" },
        { identity: "w5", map: "FiveWs.init" },
        { identity: "rim", map: ".effectiveTime" },
        { identity: "dicom", map: "(0008,0020)+(0008,0030)" },
      ],
    },
    dataPath: "root.started",
    parentDataPath: "root",
    basePath: "root.started",
    baseId: "ImagingStudy.started",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.referrer",
      path: "ImagingStudy.referrer",
      short: "Referring physician",
      definition: "The requesting/referring physician.",
      alias: ["ReferringPhysiciansName"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.referrer", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Practitioner",
            "http://hl7.org/fhir/StructureDefinition/PractitionerRole",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "w5", map: "FiveWs.cause" },
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=FLFS].target[classCode=DGIMG, moodCode=RQO].participation[typeCode=AUT].role",
        },
        { identity: "dicom", map: "(0008,0090)+(0008,0096)" },
      ],
    },
    dataPath: "root.referrer",
    parentDataPath: "root",
    basePath: "root.referrer",
    baseId: "ImagingStudy.referrer",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.endpoint",
      path: "ImagingStudy.endpoint",
      short: "Study access endpoint",
      definition:
        "The network service providing access (e.g., query, view, or retrieval) for the study. See implementation notes for information about using DICOM endpoints. A study-level endpoint applies to each series in the study, unless overridden by a series-level endpoint with the same Endpoint.connectionType.",
      comment:
        "Typical endpoint types include DICOM WADO-RS, which is used to retrieve DICOM instances in native or rendered (e.g., JPG, PNG), formats using a RESTful API; DICOM WADO-URI, which can similarly retrieve native or rendered instances, except using an HTTP query-based approach; DICOM QIDO-RS, which allows RESTful query for DICOM information without retrieving the actual instances; or IHE Invoke Image Display (IID), which provides standard invocation of an imaging web viewer.",
      requirements:
        "Access methods for viewing (e.g., IHE’s IID profile) or retrieving (e.g., DICOM’s WADO-URI and WADO-RS) the study or the study’s series or instances. The study-level baseLocation applies to each series in the study, unless overridden in series by a series-level baseLocation of the same type.",
      min: 0,
      max: "*",
      base: { path: "ImagingStudy.endpoint", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Endpoint"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "rim", map: "Not supported" }],
    },
    dataPath: "root.endpoint[0]",
    parentDataPath: "root",
    basePath: "root.endpoint",
    baseId: "ImagingStudy.endpoint",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.numberOfSeries",
      path: "ImagingStudy.numberOfSeries",
      short: "Number of Study Related Series",
      definition:
        "Number of Series in the Study. This value given may be larger than the number of series elements this Resource contains due to resource availability, security, or other factors. This element should be present if any series elements are present.",
      alias: ["NumberOfStudyRelatedSeries"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.numberOfSeries", min: 0, max: "1" },
      type: [{ code: "unsignedInt" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP, subsetCode=SUMM].target[classCode=OBSSER, moodCode=EVN].repeatNumber",
        },
        { identity: "dicom", map: "(0020,1206)" },
      ],
    },
    dataPath: "root.numberOfSeries",
    parentDataPath: "root",
    basePath: "root.numberOfSeries",
    baseId: "ImagingStudy.numberOfSeries",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.numberOfInstances",
      path: "ImagingStudy.numberOfInstances",
      short: "Number of Study Related Instances",
      definition:
        "Number of SOP Instances in Study. This value given may be larger than the number of instance elements this resource contains due to resource availability, security, or other factors. This element should be present if any instance elements are present.",
      alias: ["NumberOfStudyRelatedInstances"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.numberOfInstances", min: 0, max: "1" },
      type: [{ code: "unsignedInt" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP, subsetCode=SUMM].target[classCode=DGIMG, moodCode=EVN].repeatNumber",
        },
        { identity: "dicom", map: "(0020,1208)" },
      ],
    },
    dataPath: "root.numberOfInstances",
    parentDataPath: "root",
    basePath: "root.numberOfInstances",
    baseId: "ImagingStudy.numberOfInstances",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.procedureCode",
      path: "ImagingStudy.procedureCode",
      short: "The performed procedure code",
      definition: "The code for the performed procedure type.",
      alias: ["ProcedureCodeSequence"],
      min: 0,
      max: "*",
      base: { path: "ImagingStudy.procedureCode", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ImagingProcedureCode",
          },
        ],
        strength: "extensible",
        description: "Use of RadLex is preferred",
        valueSet: "http://www.rsna.org/RadLex_Playbook.aspx",
      },
      mapping: [
        { identity: "workflow", map: "Event.code" },
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP].target[classCode=PROC, moodCode=EVN]",
        },
        { identity: "dicom", map: "(0008,1032)" },
      ],
    },
    dataPath: "root.procedureCode[0]",
    parentDataPath: "root",
    basePath: "root.procedureCode",
    baseId: "ImagingStudy.procedureCode",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.reasonCode",
      path: "ImagingStudy.reasonCode",
      short: "Why the study was requested",
      definition:
        "Description of clinical condition indicating why the ImagingStudy was requested.",
      min: 0,
      max: "*",
      base: { path: "ImagingStudy.reasonCode", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ImagingReason",
          },
        ],
        strength: "example",
        description: "The reason for the study.",
        valueSet: "http://hl7.org/fhir/ValueSet/procedure-reason",
      },
      mapping: [
        { identity: "workflow", map: "Event.reasonCode" },
        { identity: "w5", map: "FiveWs.why[x]" },
        { identity: "rim", map: ".reasonCode" },
        { identity: "dicom", map: "(0040,1002)" },
      ],
    },
    dataPath: "root.reasonCode[0]",
    parentDataPath: "root",
    basePath: "root.reasonCode",
    baseId: "ImagingStudy.reasonCode",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.note",
      path: "ImagingStudy.note",
      short: "User-defined comments",
      definition:
        "Per the recommended DICOM mapping, this element is derived from the Study Description attribute (0008,1030). Observations or findings about the imaging study should be recorded in another resource, e.g. Observation, and not in this element.",
      min: 0,
      max: "*",
      base: { path: "ImagingStudy.note", min: 0, max: "*" },
      type: [{ code: "Annotation" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.note" },
        { identity: "rim", map: "unknown" },
      ],
    },
    dataPath: "root.note[0]",
    parentDataPath: "root",
    basePath: "root.note",
    baseId: "ImagingStudy.note",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.description",
      path: "ImagingStudy.description",
      short: "Institution-generated description",
      definition:
        "The Imaging Manager description of the study. Institution-generated description or classification of the Study (component) performed.",
      alias: ["StudyDescription"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.description", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "rim", map: ".text" },
        { identity: "dicom", map: "(0008,1030)" },
      ],
    },
    dataPath: "root.description",
    parentDataPath: "root",
    basePath: "root.description",
    baseId: "ImagingStudy.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series",
      path: "ImagingStudy.series",
      short: "Each study has one or more series of instances",
      definition:
        "Each study has one or more series of images or other content.",
      min: 0,
      max: "*",
      base: { path: "ImagingStudy.series", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP].target[classCode=OBSSER, moodCode=EVN]",
        },
      ],
    },
    dataPath: "root.series[0]",
    parentDataPath: "root",
    basePath: "root.series",
    baseId: "ImagingStudy.series",
    isPrimitive: false,
    childPaths: [
      "root.series.uid",
      "root.series.number",
      "root.series.modality",
      "root.series.description",
      "root.series.numberOfInstances",
      "root.series.endpoint[0]",
      "root.series.bodySite",
      "root.series.laterality",
      "root.series.specimen[0]",
      "root.series.started",
      "root.series.performer[0]",
      "root.series.instance[0]",
    ],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.uid",
      path: "ImagingStudy.series.uid",
      short: "DICOM Series Instance UID for the series",
      definition: "The DICOM Series Instance UID for the series.",
      comment:
        "See [DICOM PS3.3 C.7.3](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.3.html).",
      requirements: "DICOM Series Instance UID.",
      alias: ["SeriesInstanceUID"],
      min: 1,
      max: "1",
      base: { path: "ImagingStudy.series.uid", min: 1, max: "1" },
      type: [{ code: "id" }],
      example: [
        {
          label: "General",
          valueId: "2.16.124.113543.6003.2588828330.45298.17418.2723805630",
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "rim", map: ".id" },
        { identity: "dicom", map: "(0020,000E)" },
      ],
    },
    dataPath: "root.series.uid",
    parentDataPath: "root.series[0]",
    basePath: "root.uid",
    baseId: "ImagingStudy.series.uid",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.number",
      path: "ImagingStudy.series.number",
      short: "Numeric identifier of this series",
      definition: "The numeric identifier of this series in the study.",
      alias: ["SeriesNumber"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.series.number", min: 0, max: "1" },
      type: [{ code: "unsignedInt" }],
      example: [{ label: "General", valueUnsignedInt: 3 }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        {
          identity: "rim",
          map: ".inboundRelationship[type=COMP, source[classCode=COMPOSITION, moodCode=EVN]].sequenceNumber",
        },
        { identity: "dicom", map: "(0020,0011)" },
      ],
    },
    dataPath: "root.series.number",
    parentDataPath: "root.series[0]",
    basePath: "root.number",
    baseId: "ImagingStudy.series.number",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.description",
      path: "ImagingStudy.series.description",
      short: "A short human readable summary of the series",
      definition: "A description of the series.",
      alias: ["SeriesDescription"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.series.description", min: 0, max: "1" },
      type: [{ code: "string" }],
      example: [{ label: "General", valueString: "CT Surview 180" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "rim", map: ".text" },
        { identity: "dicom", map: "(0008,103E)" },
      ],
    },
    dataPath: "root.series.description",
    parentDataPath: "root.series[0]",
    basePath: "root.description",
    baseId: "ImagingStudy.series.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.numberOfInstances",
      path: "ImagingStudy.series.numberOfInstances",
      short: "Number of Series Related Instances",
      definition:
        "Number of SOP Instances in the Study. The value given may be larger than the number of instance elements this resource contains due to resource availability, security, or other factors. This element should be present if any instance elements are present.",
      alias: ["NumberOfSeriesRelatedInstances"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.series.numberOfInstances", min: 0, max: "1" },
      type: [{ code: "unsignedInt" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP, subsetCode=SUMM].target[classCode=DGIMG, moodCode=EVN].repeatNumber",
        },
        { identity: "dicom", map: "(0020,1209)" },
      ],
    },
    dataPath: "root.series.numberOfInstances",
    parentDataPath: "root.series[0]",
    basePath: "root.numberOfInstances",
    baseId: "ImagingStudy.series.numberOfInstances",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.bodySite",
      path: "ImagingStudy.series.bodySite",
      short: "Body part examined",
      definition:
        "The anatomic structures examined. See DICOM Part 16 Annex L (http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_L.html) for DICOM to SNOMED-CT mappings. The bodySite may indicate the laterality of body part imaged; if so, it shall be consistent with any content of ImagingStudy.series.laterality.",
      alias: ["BodyPartExamined"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.series.bodySite", min: 0, max: "1" },
      type: [{ code: "Coding" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "BodySite",
          },
        ],
        strength: "example",
        description: "SNOMED CT Body site concepts",
        valueSet: "http://hl7.org/fhir/ValueSet/body-site",
      },
      mapping: [
        { identity: "rim", map: ".targetSiteCode" },
        { identity: "dicom", map: "(0018,0015)" },
      ],
    },
    dataPath: "root.series.bodySite",
    parentDataPath: "root.series[0]",
    basePath: "root.bodySite",
    baseId: "ImagingStudy.series.bodySite",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.laterality",
      path: "ImagingStudy.series.laterality",
      short: "Body part laterality",
      definition:
        "The laterality of the (possibly paired) anatomic structures examined. E.g., the left knee, both lungs, or unpaired abdomen. If present, shall be consistent with any laterality information indicated in ImagingStudy.series.bodySite.",
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.series.laterality", min: 0, max: "1" },
      type: [{ code: "Coding" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Laterality",
          },
        ],
        strength: "example",
        description:
          "Codes describing body site laterality (left, right, etc.).",
        valueSet: "http://hl7.org/fhir/ValueSet/bodysite-laterality",
      },
      mapping: [
        { identity: "rim", map: ".targetSiteCode" },
        { identity: "dicom", map: "(0020,0060)" },
      ],
    },
    dataPath: "root.series.laterality",
    parentDataPath: "root.series[0]",
    basePath: "root.laterality",
    baseId: "ImagingStudy.series.laterality",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "419161000", display: "Unilateral left" },
      { code: "419465000", display: "Unilateral right" },
      { code: "51440002", display: "Bilateral" },
    ],
  },
  {
    element: {
      id: "ImagingStudy.series.started",
      path: "ImagingStudy.series.started",
      short: "When the series started",
      definition: "The date and time the series was started.",
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.series.started", min: 0, max: "1" },
      type: [{ code: "dateTime" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "rim", map: ".effectiveTime" },
        { identity: "dicom", map: "(0008,0021) + (0008,0031)" },
      ],
    },
    dataPath: "root.series.started",
    parentDataPath: "root.series[0]",
    basePath: "root.started",
    baseId: "ImagingStudy.series.started",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.performer",
      path: "ImagingStudy.series.performer",
      short: "Who performed the series",
      definition:
        "Indicates who or what performed the series and how they were involved.",
      comment:
        "If the person who performed the series is not known, their Organization may be recorded. A patient, or related person, may be the performer, e.g. for patient-captured images.",
      requirements:
        "The performer is recorded at the series level, since each series in a study may be performed by a different performer, at different times, and using different devices. A series may be performed by multiple performers.",
      alias: ["PerformingPhysicianName", "OperatorName"],
      min: 0,
      max: "*",
      base: { path: "ImagingStudy.series.performer", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.performer" },
        { identity: "rim", map: ".participation[typeCode=PRF].role" },
        {
          identity: "dicom",
          map: "(0008, 1050) | (0008, 1052) | (0008, 1070) | (0008, 1072)",
        },
      ],
    },
    dataPath: "root.series.performer[0]",
    parentDataPath: "root.series[0]",
    basePath: "root.performer",
    baseId: "ImagingStudy.series.performer",
    isPrimitive: false,
    childPaths: [
      "root.series.performer.function",
      "root.series.performer.actor",
    ],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.performer.function",
      path: "ImagingStudy.series.performer.function",
      short: "Type of performance",
      definition:
        "Distinguishes the type of involvement of the performer in the series.",
      requirements:
        "Allows disambiguation of the types of involvement of different performers.",
      min: 0,
      max: "1",
      base: {
        path: "ImagingStudy.series.performer.function",
        min: 0,
        max: "1",
      },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "EventPerformerFunction",
          },
        ],
        strength: "extensible",
        description: "The type of involvement of the performer.",
        valueSet: "http://hl7.org/fhir/ValueSet/series-performer-function",
      },
      mapping: [{ identity: "rim", map: ".participation[typeCode=PRF].role" }],
    },
    dataPath: "root.series.performer.function",
    parentDataPath: "root.series.performer[0]",
    basePath: "root.function",
    baseId: "ImagingStudy.series.performer.function",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "CON", display: "consultant" },
      { code: "VRF", display: "verifier" },
      { code: "PRF", display: "performer" },
      { code: "SPRF", display: "secondary performer" },
      { code: "REF", display: "referrer" },
    ],
  },
  {
    element: {
      id: "ImagingStudy.series.instance",
      path: "ImagingStudy.series.instance",
      short: "A single SOP instance from the series",
      definition:
        "A single SOP instance within the series, e.g. an image, or presentation state.",
      min: 0,
      max: "*",
      base: { path: "ImagingStudy.series.instance", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP].target[classCode=DGIMG, moodCode=EVN]",
        },
      ],
    },
    dataPath: "root.series.instance[0]",
    parentDataPath: "root.series[0]",
    basePath: "root.instance",
    baseId: "ImagingStudy.series.instance",
    isPrimitive: false,
    childPaths: [
      "root.series.instance.uid",
      "root.series.instance.sopClass",
      "root.series.instance.number",
      "root.series.instance.title",
    ],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.instance.uid",
      path: "ImagingStudy.series.instance.uid",
      short: "DICOM SOP Instance UID",
      definition:
        "The DICOM SOP Instance UID for this image or other DICOM content.",
      comment:
        "See  [DICOM PS3.3 C.12.1](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.12.html#sect_C.12.1).",
      requirements: "DICOM SOP Instance UID.",
      alias: ["SOPInstanceUID"],
      min: 1,
      max: "1",
      base: { path: "ImagingStudy.series.instance.uid", min: 1, max: "1" },
      type: [{ code: "id" }],
      example: [
        {
          label: "General",
          valueId: "2.16.124.113543.6003.189642796.63084.16748.2599092903",
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: ".id" },
        { identity: "dicom", map: "(0008,0018)" },
      ],
    },
    dataPath: "root.series.instance.uid",
    parentDataPath: "root.series.instance[0]",
    basePath: "root.uid",
    baseId: "ImagingStudy.series.instance.uid",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.instance.number",
      path: "ImagingStudy.series.instance.number",
      short: "The number of this instance in the series",
      definition: "The number of instance in the series.",
      alias: ["InstanceNumber"],
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.series.instance.number", min: 0, max: "1" },
      type: [{ code: "unsignedInt" }],
      example: [{ label: "General", valueUnsignedInt: 1 }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".inboundRelationship[typeCode=COMP, source[classCode=OBSSER, moodCode=EVN]].sequenceNumber",
        },
        { identity: "dicom", map: "(0020,0013)" },
      ],
    },
    dataPath: "root.series.instance.number",
    parentDataPath: "root.series.instance[0]",
    basePath: "root.number",
    baseId: "ImagingStudy.series.instance.number",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy.series.instance.title",
      path: "ImagingStudy.series.instance.title",
      short: "Description of instance",
      definition: "The description of the instance.",
      comment:
        "Particularly for post-acquisition analytic objects, such as SR, presentation states, value mapping, etc.",
      min: 0,
      max: "1",
      base: { path: "ImagingStudy.series.instance.title", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: ".title" },
        {
          identity: "dicom",
          map: "(0008,0008) | (0007,0080) | (0040,A043) + (0008,0104) | (0042,0010)",
        },
      ],
    },
    dataPath: "root.series.instance.title",
    parentDataPath: "root.series.instance[0]",
    basePath: "root.title",
    baseId: "ImagingStudy.series.instance.title",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "ImagingStudy",
      path: "ImagingStudy",
      short:
        "A set of images produced in single study (one or more series of references images)",
      definition:
        "Representation of the content produced in a DICOM imaging study. A study comprises a set of series, each of which includes a set of Service-Object Pair Instances (SOP Instances - images or other data) acquired or produced in a common context.  A series is of only one modality (e.g. X-ray, CT, MR, ultrasound), but a study may have multiple series of different modalities.",
      min: 0,
      max: "*",
      base: { path: "ImagingStudy", min: 0, max: "*" },
      constraint: [
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "workflow", map: "Event" },
        { identity: "rim", map: "Act[classCode=COMPOSITION, moodCode=EVN]" },
        {
          identity: "dicom",
          map: "Reference IHE radiology TF vol 2 table 4.14-1",
        },
        { identity: "w5", map: "clinical.diagnostics" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "ImagingStudy",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
