const data = [
  {
    element: {
      id: "MessageHeader.meta",
      path: "MessageHeader.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "MessageHeader.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.implicitRules",
      path: "MessageHeader.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "MessageHeader.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.language",
      path: "MessageHeader.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "MessageHeader.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "MessageHeader.contained",
      path: "MessageHeader.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source: "http://hl7.org/fhir/StructureDefinition/MessageHeader",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "MessageHeader.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.destination",
      extension: [
        {
          url: "http://hl7.org/fhir/StructureDefinition/structuredefinition-explicit-type-name",
          valueString: "MessageDestination",
        },
      ],
      path: "MessageHeader.destination",
      short: "Message destination application(s)",
      definition:
        "The destination application which the message is intended for.",
      comment:
        "There SHOULD be at least one destination, but in some circumstances, the source system is unaware of any particular destination system.",
      requirements:
        'Indicates where message is to be sent for routing purposes.  Allows verification of "am I the intended recipient".',
      min: 0,
      max: "*",
      base: { path: "MessageHeader.destination", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "w5", map: "FiveWs.subject[x]" },
        { identity: "rim", map: './communicationFunction[typeCode="RCV"]' },
        { identity: "w5", map: "FiveWs.subject" },
      ],
    },
    dataPath: "root.destination[0]",
    parentDataPath: "root",
    basePath: "root.destination",
    baseId: "MessageHeader.destination",
    isPrimitive: false,
    childPaths: [
      "root.destination.name",
      "root.destination.target",
      "root.destination.endpoint",
      "root.destination.receiver",
    ],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.destination.name",
      path: "MessageHeader.destination.name",
      short: "Name of system",
      definition: "Human-readable name for the target system.",
      requirements:
        "May be used for routing of response and/or to support audit.",
      min: 0,
      max: "1",
      base: { path: "MessageHeader.destination.name", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "v2", map: "MSH-5" },
        {
          identity: "rim",
          map: 'unique(./entity[determinerCode="INST" and (classCode=("DEV", "PSN", "ORG"]/name[type=\'ST\' and isNormalDatatype()])',
        },
      ],
    },
    dataPath: "root.destination.name",
    parentDataPath: "root.destination[0]",
    basePath: "root.name",
    baseId: "MessageHeader.destination.name",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.destination.endpoint",
      path: "MessageHeader.destination.endpoint",
      short: "Actual destination address or id",
      definition: "Indicates where the message should be routed to.",
      comment:
        "The id may be a non-resolvable URI for systems that do not use standard network-based addresses.",
      requirements: "Identifies where to route the message.",
      min: 1,
      max: "1",
      base: { path: "MessageHeader.destination.endpoint", min: 1, max: "1" },
      type: [{ code: "url" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "v2", map: "MSH-25 (or MSH-6)" },
        { identity: "rim", map: "./telecom" },
      ],
    },
    dataPath: "root.destination.endpoint",
    parentDataPath: "root.destination[0]",
    basePath: "root.endpoint",
    baseId: "MessageHeader.destination.endpoint",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.sender",
      path: "MessageHeader.sender",
      short: "Real world sender of the message",
      definition:
        "Identifies the sending system to allow the use of a trust relationship.",
      comment:
        "Use case is for where a (trusted) sending system is responsible for multiple organizations, and therefore cannot differentiate based on source endpoint / authentication alone.",
      requirements: "Allows routing beyond just the application level.",
      min: 0,
      max: "1",
      base: { path: "MessageHeader.sender", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Practitioner",
            "http://hl7.org/fhir/StructureDefinition/PractitionerRole",
            "http://hl7.org/fhir/StructureDefinition/Organization",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "w5", map: "FiveWs.subject[x]" },
        { identity: "v2", map: "PRT-5:PRT-4='WAYR' / PRT-8:PRT-4='WAYR'" },
        {
          identity: "rim",
          map: "Not directly supported.  Could be shared using attentionLine.value with an appropriate keyWordText",
        },
        { identity: "w5", map: "FiveWs.subject" },
      ],
    },
    dataPath: "root.sender",
    parentDataPath: "root",
    basePath: "root.sender",
    baseId: "MessageHeader.sender",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.author",
      path: "MessageHeader.author",
      short: "The source of the decision",
      definition:
        "The logical author of the message - the person or device that decided the described event should happen. When there is more than one candidate, pick the most proximal to the MessageHeader. Can provide other authors in extensions.",
      comment: "Usually only for the request but can be used in a response.",
      requirements:
        "Need to know for audit/traceback requirements and possibly for authorization.",
      min: 0,
      max: "1",
      base: { path: "MessageHeader.author", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Practitioner",
            "http://hl7.org/fhir/StructureDefinition/PractitionerRole",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "w5", map: "FiveWs.author" },
        {
          identity: "v2",
          map: "ORC-19 / PRT-5:PRT-4='AUT' / ROL where ROL.3 is IP or ORC.12",
        },
        {
          identity: "rim",
          map: 'unique(./controlAct[classCode="CACT" and classCode="EVN" and isNormalAct()]/participation[isHighest(priorityCode) and typeCode="AUT" and isNormalParticipation]/role[classCode="ASSIGNED" and isNormalRole()]/player[isNormalEntity() and classCode=("DEV", "PSN") and determinerCode="INST"])',
        },
      ],
    },
    dataPath: "root.author",
    parentDataPath: "root",
    basePath: "root.author",
    baseId: "MessageHeader.author",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.source",
      extension: [
        {
          url: "http://hl7.org/fhir/StructureDefinition/structuredefinition-explicit-type-name",
          valueString: "MessageSource",
        },
      ],
      path: "MessageHeader.source",
      short: "Message source application",
      definition: "The source application from which this message originated.",
      requirements: "Allows replies, supports audit.",
      min: 1,
      max: "1",
      base: { path: "MessageHeader.source", min: 1, max: "1" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "w5", map: "FiveWs.actor" },
        {
          identity: "rim",
          map: 'unique(./communicationFunction[typeCode="SND"])',
        },
      ],
    },
    dataPath: "root.source",
    parentDataPath: "root",
    basePath: "root.source",
    baseId: "MessageHeader.source",
    isPrimitive: false,
    childPaths: [
      "root.source.name",
      "root.source.software",
      "root.source.version",
      "root.source.contact",
      "root.source.endpoint",
    ],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.source.name",
      path: "MessageHeader.source.name",
      short: "Name of system",
      definition: "Human-readable name for the source system.",
      requirements: "May be used to support audit.",
      min: 0,
      max: "1",
      base: { path: "MessageHeader.source.name", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "v2", map: "MSH-3" },
        {
          identity: "rim",
          map: 'unique(./entity[determinerCode="INST" and classCode="DEV"]/name[type=\'ST\' and isNormalDatatype()])',
        },
      ],
    },
    dataPath: "root.source.name",
    parentDataPath: "root.source",
    basePath: "root.name",
    baseId: "MessageHeader.source.name",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.source.software",
      path: "MessageHeader.source.software",
      short: "Name of software running the system",
      definition:
        "May include configuration or other information useful in debugging.",
      requirements: "Supports audit and possibly interface engine behavior.",
      min: 0,
      max: "1",
      base: { path: "MessageHeader.source.software", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "v2", map: "SFT-3 ( +SFT-1)" },
        {
          identity: "rim",
          map: 'unique(./entity[determinerCode="INST" and classCode="DEV"]/softwareName[isNormalDatatype()])',
        },
      ],
    },
    dataPath: "root.source.software",
    parentDataPath: "root.source",
    basePath: "root.software",
    baseId: "MessageHeader.source.software",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.source.version",
      path: "MessageHeader.source.version",
      short: "Version of software running",
      definition:
        "Can convey versions of multiple systems in situations where a message passes through multiple hands.",
      requirements: "Supports audit and possibly interface engine behavior.",
      min: 0,
      max: "1",
      base: { path: "MessageHeader.source.version", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "v2", map: "SFT-2" },
        { identity: "rim", map: "(Not supported)" },
      ],
    },
    dataPath: "root.source.version",
    parentDataPath: "root.source",
    basePath: "root.version",
    baseId: "MessageHeader.source.version",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.source.endpoint",
      path: "MessageHeader.source.endpoint",
      short: "Actual message source address or id",
      definition: "Identifies the routing target to send acknowledgements to.",
      comment:
        "The id may be a non-resolvable URI for systems that do not use standard network-based addresses.",
      requirements:
        "Identifies where to send responses, may influence security permissions.",
      min: 1,
      max: "1",
      base: { path: "MessageHeader.source.endpoint", min: 1, max: "1" },
      type: [{ code: "url" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "v2", map: "MSH-24" },
        { identity: "rim", map: "./telecom[isNormalDatatype()]" },
      ],
    },
    dataPath: "root.source.endpoint",
    parentDataPath: "root.source",
    basePath: "root.endpoint",
    baseId: "MessageHeader.source.endpoint",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.reason",
      path: "MessageHeader.reason",
      short: "Cause of event",
      definition:
        "Coded indication of the cause for the event - indicates  a reason for the occurrence of the event that is a focus of this message.",
      requirements:
        "Need to be able to track why resources are being changed and report in the audit log/history of the resource.  May affect authorization.",
      min: 0,
      max: "1",
      base: { path: "MessageHeader.reason", min: 0, max: "1" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "EventReason",
          },
        ],
        strength: "example",
        description: "Reason for event occurrence.",
        valueSet: "http://hl7.org/fhir/ValueSet/message-reason-encounter",
      },
      mapping: [
        { identity: "w5", map: "FiveWs.why[x]" },
        {
          identity: "v2",
          map: "EVN.4 / ORC.16 / OBR-31-reason for study / BPO-13-BP indication for use / RXO-20-indication / RXE-27-give indication / RXD-21-indication / RXG-22-indication / RXA-19-indication",
        },
        {
          identity: "rim",
          map: 'unique(./controlAct[classCode="CACT" and classCode="EVN" and isNormalAct()]/reasonCode[isNormalDatatype()])',
        },
      ],
    },
    dataPath: "root.reason",
    parentDataPath: "root",
    basePath: "root.reason",
    baseId: "MessageHeader.reason",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system:
          "http://terminology.hl7.org/CodeSystem/message-reasons-encounter",
        code: "admit",
        display: "Admit",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/message-reasons-encounter",
        code: "discharge",
        display: "Discharge",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/message-reasons-encounter",
        code: "absent",
        display: "Absent",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/message-reasons-encounter",
        code: "return",
        display: "Returned",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/message-reasons-encounter",
        code: "moved",
        display: "Moved",
      },
      {
        system:
          "http://terminology.hl7.org/CodeSystem/message-reasons-encounter",
        code: "edit",
        display: "Edit",
      },
    ],
  },
  {
    element: {
      id: "MessageHeader.response",
      path: "MessageHeader.response",
      short: "If this is a reply to prior message",
      definition:
        "Information about the message that this message is a response to.  Only present if this message is a response.",
      min: 0,
      max: "1",
      base: { path: "MessageHeader.response", min: 0, max: "1" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "v2", map: "MSA" },
        { identity: "rim", map: "./conveyedAcknowledgement" },
      ],
    },
    dataPath: "root.response",
    parentDataPath: "root",
    basePath: "root.response",
    baseId: "MessageHeader.response",
    isPrimitive: false,
    childPaths: [
      "root.response.identifier",
      "root.response.code",
      "root.response.details",
    ],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.response.identifier",
      path: "MessageHeader.response.identifier",
      short: "Id of original message",
      definition:
        "The MessageHeader.id of the message to which this message is a response.",
      requirements:
        "Allows receiver to know what message is being responded to.",
      min: 1,
      max: "1",
      base: { path: "MessageHeader.response.identifier", min: 1, max: "1" },
      type: [{ code: "id" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "v2", map: "MSA-2" },
        { identity: "rim", map: "./acknowledges.id[isNormalDatatype()]" },
      ],
    },
    dataPath: "root.response.identifier",
    parentDataPath: "root.response",
    basePath: "root.identifier",
    baseId: "MessageHeader.response.identifier",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.response.code",
      path: "MessageHeader.response.code",
      short: "ok | transient-error | fatal-error",
      definition:
        "Code that identifies the type of response to the message - whether it was successful or not, and whether it should be resent or not.",
      comment:
        "This is a generic response to the request message. Specific data for the response will be found in MessageHeader.focus.",
      requirements:
        "Allows the sender of the acknowledge message to know if the request was successful or if action is needed.",
      min: 1,
      max: "1",
      base: { path: "MessageHeader.response.code", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ResponseType",
          },
        ],
        strength: "required",
        description: "The kind of response to a message.",
        valueSet: "http://hl7.org/fhir/ValueSet/response-code|4.3.0",
      },
      mapping: [
        { identity: "v2", map: "MSA-1" },
        { identity: "rim", map: "./typeCode[isNormalDatatype()]" },
      ],
    },
    dataPath: "root.response.code",
    parentDataPath: "root.response",
    basePath: "root.code",
    baseId: "MessageHeader.response.code",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/response-code",
        code: "ok",
        display: "OK",
      },
      {
        system: "http://hl7.org/fhir/response-code",
        code: "transient-error",
        display: "Transient Error",
      },
      {
        system: "http://hl7.org/fhir/response-code",
        code: "fatal-error",
        display: "Fatal Error",
      },
    ],
  },
  {
    element: {
      id: "MessageHeader.focus",
      path: "MessageHeader.focus",
      short: "The actual content of the message",
      definition:
        "The actual data of the message - a reference to the root/focus class of the event.",
      comment:
        "The data is defined where the transaction type is defined. The transaction data is always included in the bundle that is the full message.  Only the root resource is specified.  The resources it references should be contained in the bundle but are not also listed here.  Multiple repetitions are allowed to cater for merges and other situations with multiple focal targets.",
      requirements:
        "Every message event is about actual data, a single resource, that is identified in the definition of the event, and perhaps some or all linked resources.",
      min: 0,
      max: "*",
      base: { path: "MessageHeader.focus", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Resource"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        {
          identity: "rim",
          map: 'unique(./controlAct[classCode="CACT" and classCode="EVN" and isNormalAct()]/participation[typeCode="SUBJ" and isNormalParticipation]/role or ./controlAct[classCode="CACT" and classCode="EVN" and isNormalAct()]/outboundRelationship[typeCode="SBJ" and isNormalActRelatoinship]/target)',
        },
      ],
    },
    dataPath: "root.focus[0]",
    parentDataPath: "root",
    basePath: "root.focus",
    baseId: "MessageHeader.focus",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader.definition",
      path: "MessageHeader.definition",
      short: "Link to the definition for this message",
      definition: "Permanent link to the MessageDefinition for this message.",
      requirements:
        "Allows sender to define the expected contents of the message.",
      min: 0,
      max: "1",
      base: { path: "MessageHeader.definition", min: 0, max: "1" },
      type: [
        {
          code: "canonical",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/MessageDefinition",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "rim", map: "Not directly supported." }],
    },
    dataPath: "root.definition",
    parentDataPath: "root",
    basePath: "root.definition",
    baseId: "MessageHeader.definition",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "MessageHeader",
      path: "MessageHeader",
      short:
        "A resource that describes a message that is exchanged between systems",
      definition:
        "The header for a message exchange that is either requesting or responding to an action.  The reference(s) that are the subject of the action as well as other information related to the action are typically transmitted in a bundle in which the MessageHeader resource instance is the first resource in the bundle.",
      min: 0,
      max: "*",
      base: { path: "MessageHeader", min: 0, max: "*" },
      constraint: [
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "v2", map: "MSH / MSA / ERR" },
        { identity: "rim", map: "Message" },
        { identity: "w5", map: "infrastructure.exchange" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "MessageHeader",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
