const data = [
  {
    element: {
      id: "OrganizationAffiliation.meta",
      path: "OrganizationAffiliation.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "OrganizationAffiliation.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "OrganizationAffiliation.implicitRules",
      path: "OrganizationAffiliation.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "OrganizationAffiliation.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "OrganizationAffiliation.language",
      path: "OrganizationAffiliation.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "OrganizationAffiliation.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "OrganizationAffiliation.contained",
      path: "OrganizationAffiliation.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source:
            "http://hl7.org/fhir/StructureDefinition/OrganizationAffiliation",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "OrganizationAffiliation.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "OrganizationAffiliation.active",
      path: "OrganizationAffiliation.active",
      short: "Whether this organization affiliation record is in active use",
      definition:
        "Whether this organization affiliation record is in active use.",
      comment:
        "If this value is false, you may refer to the period to see when the role was in active use. If there is no period specified, no inference can be made about when it was active.",
      requirements:
        "Need to be able to mark an organization affiliation record as not to be used because it was created in error, or otherwise no longer in active use.",
      min: 0,
      max: "1",
      base: { path: "OrganizationAffiliation.active", min: 0, max: "1" },
      type: [{ code: "boolean" }],
      meaningWhenMissing:
        "This resource is generally assumed to be active if no value is provided for the active element",
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "w5", map: "FiveWs.status" },
        { identity: "rim", map: ".statusCode" },
      ],
    },
    dataPath: "root.active",
    parentDataPath: "root",
    basePath: "root.active",
    baseId: "OrganizationAffiliation.active",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "OrganizationAffiliation.organization",
      path: "OrganizationAffiliation.organization",
      short: "Organization where the role is available",
      definition:
        "Organization where the role is available (primary organization/has members).",
      min: 0,
      max: "1",
      base: { path: "OrganizationAffiliation.organization", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Organization",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "rim", map: ".scoper" }],
    },
    dataPath: "root.organization",
    parentDataPath: "root",
    basePath: "root.organization",
    baseId: "OrganizationAffiliation.organization",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "OrganizationAffiliation.network",
      path: "OrganizationAffiliation.network",
      short:
        "Health insurance provider network in which the participatingOrganization provides the role's services (if defined) at the indicated locations (if defined)",
      definition:
        "Health insurance provider network in which the participatingOrganization provides the role's services (if defined) at the indicated locations (if defined).",
      min: 0,
      max: "*",
      base: { path: "OrganizationAffiliation.network", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Organization",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.network[0]",
    parentDataPath: "root",
    basePath: "root.network",
    baseId: "OrganizationAffiliation.network",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "OrganizationAffiliation.code",
      path: "OrganizationAffiliation.code",
      short: "Definition of the role the participatingOrganization plays",
      definition:
        "Definition of the role the participatingOrganization plays in the association.",
      min: 0,
      max: "*",
      base: { path: "OrganizationAffiliation.code", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "OrganizationAffiliation",
          },
        ],
        strength: "example",
        description:
          "The role the participating organization providing services to the primary organization.",
        valueSet: "http://hl7.org/fhir/ValueSet/organization-role",
      },
      mapping: [{ identity: "rim", map: ".code" }],
    },
    dataPath: "root.code[0]",
    parentDataPath: "root",
    basePath: "root.code",
    baseId: "OrganizationAffiliation.code",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/organization-role",
        code: "provider",
        display: "Provider",
      },
      {
        system: "http://hl7.org/fhir/organization-role",
        code: "agency",
        display: "Agency",
      },
      {
        system: "http://hl7.org/fhir/organization-role",
        code: "research",
        display: "Research",
      },
      {
        system: "http://hl7.org/fhir/organization-role",
        code: "payer",
        display: "Payer",
      },
      {
        system: "http://hl7.org/fhir/organization-role",
        code: "diagnostics",
        display: "Diagnostics",
      },
      {
        system: "http://hl7.org/fhir/organization-role",
        code: "supplier",
        display: "Supplier",
      },
      {
        system: "http://hl7.org/fhir/organization-role",
        code: "HIE/HIO",
        display: "HIE/HIO",
      },
      {
        system: "http://hl7.org/fhir/organization-role",
        code: "member",
        display: "Member",
      },
    ],
  },
  {
    element: {
      id: "OrganizationAffiliation.specialty",
      path: "OrganizationAffiliation.specialty",
      short:
        "Specific specialty of the participatingOrganization in the context of the role",
      definition:
        "Specific specialty of the participatingOrganization in the context of the role.",
      min: 0,
      max: "*",
      base: { path: "OrganizationAffiliation.specialty", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "OrganizationSpecialty",
          },
        ],
        strength: "preferred",
        description:
          "Specific specialty associated with the participating organization.",
        valueSet: "http://hl7.org/fhir/ValueSet/c80-practice-codes",
      },
      mapping: [
        {
          identity: "rim",
          map: ".player.HealthCareProvider[@classCode = 'PROV'].code",
        },
      ],
    },
    dataPath: "root.specialty[0]",
    parentDataPath: "root",
    basePath: "root.specialty",
    baseId: "OrganizationAffiliation.specialty",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "408467006", display: "Adult mental illness" },
      { code: "394577000", display: "Anesthetics" },
      { code: "394578005", display: "Audiological medicine" },
      { code: "421661004", display: "Blood banking and transfusion medicine" },
      { code: "408462000", display: "Burns care" },
      { code: "394579002", display: "Cardiology" },
      {
        code: "394804000",
        display: "Clinical cytogenetics and molecular genetics",
      },
      { code: "394580004", display: "Clinical genetics" },
      { code: "394803006", display: "Clinical hematology" },
      { code: "408480009", display: "Clinical immunology" },
      { code: "408454008", display: "Clinical microbiology" },
      { code: "394809005", display: "Clinical neuro-physiology" },
      { code: "394592004", display: "Clinical oncology" },
      { code: "394600006", display: "Clinical pharmacology" },
      { code: "394601005", display: "Clinical physiology" },
      { code: "394581000", display: "Community medicine" },
      { code: "408478003", display: "Critical care medicine" },
      { code: "394812008", display: "Dental medicine specialties" },
      { code: "408444009", display: "Dental-General dental practice" },
      { code: "394582007", display: "Dermatology" },
      { code: "408475000", display: "Diabetic medicine" },
      { code: "410005002", display: "Dive medicine" },
      { code: "394583002", display: "Endocrinology" },
      { code: "419772000", display: "Family practice" },
      { code: "394584008", display: "Gastroenterology" },
      { code: "408443003", display: "General medical practice" },
      { code: "394802001", display: "General medicine" },
      { code: "394915009", display: "General pathology" },
      { code: "394814009", display: "General practice" },
      { code: "394808002", display: "Genito-urinary medicine" },
      { code: "394811001", display: "Geriatric medicine" },
      { code: "408446006", display: "Gynecological oncology" },
      { code: "394586005", display: "Gynecology" },
      { code: "394916005", display: "Hematopathology" },
      { code: "408472002", display: "Hepatology" },
      { code: "394597005", display: "Histopathology" },
      { code: "394598000", display: "Immunopathology" },
      { code: "394807007", display: "Infectious diseases" },
      { code: "419192003", display: "Internal medicine" },
      { code: "408468001", display: "Learning disability" },
      { code: "394593009", display: "Medical oncology" },
      { code: "394813003", display: "Medical ophthalmology" },
      { code: "410001006", display: "Military medicine" },
      { code: "394589003", display: "Nephrology" },
      { code: "394591006", display: "Neurology" },
      { code: "394599008", display: "Neuropathology" },
      { code: "394649004", display: "Nuclear medicine" },
      { code: "408470005", display: "Obstetrics" },
      { code: "394585009", display: "Obstetrics and gynecology" },
      { code: "394821009", display: "Occupational medicine" },
      { code: "422191005", display: "Ophthalmic surgery" },
      { code: "394594003", display: "Ophthalmology" },
      { code: "416304004", display: "Osteopathic manipulative medicine" },
      { code: "418960008", display: "Otolaryngology" },
      { code: "394882004", display: "Pain management" },
      { code: "394806003", display: "Palliative medicine" },
      {
        code: "394588006",
        display: "Pediatric (Child and adolescent) psychiatry",
      },
      { code: "408459003", display: "Pediatric cardiology" },
      { code: "394607009", display: "Pediatric dentistry" },
      { code: "419610006", display: "Pediatric endocrinology" },
      { code: "418058008", display: "Pediatric gastroenterology" },
      { code: "420208008", display: "Pediatric genetics" },
      { code: "418652005", display: "Pediatric hematology" },
      { code: "418535003", display: "Pediatric immunology" },
      { code: "418862001", display: "Pediatric infectious diseases" },
      { code: "419365004", display: "Pediatric nephrology" },
      { code: "418002000", display: "Pediatric oncology" },
      { code: "419983000", display: "Pediatric ophthalmology" },
      { code: "419170002", display: "Pediatric pulmonology" },
      { code: "419472004", display: "Pediatric rheumatology" },
      { code: "394539006", display: "Pediatric surgery" },
      {
        code: "420112009",
        display: "Pediatric surgery-bone marrow transplantation",
      },
      { code: "409968004", display: "Preventive medicine" },
      { code: "394587001", display: "Psychiatry" },
      { code: "394913002", display: "Psychotherapy" },
      { code: "408440000", display: "Public health medicine" },
      { code: "418112009", display: "Pulmonary medicine" },
      { code: "419815003", display: "Radiation oncology" },
      { code: "394914008", display: "Radiology" },
      { code: "408455009", display: "Radiology-Interventional radiology" },
      { code: "394602003", display: "Rehabilitation" },
      { code: "408447002", display: "Respite care" },
      { code: "394810000", display: "Rheumatology" },
      { code: "408450004", display: "Sleep studies" },
      { code: "408476004", display: "Surgery-Bone and marrow transplantation" },
      { code: "408469009", display: "Surgery-Breast surgery" },
      { code: "408466002", display: "Surgery-Cardiac surgery" },
      { code: "408471009", display: "Surgery-Cardiothoracic transplantation" },
      { code: "408464004", display: "Surgery-Colorectal surgery" },
      { code: "408441001", display: "Surgery-Dental-Endodontics" },
      {
        code: "408465003",
        display: "Surgery-Dental-Oral and maxillofacial surgery",
      },
      { code: "394605001", display: "Surgery-Dental-Oral surgery" },
      { code: "394608004", display: "Surgery-Dental-Orthodontics" },
      { code: "408461007", display: "Surgery-Dental-Periodontal surgery" },
      {
        code: "408460008",
        display: "Surgery-Dental-Prosthetic dentistry (Prosthodontics)",
      },
      { code: "408460008", display: "Surgery-Dental-surgical-Prosthodontics" },
      { code: "394606000", display: "Surgery-Dentistry-Restorative dentistry" },
      { code: "408449004", display: "Surgery-Dentistry--surgical" },
      { code: "394608004", display: "Surgery-Dentistry-surgical-Orthodontics" },
      { code: "418018006", display: "Surgery-Dermatologic surgery" },
      { code: "394604002", display: "Surgery-Ear, nose and throat surgery" },
      { code: "394609007", display: "Surgery-general" },
      {
        code: "408474001",
        display: "Surgery-Hepatobiliary and pancreatic surgery",
      },
      { code: "394610002", display: "Surgery-Neurosurgery" },
      { code: "394611003", display: "Surgery-Plastic surgery" },
      { code: "408477008", display: "Surgery-Transplantation surgery" },
      { code: "394801008", display: "Surgery-Trauma and orthopedics" },
      { code: "408463005", display: "Surgery-Vascular" },
      { code: "419321007", display: "Surgical oncology" },
      { code: "394576009", display: "Surgical-Accident & emergency" },
      { code: "394590007", display: "Thoracic medicine" },
      { code: "409967009", display: "Toxicology" },
      { code: "408448007", display: "Tropical medicine" },
      { code: "419043006", display: "Urological oncology" },
      { code: "394612005", display: "Urology" },
      { code: "394733009", display: "Medical specialty--OTHER--NOT LISTED" },
      { code: "394732004", display: "Surgical specialty--OTHER-NOT LISTED" },
    ],
  },
  {
    element: {
      id: "OrganizationAffiliation.healthcareService",
      path: "OrganizationAffiliation.healthcareService",
      short: "Healthcare services provided through the role",
      definition: "Healthcare services provided through the role.",
      min: 0,
      max: "*",
      base: {
        path: "OrganizationAffiliation.healthcareService",
        min: 0,
        max: "*",
      },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/HealthcareService",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".player.QualifiedEntity[@classCode = 'QUAL'].code",
        },
      ],
    },
    dataPath: "root.healthcareService[0]",
    parentDataPath: "root",
    basePath: "root.healthcareService",
    baseId: "OrganizationAffiliation.healthcareService",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "OrganizationAffiliation.endpoint",
      path: "OrganizationAffiliation.endpoint",
      short:
        "Technical endpoints providing access to services operated for this role",
      definition:
        "Technical endpoints providing access to services operated for this role.",
      min: 0,
      max: "*",
      base: { path: "OrganizationAffiliation.endpoint", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Endpoint"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "n/a" }],
    },
    dataPath: "root.endpoint[0]",
    parentDataPath: "root",
    basePath: "root.endpoint",
    baseId: "OrganizationAffiliation.endpoint",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "OrganizationAffiliation",
      path: "OrganizationAffiliation",
      short:
        "Defines an affiliation/assotiation/relationship between 2 distinct oganizations, that is not a part-of relationship/sub-division relationship",
      definition:
        "Defines an affiliation/assotiation/relationship between 2 distinct oganizations, that is not a part-of relationship/sub-division relationship.",
      min: 0,
      max: "*",
      base: { path: "OrganizationAffiliation", min: 0, max: "*" },
      constraint: [
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "rim", map: "Role" },
        { identity: "w5", map: "administrative.individual" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "OrganizationAffiliation",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
