const data = [
  {
    element: {
      id: "Organization.meta",
      path: "Organization.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "Organization.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Organization.implicitRules",
      path: "Organization.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "Organization.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Organization.language",
      path: "Organization.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "Organization.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "Organization.contained",
      path: "Organization.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source: "http://hl7.org/fhir/StructureDefinition/Organization",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "Organization.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Organization.active",
      path: "Organization.active",
      short: "Whether the organization's record is still in active use",
      definition: "Whether the organization's record is still in active use.",
      comment:
        "This active flag is not intended to be used to mark an organization as temporarily closed or under construction. Instead the Location(s) within the Organization should have the suspended status. If further details of the reason for the suspension are required, then an extension on this element should be used.\n\nThis element is labeled as a modifier because it may be used to mark that the resource was created in error.",
      requirements:
        "Need a flag to indicate a record is no longer to be used and should generally be hidden for the user in the UI.",
      min: 0,
      max: "1",
      base: { path: "Organization.active", min: 0, max: "1" },
      type: [{ code: "boolean" }],
      meaningWhenMissing:
        "This resource is generally assumed to be active if no value is provided for the active element",
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labelled as a modifier because it is a status element that can indicate that a record should not be treated as valid",
      isSummary: true,
      mapping: [
        { identity: "w5", map: "FiveWs.status" },
        { identity: "v2", map: "No equivalent in HL7 v2" },
        { identity: "rim", map: ".status" },
        {
          identity: "servd",
          map: "./Status (however this concept in ServD more covers why the organization is active or not, could be delisted, deregistered, not operational yet) this could alternatively be derived from ./StartDate and ./EndDate and given a context date.",
        },
      ],
    },
    dataPath: "root.active",
    parentDataPath: "root",
    basePath: "root.active",
    baseId: "Organization.active",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Organization.type",
      path: "Organization.type",
      short: "Kind of organization",
      definition: "The kind(s) of organization that this is.",
      comment:
        "Organizations can be corporations, wards, sections, clinical teams, government departments, etc. Note that code is generally a classifier of the type of organization; in many applications, codes are used to identity a particular organization (say, ward) as opposed to another of the same type - these are identifiers, not codes\n\nWhen considering if multiple types are appropriate, you should evaluate if child organizations would be a more appropriate use of the concept, as different types likely are in different sub-areas of the organization. This is most likely to be used where type values have orthogonal values, such as a religious, academic and medical center.\n\nWe expect that some jurisdictions will profile this optionality to be a single cardinality.",
      requirements:
        "Need to be able to track the kind of organization that this is - different organization types have different uses.",
      min: 0,
      max: "*",
      base: { path: "Organization.type", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "OrganizationType",
          },
        ],
        strength: "example",
        description: "Used to categorize the organization.",
        valueSet: "http://hl7.org/fhir/ValueSet/organization-type",
      },
      mapping: [
        { identity: "w5", map: "FiveWs.class" },
        { identity: "v2", map: "No equivalent in v2" },
        { identity: "rim", map: ".code" },
        { identity: "servd", map: "n/a" },
      ],
    },
    dataPath: "root.type[0]",
    parentDataPath: "root",
    basePath: "root.type",
    baseId: "Organization.type",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "prov",
        display: "Healthcare Provider",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "dept",
        display: "Hospital Department",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "team",
        display: "Organizational team",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "govt",
        display: "Government",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "ins",
        display: "Insurance Company",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "pay",
        display: "Payer",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "edu",
        display: "Educational Institute",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "reli",
        display: "Religious Institution",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "crs",
        display: "Clinical Research Sponsor",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "cg",
        display: "Community Group",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "bus",
        display: "Non-Healthcare Business or Corporation",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/organization-type",
        code: "other",
        display: "Other",
      },
    ],
  },
  {
    element: {
      id: "Organization.name",
      path: "Organization.name",
      short: "Name used for the organization",
      definition: "A name associated with the organization.",
      comment:
        "If the name of an organization changes, consider putting the old name in the alias column so that it can still be located through searches.",
      requirements: "Need to use the name as the label of the organization.",
      min: 0,
      max: "1",
      base: { path: "Organization.name", min: 0, max: "1" },
      type: [{ code: "string" }],
      condition: ["org-1"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "v2", map: "XON.1" },
        { identity: "rim", map: ".name" },
        { identity: "servd", map: ".PreferredName/Name" },
      ],
    },
    dataPath: "root.name",
    parentDataPath: "root",
    basePath: "root.name",
    baseId: "Organization.name",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Organization.alias",
      path: "Organization.alias",
      short:
        "A list of alternate names that the organization is known as, or was known as in the past",
      definition:
        "A list of alternate names that the organization is known as, or was known as in the past.",
      comment:
        "There are no dates associated with the alias/historic names, as this is not intended to track when names were used, but to assist in searching so that older names can still result in identifying the organization.",
      requirements:
        "Over time locations and organizations go through many changes and can be known by different names.\n\nFor searching knowing previous names that the organization was known by can be very useful.",
      min: 0,
      max: "*",
      base: { path: "Organization.alias", min: 0, max: "*" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: ".name" }],
    },
    dataPath: "root.alias[0]",
    parentDataPath: "root",
    basePath: "root.alias",
    baseId: "Organization.alias",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Organization.address",
      path: "Organization.address",
      short: "An address for the organization",
      definition: "An address for the organization.",
      comment:
        "Organization may have multiple addresses with different uses or applicable periods. The use code 'home' is not to be used.",
      requirements:
        "May need to keep track of the organization's addresses for contacting, billing or reporting requirements.",
      min: 0,
      max: "*",
      base: { path: "Organization.address", min: 0, max: "*" },
      type: [{ code: "Address" }],
      condition: ["org-2"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
        {
          key: "org-2",
          severity: "error",
          human: "An address of an organization can never be of use 'home'",
          expression: "where(use = 'home').empty()",
          xpath: "count(f:use[@value='home']) = 0",
          source: "http://hl7.org/fhir/StructureDefinition/Organization",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "v2", map: "ORC-23?" },
        { identity: "rim", map: ".address" },
        { identity: "servd", map: "./PrimaryAddress and ./OtherAddresses" },
      ],
    },
    dataPath: "root.address[0]",
    parentDataPath: "root",
    basePath: "root.address",
    baseId: "Organization.address",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Organization.contact",
      path: "Organization.contact",
      short: "Contact for the organization for a certain purpose",
      definition: "Contact for the organization for a certain purpose.",
      comment:
        "Where multiple contacts for the same purpose are provided there is a standard extension that can be used to determine which one is the preferred contact to use.",
      requirements:
        "Need to keep track of assigned contact points within bigger organization.",
      min: 0,
      max: "*",
      base: { path: "Organization.contact", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: ".contactParty" }],
    },
    dataPath: "root.contact[0]",
    parentDataPath: "root",
    basePath: "root.contact",
    baseId: "Organization.contact",
    isPrimitive: false,
    childPaths: [
      "root.contact.purpose",
      "root.contact.name",
      "root.contact.telecom[0]",
      "root.contact.address",
    ],
    value: "",
  },
  {
    element: {
      id: "Organization.contact.purpose",
      path: "Organization.contact.purpose",
      short: "The type of contact",
      definition: "Indicates a purpose for which the contact can be reached.",
      requirements: "Need to distinguish between multiple contact persons.",
      min: 0,
      max: "1",
      base: { path: "Organization.contact.purpose", min: 0, max: "1" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ContactPartyType",
          },
        ],
        strength: "extensible",
        description: "The purpose for which you would contact a contact party.",
        valueSet: "http://hl7.org/fhir/ValueSet/contactentity-type",
      },
      mapping: [{ identity: "rim", map: "./type" }],
    },
    dataPath: "root.contact.purpose",
    parentDataPath: "root.contact[0]",
    basePath: "root.purpose",
    baseId: "Organization.contact.purpose",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://terminology.hl7.org/CodeSystem/contactentity-type",
        code: "BILL",
        display: "Billing",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/contactentity-type",
        code: "ADMIN",
        display: "Administrative",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/contactentity-type",
        code: "HR",
        display: "Human Resource",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/contactentity-type",
        code: "PAYOR",
        display: "Payor",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/contactentity-type",
        code: "PATINF",
        display: "Patient",
      },
      {
        system: "http://terminology.hl7.org/CodeSystem/contactentity-type",
        code: "PRESS",
        display: "Press",
      },
    ],
  },
  {
    element: {
      id: "Organization.contact.telecom",
      path: "Organization.contact.telecom",
      short: "Contact details (telephone, email, etc.)  for a contact",
      definition:
        "A contact detail (e.g. a telephone number or an email address) by which the party may be contacted.",
      requirements:
        "People have (primary) ways to contact them in some way such as phone, email.",
      min: 0,
      max: "*",
      base: { path: "Organization.contact.telecom", min: 0, max: "*" },
      type: [{ code: "ContactPoint" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "v2", map: "PID-13, PID-14" },
        { identity: "rim", map: "./telecom" },
      ],
    },
    dataPath: "root.contact.telecom[0]",
    parentDataPath: "root.contact[0]",
    basePath: "root.telecom",
    baseId: "Organization.contact.telecom",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Organization.endpoint",
      path: "Organization.endpoint",
      short:
        "Technical endpoints providing access to services operated for the organization",
      definition:
        "Technical endpoints providing access to services operated for the organization.",
      requirements:
        "Organizations have multiple systems that provide various services and need to be able to define the technical connection details for how to connect to them, and for what purpose.",
      min: 0,
      max: "*",
      base: { path: "Organization.endpoint", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Endpoint"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "n/a" }],
    },
    dataPath: "root.endpoint[0]",
    parentDataPath: "root",
    basePath: "root.endpoint",
    baseId: "Organization.endpoint",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Organization",
      path: "Organization",
      short: "A grouping of people or organizations with a common purpose",
      definition:
        "A formally or informally recognized grouping of people or organizations formed for the purpose of achieving some form of collective action.  Includes companies, institutions, corporations, departments, community groups, healthcare practice groups, payer/insurer, etc.",
      min: 0,
      max: "*",
      base: { path: "Organization", min: 0, max: "*" },
      constraint: [
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "org-1",
          severity: "error",
          human:
            "The organization SHALL at least have a name or an identifier, and possibly more than one",
          expression: "(identifier.count() + name.count()) > 0",
          xpath: "count(f:identifier | f:name) > 0",
          source: "http://hl7.org/fhir/StructureDefinition/Organization",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "v2", map: "(also see master files messages)" },
        {
          identity: "rim",
          map: "Organization(classCode=ORG, determinerCode=INST)",
        },
        { identity: "servd", map: "Organization" },
        { identity: "w5", map: "administrative.group" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "Organization",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
