const data = [
  {
    element: {
      id: "Procedure.meta",
      path: "Procedure.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "Procedure.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.implicitRules",
      path: "Procedure.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "Procedure.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.language",
      path: "Procedure.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "Procedure.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "Procedure.contained",
      path: "Procedure.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source: "http://hl7.org/fhir/StructureDefinition/Procedure",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "Procedure.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.instantiatesCanonical",
      path: "Procedure.instantiatesCanonical",
      short: "Instantiates FHIR protocol or definition",
      definition:
        "The URL pointing to a FHIR-defined protocol, guideline, order set or other definition that is adhered to in whole or in part by this Procedure.",
      min: 0,
      max: "*",
      base: { path: "Procedure.instantiatesCanonical", min: 0, max: "*" },
      type: [
        {
          code: "canonical",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/PlanDefinition",
            "http://hl7.org/fhir/StructureDefinition/ActivityDefinition",
            "http://hl7.org/fhir/StructureDefinition/Measure",
            "http://hl7.org/fhir/StructureDefinition/OperationDefinition",
            "http://hl7.org/fhir/StructureDefinition/Questionnaire",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.instantiatesCanonical" },
        { identity: "rim", map: ".outboundRelationship[typeCode=DEFN].target" },
      ],
    },
    dataPath: "root.instantiatesCanonical[0]",
    parentDataPath: "root",
    basePath: "root.instantiatesCanonical",
    baseId: "Procedure.instantiatesCanonical",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.instantiatesUri",
      path: "Procedure.instantiatesUri",
      short: "Instantiates external protocol or definition",
      definition:
        "The URL pointing to an externally maintained protocol, guideline, order set or other definition that is adhered to in whole or in part by this Procedure.",
      comment:
        "This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier.",
      min: 0,
      max: "*",
      base: { path: "Procedure.instantiatesUri", min: 0, max: "*" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.instantiatesUri" },
        { identity: "rim", map: ".outboundRelationship[typeCode=DEFN].target" },
      ],
    },
    dataPath: "root.instantiatesUri[0]",
    parentDataPath: "root",
    basePath: "root.instantiatesUri",
    baseId: "Procedure.instantiatesUri",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.partOf",
      path: "Procedure.partOf",
      short: "Part of referenced event",
      definition:
        "A larger event of which this particular procedure is a component or step.",
      comment:
        "The MedicationAdministration resource has a partOf reference to Procedure, but this is not a circular reference.   For example, the anesthesia MedicationAdministration is part of the surgical Procedure (MedicationAdministration.partOf = Procedure).  For example, the procedure to insert the IV port for an IV medication administration is part of the medication administration (Procedure.partOf = MedicationAdministration).",
      alias: ["container"],
      min: 0,
      max: "*",
      base: { path: "Procedure.partOf", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Procedure",
            "http://hl7.org/fhir/StructureDefinition/Observation",
            "http://hl7.org/fhir/StructureDefinition/MedicationAdministration",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.partOf" },
        {
          identity: "rim",
          map: ".inboundRelationship[typeCode=COMP].source[classCode=SBADM or PROC or OBS, moodCode=EVN]",
        },
      ],
    },
    dataPath: "root.partOf[0]",
    parentDataPath: "root",
    basePath: "root.partOf",
    baseId: "Procedure.partOf",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.status",
      path: "Procedure.status",
      short:
        "preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown",
      definition:
        "A code specifying the state of the procedure. Generally, this will be the in-progress or completed state.",
      comment:
        'The "unknown" code is not to be used to convey other statuses.  The "unknown" code should be used when one of the statuses applies, but the authoring system doesn\'t know the current state of the procedure.\n\nThis element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.',
      min: 1,
      max: "1",
      base: { path: "Procedure.status", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid",
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ProcedureStatus",
          },
        ],
        strength: "required",
        description: "A code specifying the state of the procedure.",
        valueSet: "http://hl7.org/fhir/ValueSet/event-status|4.3.0",
      },
      mapping: [
        { identity: "workflow", map: "Event.status" },
        { identity: "w5", map: "FiveWs.status" },
        { identity: "rim", map: "statusCode" },
      ],
    },
    dataPath: "root.status",
    parentDataPath: "root",
    basePath: "root.status",
    baseId: "Procedure.status",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/event-status",
        code: "preparation",
        display: "Preparation",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "in-progress",
        display: "In Progress",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "not-done",
        display: "Not Done",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "on-hold",
        display: "On Hold",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "stopped",
        display: "Stopped",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "completed",
        display: "Completed",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "entered-in-error",
        display: "Entered in Error",
      },
      {
        system: "http://hl7.org/fhir/event-status",
        code: "unknown",
        display: "Unknown",
      },
    ],
  },
  {
    element: {
      id: "Procedure.category",
      path: "Procedure.category",
      short: "Classification of the procedure",
      definition:
        'A code that classifies the procedure for searching, sorting and display purposes (e.g. "Surgical Procedure").',
      min: 0,
      max: "1",
      base: { path: "Procedure.category", min: 0, max: "1" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ProcedureCategory",
          },
        ],
        strength: "example",
        description:
          "A code that classifies a procedure for searching, sorting and display purposes.",
        valueSet: "http://hl7.org/fhir/ValueSet/procedure-category",
      },
      mapping: [
        { identity: "w5", map: "FiveWs.class" },
        {
          identity: "rim",
          map: '.outboundRelationship[typeCode="COMP].target[classCode="LIST", moodCode="EVN"].code',
        },
      ],
    },
    dataPath: "root.category",
    parentDataPath: "root",
    basePath: "root.category",
    baseId: "Procedure.category",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "24642003" },
      { code: "409063005" },
      { code: "409073007" },
      { code: "387713003" },
      { code: "103693007" },
      { code: "46947000" },
      { code: "410606002" },
    ],
  },
  {
    element: {
      id: "Procedure.subject",
      path: "Procedure.subject",
      short: "Who the procedure was performed on",
      definition:
        "The person, animal or group on which the procedure was performed.",
      alias: ["patient"],
      min: 1,
      max: "1",
      base: { path: "Procedure.subject", min: 1, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Patient",
            "http://hl7.org/fhir/StructureDefinition/Group",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.subject" },
        { identity: "w5", map: "FiveWs.subject[x]" },
        { identity: "v2", map: "PID-3" },
        { identity: "rim", map: ".participation[typeCode=SBJ].role" },
        { identity: "w5", map: "FiveWs.subject" },
      ],
    },
    dataPath: "root.subject",
    parentDataPath: "root",
    basePath: "root.subject",
    baseId: "Procedure.subject",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.performed[x]",
      path: "Procedure.performed[x]",
      short: "When the procedure was performed",
      definition:
        "Estimated or actual date, date-time, period, or age when the procedure was performed.  Allows a period to support complex procedures that span more than one date, and also allows for the length of the procedure to be captured.",
      comment:
        "Age is generally used when the patient reports an age at which the procedure was performed. Range is generally used when the patient reports an age range when the procedure was performed, such as sometime between 20-25 years old.  dateTime supports a range of precision due to some procedures being reported as past procedures that might not have millisecond precision while other procedures performed and documented during the encounter might have more precise UTC timestamps with timezone.",
      min: 0,
      max: "1",
      base: { path: "Procedure.performed[x]", min: 0, max: "1" },
      type: [
        { code: "dateTime" },
        { code: "Period" },
        { code: "string" },
        { code: "Age" },
        { code: "Range" },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.occurrence[x]" },
        { identity: "w5", map: "FiveWs.done[x]" },
        { identity: "v2", map: "OBR-7" },
        { identity: "rim", map: ".effectiveTime" },
      ],
    },
    dataPath: "root.performed[x]",
    parentDataPath: "root",
    basePath: "root.performed[x]",
    baseId: "Procedure.performed[x]",
    isPrimitive: false,
    childPaths: [],
    multiTypeType: "dateTime",
    value: "",
  },
  {
    element: {
      id: "Procedure.asserter",
      path: "Procedure.asserter",
      short: "Person who asserts this procedure",
      definition: "Individual who is making the procedure statement.",
      min: 0,
      max: "1",
      base: { path: "Procedure.asserter", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Patient",
            "http://hl7.org/fhir/StructureDefinition/RelatedPerson",
            "http://hl7.org/fhir/StructureDefinition/Practitioner",
            "http://hl7.org/fhir/StructureDefinition/PractitionerRole",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "w5", map: "FiveWs.source" },
        { identity: "rim", map: ".participation[typeCode=INF].role" },
      ],
    },
    dataPath: "root.asserter",
    parentDataPath: "root",
    basePath: "root.asserter",
    baseId: "Procedure.asserter",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.performer",
      path: "Procedure.performer",
      short: "The people who performed the procedure",
      definition: 'Limited to "real" people rather than equipment.',
      min: 0,
      max: "*",
      base: { path: "Procedure.performer", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.performer" },
        { identity: "rim", map: ".participation[typeCode=PRF]" },
      ],
    },
    dataPath: "root.performer[0]",
    parentDataPath: "root",
    basePath: "root.performer",
    baseId: "Procedure.performer",
    isPrimitive: false,
    childPaths: [
      "root.performer.function",
      "root.performer.actor",
      "root.performer.onBehalfOf",
    ],
    value: "",
  },
  {
    element: {
      id: "Procedure.performer.actor",
      path: "Procedure.performer.actor",
      short: "The reference to the practitioner",
      definition: "The practitioner who was involved in the procedure.",
      requirements:
        "A reference to Device supports use cases, such as pacemakers.",
      min: 1,
      max: "1",
      base: { path: "Procedure.performer.actor", min: 1, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Practitioner",
            "http://hl7.org/fhir/StructureDefinition/PractitionerRole",
            "http://hl7.org/fhir/StructureDefinition/Organization",
            "http://hl7.org/fhir/StructureDefinition/Patient",
            "http://hl7.org/fhir/StructureDefinition/RelatedPerson",
            "http://hl7.org/fhir/StructureDefinition/Device",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.performer.actor" },
        { identity: "w5", map: "FiveWs.actor" },
        { identity: "v2", map: "ORC-19/PRT-5" },
        { identity: "rim", map: ".role" },
      ],
    },
    dataPath: "root.performer.actor",
    parentDataPath: "root.performer[0]",
    basePath: "root.actor",
    baseId: "Procedure.performer.actor",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.location",
      path: "Procedure.location",
      short: "Where the procedure happened",
      definition:
        "The location where the procedure actually happened.  E.g. a newborn at home, a tracheostomy at a restaurant.",
      requirements: "Ties a procedure to where the records are likely kept.",
      min: 0,
      max: "1",
      base: { path: "Procedure.location", min: 0, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Location"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "w5", map: "FiveWs.where[x]" },
        {
          identity: "rim",
          map: ".participation[typeCode=LOC].role[classCode=SDLOC]",
        },
      ],
    },
    dataPath: "root.location",
    parentDataPath: "root",
    basePath: "root.location",
    baseId: "Procedure.location",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.reasonReference",
      path: "Procedure.reasonReference",
      short: "The justification that the procedure was performed",
      definition: "The justification of why the procedure was performed.",
      comment:
        "It is possible for a procedure to be a reason (such as C-Section) for another procedure (such as an epidural). Other examples include endoscopy for dilatation and biopsy (a combination of diagnostic and therapeutic use). \nUse Procedure.reasonCode when a code sufficiently describes the reason.  Use Procedure.reasonReference when referencing a resource, which allows more information to be conveyed, such as onset date. Procedure.reasonCode and Procedure.reasonReference are not meant to be duplicative.  For a single reason, either Procedure.reasonCode or Procedure.reasonReference can be used.  Procedure.reasonCode may be a summary code, or Procedure.reasonReference may be used to reference a very precise definition of the reason using Condition | Observation | Procedure | DiagnosticReport | DocumentReference.  Both Procedure.reasonCode and Procedure.reasonReference can be used if they are describing different reasons for the procedure.",
      min: 0,
      max: "*",
      base: { path: "Procedure.reasonReference", min: 0, max: "*" },
      type: [
        {
          code: "Reference",
          targetProfile: [
            "http://hl7.org/fhir/StructureDefinition/Condition",
            "http://hl7.org/fhir/StructureDefinition/Observation",
            "http://hl7.org/fhir/StructureDefinition/Procedure",
            "http://hl7.org/fhir/StructureDefinition/DiagnosticReport",
            "http://hl7.org/fhir/StructureDefinition/DocumentReference",
          ],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Event.reasonReference" },
        { identity: "w5", map: "FiveWs.why[x]" },
        { identity: "rim", map: ".reasonCode" },
      ],
    },
    dataPath: "root.reasonReference[0]",
    parentDataPath: "root",
    basePath: "root.reasonReference",
    baseId: "Procedure.reasonReference",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.outcome",
      path: "Procedure.outcome",
      short: "The result of procedure",
      definition:
        "The outcome of the procedure - did it resolve the reasons for the procedure being performed?",
      comment:
        "If outcome contains narrative text only, it can be captured using the CodeableConcept.text.",
      min: 0,
      max: "1",
      base: { path: "Procedure.outcome", min: 0, max: "1" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ProcedureOutcome",
          },
        ],
        strength: "example",
        description:
          "An outcome of a procedure - whether it was resolved or otherwise.",
        valueSet: "http://hl7.org/fhir/ValueSet/procedure-outcome",
      },
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=OUT].target.text",
        },
      ],
    },
    dataPath: "root.outcome",
    parentDataPath: "root",
    basePath: "root.outcome",
    baseId: "Procedure.outcome",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "385669000" },
      { code: "385671000" },
      { code: "385670004" },
    ],
  },
  {
    element: {
      id: "Procedure.complication",
      path: "Procedure.complication",
      short: "Complication following the procedure",
      definition:
        "Any complications that occurred during the procedure, or in the immediate post-performance period. These are generally tracked separately from the notes, which will typically describe the procedure itself rather than any 'post procedure' issues.",
      comment:
        "If complications are only expressed by the narrative text, they can be captured using the CodeableConcept.text.",
      min: 0,
      max: "*",
      base: { path: "Procedure.complication", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ProcedureComplication",
          },
        ],
        strength: "example",
        description:
          "Codes describing complications that resulted from a procedure.",
        valueSet: "http://hl7.org/fhir/ValueSet/condition-code",
      },
      mapping: [
        {
          identity: "rim",
          map: '.outboundRelationship[typeCode=OUTC].target[classCode=OBS, code="complication", moodCode=EVN].value',
        },
      ],
    },
    dataPath: "root.complication[0]",
    parentDataPath: "root",
    basePath: "root.complication",
    baseId: "Procedure.complication",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.followUp",
      path: "Procedure.followUp",
      short: "Instructions for follow up",
      definition:
        "If the procedure required specific follow up - e.g. removal of sutures. The follow up may be represented as a simple note or could potentially be more complex, in which case the CarePlan resource can be used.",
      min: 0,
      max: "*",
      base: { path: "Procedure.followUp", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ProcedureFollowUp",
          },
        ],
        strength: "example",
        description:
          "Specific follow up required for a procedure e.g. removal of sutures.",
        valueSet: "http://hl7.org/fhir/ValueSet/procedure-followup",
      },
      mapping: [
        {
          identity: "rim",
          map: ".outboundRelationship[typeCode=COMP].target[classCode=ACT, moodCode=INT].code",
        },
      ],
    },
    dataPath: "root.followUp[0]",
    parentDataPath: "root",
    basePath: "root.followUp",
    baseId: "Procedure.followUp",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "18949003" },
      { code: "30549001" },
      { code: "241031001" },
      { code: "35963001" },
      { code: "225164002" },
      { code: "447346005" },
      { code: "229506003" },
      { code: "274441001" },
      { code: "394725008" },
      { code: "359825008" },
    ],
  },
  {
    element: {
      id: "Procedure.focalDevice",
      path: "Procedure.focalDevice",
      short: "Manipulated, implanted, or removed device",
      definition:
        "A device that is implanted, removed or otherwise manipulated (calibration, battery replacement, fitting a prosthesis, attaching a wound-vac, etc.) as a focal portion of the Procedure.",
      min: 0,
      max: "*",
      base: { path: "Procedure.focalDevice", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".participation[typeCode=DEV].role[classCode=MANU]",
        },
      ],
    },
    dataPath: "root.focalDevice[0]",
    parentDataPath: "root",
    basePath: "root.focalDevice",
    baseId: "Procedure.focalDevice",
    isPrimitive: false,
    childPaths: ["root.focalDevice.action", "root.focalDevice.manipulated"],
    value: "",
  },
  {
    element: {
      id: "Procedure.focalDevice.manipulated",
      path: "Procedure.focalDevice.manipulated",
      short: "Device that was changed",
      definition:
        "The device that was manipulated (changed) during the procedure.",
      min: 1,
      max: "1",
      base: { path: "Procedure.focalDevice.manipulated", min: 1, max: "1" },
      type: [
        {
          code: "Reference",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/Device"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        {
          identity: "rim",
          map: ".participation[typeCode=DEV].role[classCode=SDLOC]",
        },
      ],
    },
    dataPath: "root.focalDevice.manipulated",
    parentDataPath: "root.focalDevice[0]",
    basePath: "root.manipulated",
    baseId: "Procedure.focalDevice.manipulated",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure.usedCode",
      path: "Procedure.usedCode",
      short: "Coded items used during the procedure",
      definition:
        "Identifies coded items that were used as part of the procedure.",
      comment:
        "For devices actually implanted or removed, use Procedure.device.",
      min: 0,
      max: "*",
      base: { path: "Procedure.usedCode", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "ProcedureUsed",
          },
        ],
        strength: "example",
        description: "Codes describing items used during a procedure.",
        valueSet: "http://hl7.org/fhir/ValueSet/device-kind",
      },
      mapping: [
        {
          identity: "rim",
          map: "participation[typeCode=Dev].role[classCode=MANU]",
        },
      ],
    },
    dataPath: "root.usedCode[0]",
    parentDataPath: "root",
    basePath: "root.usedCode",
    baseId: "Procedure.usedCode",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "Procedure",
      path: "Procedure",
      short: "An action that is being or was performed on a patient",
      definition:
        "An action that is or was performed on or for a patient. This can be a physical intervention like an operation, or less invasive like long term services, counseling, or hypnotherapy.",
      min: 0,
      max: "*",
      base: { path: "Procedure", min: 0, max: "*" },
      constraint: [
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "workflow", map: "Event" },
        { identity: "rim", map: "Procedure[moodCode=EVN]" },
        { identity: "w5", map: "clinical.general" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "Procedure",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
