const data = [
  {
    element: {
      id: "TerminologyCapabilities.meta",
      path: "TerminologyCapabilities.meta",
      short: "Metadata about the resource",
      definition:
        "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
      min: 0,
      max: "1",
      base: { path: "Resource.meta", min: 0, max: "1" },
      type: [{ code: "Meta" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.meta",
    parentDataPath: "root",
    basePath: "root.meta",
    baseId: "TerminologyCapabilities.meta",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.implicitRules",
      path: "TerminologyCapabilities.implicitRules",
      short: "A set of rules under which this content was created",
      definition:
        "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
      comment:
        "Asserting this rule set restricts the content to be only understood by a limited set of trading partners. This inherently limits the usefulness of the data in the long term. However, the existing health eco-system is highly fractured, and not yet ready to define, collect, and exchange data in a generally computable sense. Wherever possible, implementers and/or specification writers should avoid using this element. Often, when used, the URL is a reference to an implementation guide that defines these special rules as part of it's narrative along with other profiles, value sets, etc.",
      min: 0,
      max: "1",
      base: { path: "Resource.implicitRules", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        "This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation",
      isSummary: true,
    },
    dataPath: "root.implicitRules",
    parentDataPath: "root",
    basePath: "root.implicitRules",
    baseId: "TerminologyCapabilities.implicitRules",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.language",
      path: "TerminologyCapabilities.language",
      short: "Language of the resource content",
      definition: "The base language in which the resource is written.",
      comment:
        "Language is provided to support indexing and accessibility (typically, services such as text to speech use the language tag). The html language tag in the narrative applies  to the narrative. The language tag on the resource may be used to specify the language of other presentations generated from the data in the resource. Not all the content has to be in the base language. The Resource.language should not be assumed to apply to the narrative automatically. If a language is specified, it should it also be specified on the div element in the html (see rules in HTML5 for information about the relationship between xml:lang and the html lang attribute).",
      min: 0,
      max: "1",
      base: { path: "Resource.language", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-maxValueSet",
            valueCanonical: "http://hl7.org/fhir/ValueSet/all-languages",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Language",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "preferred",
        description: "IETF language tag",
        valueSet: "http://hl7.org/fhir/ValueSet/languages",
      },
    },
    dataPath: "root.language",
    parentDataPath: "root",
    basePath: "root.language",
    baseId: "TerminologyCapabilities.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      { code: "ar", display: "Arabic" },
      { code: "bn", display: "Bengali" },
      { code: "cs", display: "Czech" },
      { code: "da", display: "Danish" },
      { code: "de", display: "German" },
      { code: "de-AT", display: "German (Austria)" },
      { code: "de-CH", display: "German (Switzerland)" },
      { code: "de-DE", display: "German (Germany)" },
      { code: "el", display: "Greek" },
      { code: "en", display: "English" },
      { code: "en-AU", display: "English (Australia)" },
      { code: "en-CA", display: "English (Canada)" },
      { code: "en-GB", display: "English (Great Britain)" },
      { code: "en-IN", display: "English (India)" },
      { code: "en-NZ", display: "English (New Zeland)" },
      { code: "en-SG", display: "English (Singapore)" },
      { code: "en-US", display: "English (United States)" },
      { code: "es", display: "Spanish" },
      { code: "es-AR", display: "Spanish (Argentina)" },
      { code: "es-ES", display: "Spanish (Spain)" },
      { code: "es-UY", display: "Spanish (Uruguay)" },
      { code: "fi", display: "Finnish" },
      { code: "fr", display: "French" },
      { code: "fr-BE", display: "French (Belgium)" },
      { code: "fr-CH", display: "French (Switzerland)" },
      { code: "fr-FR", display: "French (France)" },
      { code: "fy", display: "Frysian" },
      { code: "fy-NL", display: "Frysian (Netherlands)" },
      { code: "hi", display: "Hindi" },
      { code: "hr", display: "Croatian" },
      { code: "it", display: "Italian" },
      { code: "it-CH", display: "Italian (Switzerland)" },
      { code: "it-IT", display: "Italian (Italy)" },
      { code: "ja", display: "Japanese" },
      { code: "ko", display: "Korean" },
      { code: "nl", display: "Dutch" },
      { code: "nl-BE", display: "Dutch (Belgium)" },
      { code: "nl-NL", display: "Dutch (Netherlands)" },
      { code: "no", display: "Norwegian" },
      { code: "no-NO", display: "Norwegian (Norway)" },
      { code: "pa", display: "Punjabi" },
      { code: "pl", display: "Polish" },
      { code: "pt", display: "Portuguese" },
      { code: "pt-BR", display: "Portuguese (Brazil)" },
      { code: "ru", display: "Russian" },
      { code: "ru-RU", display: "Russian (Russia)" },
      { code: "sr", display: "Serbian" },
      { code: "sr-RS", display: "Serbian (Serbia)" },
      { code: "sv", display: "Swedish" },
      { code: "sv-SE", display: "Swedish (Sweden)" },
      { code: "te", display: "Telegu" },
      { code: "zh", display: "Chinese" },
      { code: "zh-CN", display: "Chinese (China)" },
      { code: "zh-HK", display: "Chinese (Hong Kong)" },
      { code: "zh-SG", display: "Chinese (Singapore)" },
      { code: "zh-TW", display: "Chinese (Taiwan)" },
    ],
  },
  {
    element: {
      id: "TerminologyCapabilities.contained",
      path: "TerminologyCapabilities.contained",
      short: "Contained, inline Resources",
      definition:
        "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
      comment:
        "This should never be done when the content can be identified properly, as once identification is lost, it is extremely difficult (and context dependent) to restore it again. Contained resources may have profiles and tags In their meta elements, but SHALL NOT have security labels.",
      alias: ["inline resources", "anonymous resources", "contained resources"],
      min: 0,
      max: "*",
      base: { path: "DomainResource.contained", min: 0, max: "*" },
      type: [{ code: "Resource" }],
      constraint: [
        {
          key: "dom-r4b",
          severity: "warning",
          human:
            "Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems",
          expression:
            "($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)",
          xpath:
            "not(f:Citation|f:Evidence|f:EvidenceReport|f:EvidenceVariable|f:MedicinalProductDefinition|f:PackagedProductDefinition|f:AdministrableProductDefinition|f:Ingredient|f:ClinicalUseDefinition|f:RegulatedAuthorization|f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic) or not(parent::f:Citation|parent::f:Evidence|parent::f:EvidenceReport|parent::f:EvidenceVariable|parent::f:MedicinalProductDefinition|parent::f:PackagedProductDefinition|parent::f:AdministrableProductDefinition|parent::f:Ingredient|parent::f:ClinicalUseDefinition|parent::f:RegulatedAuthorization|parent::f:SubstanceDefinition|f:SubscriptionStatus|f:SubscriptionTopic)",
          source:
            "http://hl7.org/fhir/StructureDefinition/TerminologyCapabilities",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "rim", map: "N/A" }],
    },
    dataPath: "root.contained[0]",
    parentDataPath: "root",
    basePath: "root.contained",
    baseId: "TerminologyCapabilities.contained",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.url",
      path: "TerminologyCapabilities.url",
      short:
        "Canonical identifier for this terminology capabilities, represented as a URI (globally unique)",
      definition:
        "An absolute URI that is used to identify this terminology capabilities when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this terminology capabilities is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the terminology capabilities is stored on different servers.",
      comment:
        "Can be a urn:uuid: or a urn:oid: but real http: addresses are preferred.  Multiple instances may share the same URL if they have a distinct version.\n\nThe determination of when to create a new version of a resource (same url, new version) vs. defining a new artifact is up to the author.  Considerations for making this decision are found in [Technical and Business Versions](resource.html#versions). \n\nIn some cases, the resource can no longer be found at the stated url, but the url itself cannot change. Implementations can use the [meta.source](resource.html#meta) element to indicate where the current master source of the resource can be found.",
      requirements:
        "Allows the terminology capabilities to be referenced by a single globally unique identifier.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.url", min: 0, max: "1" },
      type: [{ code: "uri" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.url" },
        { identity: "w5", map: "FiveWs.identifier" },
      ],
    },
    dataPath: "root.url",
    parentDataPath: "root",
    basePath: "root.url",
    baseId: "TerminologyCapabilities.url",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.version",
      path: "TerminologyCapabilities.version",
      short: "Business version of the terminology capabilities",
      definition:
        "The identifier that is used to identify this version of the terminology capabilities when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the terminology capabilities author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence.",
      comment:
        "There may be different terminology capabilities instances that have the same identifier but different versions.  The version can be appended to the url in a reference to allow a reference to a particular business version of the terminology capabilities with the format [url]|[version].",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.version", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.version" },
        { identity: "w5", map: "FiveWs.version" },
      ],
    },
    dataPath: "root.version",
    parentDataPath: "root",
    basePath: "root.version",
    baseId: "TerminologyCapabilities.version",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.name",
      path: "TerminologyCapabilities.name",
      short: "Name for this terminology capabilities (computer friendly)",
      definition:
        "A natural language name identifying the terminology capabilities. This name should be usable as an identifier for the module by machine processing applications such as code generation.",
      comment:
        "The name is not expected to be globally unique. The name should be a simple alphanumeric type name to ensure that it is machine-processing friendly.",
      requirements: "Support human navigation and code generation.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.name", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.name",
    parentDataPath: "root",
    basePath: "root.name",
    baseId: "TerminologyCapabilities.name",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.title",
      path: "TerminologyCapabilities.title",
      short: "Name for this terminology capabilities (human friendly)",
      definition:
        "A short, descriptive, user-friendly title for the terminology capabilities.",
      comment:
        "This name does not need to be machine-processing friendly and may contain punctuation, white-space, etc.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.title", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [{ identity: "workflow", map: "Definition.title" }],
    },
    dataPath: "root.title",
    parentDataPath: "root",
    basePath: "root.title",
    baseId: "TerminologyCapabilities.title",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.status",
      path: "TerminologyCapabilities.status",
      short: "draft | active | retired | unknown",
      definition:
        "The status of this terminology capabilities. Enables tracking the life-cycle of the content.",
      comment:
        "Allows filtering of terminology capabilitiess that are appropriate for use versus not.This is not intended for use with actual capability statements, but where capability statements are used to describe possible or desired systems.",
      min: 1,
      max: "1",
      base: { path: "TerminologyCapabilities.status", min: 1, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: true,
      isModifierReason:
        'This is labeled as "Is Modifier" because applications should not use a retired {{title}} without due consideration',
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "PublicationStatus",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "required",
        description: "The lifecycle status of an artifact.",
        valueSet: "http://hl7.org/fhir/ValueSet/publication-status|4.3.0",
      },
      mapping: [
        { identity: "workflow", map: "Definition.status" },
        { identity: "w5", map: "FiveWs.status" },
      ],
    },
    dataPath: "root.status",
    parentDataPath: "root",
    basePath: "root.status",
    baseId: "TerminologyCapabilities.status",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "draft",
        display: "Draft",
      },
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "active",
        display: "Active",
      },
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "retired",
        display: "Retired",
      },
      {
        system: "http://hl7.org/fhir/publication-status",
        code: "unknown",
        display: "Unknown",
      },
    ],
  },
  {
    element: {
      id: "TerminologyCapabilities.experimental",
      path: "TerminologyCapabilities.experimental",
      short: "For testing purposes, not real usage",
      definition:
        "A Boolean value to indicate that this terminology capabilities is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage.",
      comment:
        "Allows filtering of terminology capabilitiess that are appropriate for use versus not.",
      requirements:
        "Enables experimental content to be developed following the same lifecycle that would be used for a production-level terminology capabilities.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.experimental", min: 0, max: "1" },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.experimental" },
        { identity: "w5", map: "FiveWs.class" },
      ],
    },
    dataPath: "root.experimental",
    parentDataPath: "root",
    basePath: "root.experimental",
    baseId: "TerminologyCapabilities.experimental",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.date",
      path: "TerminologyCapabilities.date",
      short: "Date last changed",
      definition:
        "The date  (and optionally time) when the terminology capabilities was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the terminology capabilities changes.",
      comment:
        "Note that this is not the same as the resource last-modified-date, since the resource may be a secondary representation of the terminology capabilities. Additional specific dates may be added as extensions or be found by consulting Provenances associated with past versions of the resource.",
      alias: ["Revision Date"],
      min: 1,
      max: "1",
      base: { path: "TerminologyCapabilities.date", min: 1, max: "1" },
      type: [{ code: "dateTime" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.date" },
        { identity: "w5", map: "FiveWs.recorded" },
      ],
    },
    dataPath: "root.date",
    parentDataPath: "root",
    basePath: "root.date",
    baseId: "TerminologyCapabilities.date",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.publisher",
      path: "TerminologyCapabilities.publisher",
      short: "Name of the publisher (organization or individual)",
      definition:
        "The name of the organization or individual that published the terminology capabilities.",
      comment:
        "Usually an organization but may be an individual. The publisher (or steward) of the terminology capabilities is the organization or individual primarily responsible for the maintenance and upkeep of the terminology capabilities. This is not necessarily the same individual or organization that developed and initially authored the content. The publisher is the primary point of contact for questions or issues with the terminology capabilities. This item SHOULD be populated unless the information is available from context.",
      requirements:
        'Helps establish the "authority/credibility" of the terminology capabilities.  May also allow for contact.',
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.publisher", min: 0, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.publisher" },
        { identity: "w5", map: "FiveWs.witness" },
      ],
    },
    dataPath: "root.publisher",
    parentDataPath: "root",
    basePath: "root.publisher",
    baseId: "TerminologyCapabilities.publisher",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.description",
      path: "TerminologyCapabilities.description",
      short: "Natural language description of the terminology capabilities",
      definition:
        "A free text natural language description of the terminology capabilities from a consumer's perspective. Typically, this is used when the capability statement describes a desired rather than an actual solution, for example as a formal expression of requirements as part of an RFP.",
      comment:
        "This description can be used to capture details such as why the terminology capabilities was built, comments about misuse, instructions for clinical use and interpretation, literature references, examples from the paper world, etc. It is not a rendering of the terminology capabilities as conveyed in the 'text' field of the resource itself. This item SHOULD be populated unless the information is available from context (e.g. the language of the terminology capabilities is presumed to be the predominant language in the place the terminology capabilities was created).This does not need to be populated if the description is adequately implied by the software or implementation details.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.description", min: 0, max: "1" },
      type: [{ code: "markdown" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [{ identity: "workflow", map: "Definition.description" }],
    },
    dataPath: "root.description",
    parentDataPath: "root",
    basePath: "root.description",
    baseId: "TerminologyCapabilities.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.jurisdiction",
      path: "TerminologyCapabilities.jurisdiction",
      short:
        "Intended jurisdiction for terminology capabilities (if applicable)",
      definition:
        "A legal or geographic region in which the terminology capabilities is intended to be used.",
      comment:
        "It may be possible for the terminology capabilities to be used in jurisdictions other than those for which it was originally designed or intended.",
      min: 0,
      max: "*",
      base: { path: "TerminologyCapabilities.jurisdiction", min: 0, max: "*" },
      type: [{ code: "CodeableConcept" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "Jurisdiction",
          },
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding",
            valueBoolean: true,
          },
        ],
        strength: "extensible",
        description:
          "Countries and regions within which this artifact is targeted for use.",
        valueSet: "http://hl7.org/fhir/ValueSet/jurisdiction",
      },
      mapping: [{ identity: "workflow", map: "Definition.jurisdiction" }],
    },
    dataPath: "root.jurisdiction[0]",
    parentDataPath: "root",
    basePath: "root.jurisdiction",
    baseId: "TerminologyCapabilities.jurisdiction",
    isPrimitive: false,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.purpose",
      path: "TerminologyCapabilities.purpose",
      short: "Why this terminology capabilities is defined",
      definition:
        "Explanation of why this terminology capabilities is needed and why it has been designed as it has.",
      comment:
        "This element does not describe the usage of the terminology capabilities. Instead, it provides traceability of ''why'' the resource is either needed or ''why'' it is defined as it is.  This may be used to point to source materials or specifications that drove the structure of this terminology capabilities.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.purpose", min: 0, max: "1" },
      type: [{ code: "markdown" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "workflow", map: "Definition.purpose" },
        { identity: "w5", map: "FiveWs.why[x]" },
        { identity: "objimpl", map: "no-gen-base" },
      ],
    },
    dataPath: "root.purpose",
    parentDataPath: "root",
    basePath: "root.purpose",
    baseId: "TerminologyCapabilities.purpose",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.copyright",
      path: "TerminologyCapabilities.copyright",
      short: "Use and/or publishing restrictions",
      definition:
        "A copyright statement relating to the terminology capabilities and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the terminology capabilities.",
      requirements:
        "Consumers must be able to determine any legal restrictions on the use of the terminology capabilities and/or its content.",
      alias: ["License", "Restrictions"],
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.copyright", min: 0, max: "1" },
      type: [{ code: "markdown" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      mapping: [
        { identity: "workflow", map: "Definition.copyright" },
        { identity: "objimpl", map: "no-gen-base" },
      ],
    },
    dataPath: "root.copyright",
    parentDataPath: "root",
    basePath: "root.copyright",
    baseId: "TerminologyCapabilities.copyright",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.kind",
      path: "TerminologyCapabilities.kind",
      short: "instance | capability | requirements",
      definition:
        "The way that this statement is intended to be used, to describe an actual running instance of software, a particular product (kind, not instance of software) or a class of implementation (e.g. a desired purchase).",
      requirements: "Allow searching the 3 modes.",
      min: 1,
      max: "1",
      base: { path: "TerminologyCapabilities.kind", min: 1, max: "1" },
      type: [{ code: "code" }],
      condition: ["tcp-3", "tcp-4", "tcp-5"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CapabilityStatementKind",
          },
        ],
        strength: "required",
        description: "How a capability statement is intended to be used.",
        valueSet:
          "http://hl7.org/fhir/ValueSet/capability-statement-kind|4.3.0",
      },
    },
    dataPath: "root.kind",
    parentDataPath: "root",
    basePath: "root.kind",
    baseId: "TerminologyCapabilities.kind",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/capability-statement-kind",
        code: "instance",
        display: "Instance",
      },
      {
        system: "http://hl7.org/fhir/capability-statement-kind",
        code: "capability",
        display: "Capability",
      },
      {
        system: "http://hl7.org/fhir/capability-statement-kind",
        code: "requirements",
        display: "Requirements",
      },
    ],
  },
  {
    element: {
      id: "TerminologyCapabilities.software",
      path: "TerminologyCapabilities.software",
      short:
        "Software that is covered by this terminology capability statement",
      definition:
        "Software that is covered by this terminology capability statement.  It is used when the statement describes the capabilities of a particular software version, independent of an installation.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.software", min: 0, max: "1" },
      type: [{ code: "BackboneElement" }],
      condition: ["tcp-2"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.software",
    parentDataPath: "root",
    basePath: "root.software",
    baseId: "TerminologyCapabilities.software",
    isPrimitive: false,
    childPaths: ["root.software.name", "root.software.version"],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.software.name",
      path: "TerminologyCapabilities.software.name",
      short: "A name the software is known by",
      definition: "Name the software is known by.",
      min: 1,
      max: "1",
      base: { path: "TerminologyCapabilities.software.name", min: 1, max: "1" },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.software.name",
    parentDataPath: "root.software",
    basePath: "root.name",
    baseId: "TerminologyCapabilities.software.name",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.software.version",
      path: "TerminologyCapabilities.software.version",
      short: "Version covered by this statement",
      definition:
        "The version identifier for the software covered by this statement.",
      comment:
        "If possible, a version should be specified, as statements are likely to be different for different versions of software.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.software.version",
        min: 0,
        max: "1",
      },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.software.version",
    parentDataPath: "root.software",
    basePath: "root.version",
    baseId: "TerminologyCapabilities.software.version",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.implementation",
      path: "TerminologyCapabilities.implementation",
      short: "If this describes a specific instance",
      definition:
        "Identifies a specific implementation instance that is described by the terminology capability statement - i.e. a particular installation, rather than the capabilities of a software program.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.implementation",
        min: 0,
        max: "1",
      },
      type: [{ code: "BackboneElement" }],
      condition: ["tcp-2", "tcp-5"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.implementation",
    parentDataPath: "root",
    basePath: "root.implementation",
    baseId: "TerminologyCapabilities.implementation",
    isPrimitive: false,
    childPaths: ["root.implementation.description", "root.implementation.url"],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.implementation.description",
      path: "TerminologyCapabilities.implementation.description",
      short: "Describes this specific instance",
      definition:
        "Information about the specific installation that this terminology capability statement relates to.",
      min: 1,
      max: "1",
      base: {
        path: "TerminologyCapabilities.implementation.description",
        min: 1,
        max: "1",
      },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.implementation.description",
    parentDataPath: "root.implementation",
    basePath: "root.description",
    baseId: "TerminologyCapabilities.implementation.description",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.implementation.url",
      path: "TerminologyCapabilities.implementation.url",
      short: "Base URL for the implementation",
      definition: "An absolute base URL for the implementation.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.implementation.url",
        min: 0,
        max: "1",
      },
      type: [{ code: "url" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.implementation.url",
    parentDataPath: "root.implementation",
    basePath: "root.url",
    baseId: "TerminologyCapabilities.implementation.url",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.lockedDate",
      path: "TerminologyCapabilities.lockedDate",
      short: "Whether lockedDate is supported",
      definition: "Whether the server supports lockedDate.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.lockedDate", min: 0, max: "1" },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.lockedDate",
    parentDataPath: "root",
    basePath: "root.lockedDate",
    baseId: "TerminologyCapabilities.lockedDate",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem",
      path: "TerminologyCapabilities.codeSystem",
      short: "A code system supported by the server",
      definition:
        "Identifies a code system that is supported by the server. If there is a no code system URL, then this declares the general assumptions a client can make about support for any CodeSystem resource.",
      comment:
        "The code system - identified by its system URL - may also be declared explicitly as a Code System Resource at /CodeSystem, but it might not be.",
      alias: ["1"],
      min: 0,
      max: "*",
      base: { path: "TerminologyCapabilities.codeSystem", min: 0, max: "*" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
        {
          key: "tcp-1",
          severity: "error",
          human:
            "If there is more than one version, a version code must be defined",
          expression: "version.count() > 1 implies version.all(code.exists())",
          xpath:
            "(count(f:version) <= 1) or not(exists(f:version[not(f:code)]))",
          source:
            "http://hl7.org/fhir/StructureDefinition/TerminologyCapabilities",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem[0]",
    parentDataPath: "root",
    basePath: "root.codeSystem",
    baseId: "TerminologyCapabilities.codeSystem",
    isPrimitive: false,
    childPaths: [
      "root.codeSystem.uri",
      "root.codeSystem.version[0]",
      "root.codeSystem.subsumption",
    ],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.uri",
      path: "TerminologyCapabilities.codeSystem.uri",
      short: "URI for the Code System",
      definition: "URI for the Code System.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.codeSystem.uri",
        min: 0,
        max: "1",
      },
      type: [
        {
          code: "canonical",
          targetProfile: ["http://hl7.org/fhir/StructureDefinition/CodeSystem"],
        },
      ],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem.uri",
    parentDataPath: "root.codeSystem[0]",
    basePath: "root.uri",
    baseId: "TerminologyCapabilities.codeSystem.uri",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.version",
      path: "TerminologyCapabilities.codeSystem.version",
      short: "Version of Code System supported",
      definition:
        "For the code system, a list of versions that are supported by the server.",
      comment: "Language translations might not be available for all codes.",
      min: 0,
      max: "*",
      base: {
        path: "TerminologyCapabilities.codeSystem.version",
        min: 0,
        max: "*",
      },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem.version[0]",
    parentDataPath: "root.codeSystem[0]",
    basePath: "root.version",
    baseId: "TerminologyCapabilities.codeSystem.version",
    isPrimitive: false,
    childPaths: [
      "root.codeSystem.version.code",
      "root.codeSystem.version.isDefault",
      "root.codeSystem.version.compositional",
      "root.codeSystem.version.language[0]",
      "root.codeSystem.version.filter[0]",
      "root.codeSystem.version.property[0]",
    ],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.version.code",
      path: "TerminologyCapabilities.codeSystem.version.code",
      short: "Version identifier for this version",
      definition:
        "For version-less code systems, there should be a single version with no identifier.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.codeSystem.version.code",
        min: 0,
        max: "1",
      },
      type: [{ code: "string" }],
      condition: ["tcp-1"],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.codeSystem.version.code",
    parentDataPath: "root.codeSystem.version[0]",
    basePath: "root.code",
    baseId: "TerminologyCapabilities.codeSystem.version.code",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.version.isDefault",
      path: "TerminologyCapabilities.codeSystem.version.isDefault",
      short: "If this is the default version for this code system",
      definition: "If this is the default version for this code system.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.codeSystem.version.isDefault",
        min: 0,
        max: "1",
      },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: true,
    },
    dataPath: "root.codeSystem.version.isDefault",
    parentDataPath: "root.codeSystem.version[0]",
    basePath: "root.isDefault",
    baseId: "TerminologyCapabilities.codeSystem.version.isDefault",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.version.compositional",
      path: "TerminologyCapabilities.codeSystem.version.compositional",
      short: "If compositional grammar is supported",
      definition:
        "If the compositional grammar defined by the code system is supported.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.codeSystem.version.compositional",
        min: 0,
        max: "1",
      },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem.version.compositional",
    parentDataPath: "root.codeSystem.version[0]",
    basePath: "root.compositional",
    baseId: "TerminologyCapabilities.codeSystem.version.compositional",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.version.language",
      extension: [
        {
          url: "http://hl7.org/fhir/build/StructureDefinition/no-binding",
          valueBoolean: true,
        },
      ],
      path: "TerminologyCapabilities.codeSystem.version.language",
      short: "Language Displays supported",
      definition: "Language Displays supported.",
      min: 0,
      max: "*",
      base: {
        path: "TerminologyCapabilities.codeSystem.version.language",
        min: 0,
        max: "*",
      },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem.version.language[0]",
    parentDataPath: "root.codeSystem.version[0]",
    basePath: "root.language",
    baseId: "TerminologyCapabilities.codeSystem.version.language",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.version.filter",
      path: "TerminologyCapabilities.codeSystem.version.filter",
      short: "Filter Properties supported",
      definition: "Filter Properties supported.",
      min: 0,
      max: "*",
      base: {
        path: "TerminologyCapabilities.codeSystem.version.filter",
        min: 0,
        max: "*",
      },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem.version.filter[0]",
    parentDataPath: "root.codeSystem.version[0]",
    basePath: "root.filter",
    baseId: "TerminologyCapabilities.codeSystem.version.filter",
    isPrimitive: false,
    childPaths: [
      "root.codeSystem.version.filter.code",
      "root.codeSystem.version.filter.op[0]",
    ],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.version.filter.code",
      extension: [
        {
          url: "http://hl7.org/fhir/build/StructureDefinition/no-binding",
          valueBoolean: true,
        },
      ],
      path: "TerminologyCapabilities.codeSystem.version.filter.code",
      short: "Code of the property supported",
      definition: "Code of the property supported.",
      min: 1,
      max: "1",
      base: {
        path: "TerminologyCapabilities.codeSystem.version.filter.code",
        min: 1,
        max: "1",
      },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem.version.filter.code",
    parentDataPath: "root.codeSystem.version.filter[0]",
    basePath: "root.code",
    baseId: "TerminologyCapabilities.codeSystem.version.filter.code",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.version.filter.op",
      extension: [
        {
          url: "http://hl7.org/fhir/build/StructureDefinition/no-binding",
          valueBoolean: true,
        },
      ],
      path: "TerminologyCapabilities.codeSystem.version.filter.op",
      short: "Operations supported for the property",
      definition: "Operations supported for the property.",
      min: 1,
      max: "*",
      base: {
        path: "TerminologyCapabilities.codeSystem.version.filter.op",
        min: 1,
        max: "*",
      },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem.version.filter.op[0]",
    parentDataPath: "root.codeSystem.version.filter[0]",
    basePath: "root.op",
    baseId: "TerminologyCapabilities.codeSystem.version.filter.op",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.version.property",
      extension: [
        {
          url: "http://hl7.org/fhir/build/StructureDefinition/no-binding",
          valueBoolean: true,
        },
      ],
      path: "TerminologyCapabilities.codeSystem.version.property",
      short: "Properties supported for $lookup",
      definition: "Properties supported for $lookup.",
      min: 0,
      max: "*",
      base: {
        path: "TerminologyCapabilities.codeSystem.version.property",
        min: 0,
        max: "*",
      },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem.version.property[0]",
    parentDataPath: "root.codeSystem.version[0]",
    basePath: "root.property",
    baseId: "TerminologyCapabilities.codeSystem.version.property",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSystem.subsumption",
      path: "TerminologyCapabilities.codeSystem.subsumption",
      short: "Whether subsumption is supported",
      definition:
        "True if subsumption is supported for this version of the code system.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.codeSystem.subsumption",
        min: 0,
        max: "1",
      },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.codeSystem.subsumption",
    parentDataPath: "root.codeSystem[0]",
    basePath: "root.subsumption",
    baseId: "TerminologyCapabilities.codeSystem.subsumption",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.expansion",
      path: "TerminologyCapabilities.expansion",
      short:
        "Information about the [ValueSet/$expand](valueset-operation-expand.html) operation",
      definition:
        "Information about the [ValueSet/$expand](valueset-operation-expand.html) operation.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.expansion", min: 0, max: "1" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.expansion",
    parentDataPath: "root",
    basePath: "root.expansion",
    baseId: "TerminologyCapabilities.expansion",
    isPrimitive: false,
    childPaths: [
      "root.expansion.hierarchical",
      "root.expansion.paging",
      "root.expansion.incomplete",
      "root.expansion.parameter[0]",
      "root.expansion.textFilter",
    ],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.expansion.hierarchical",
      path: "TerminologyCapabilities.expansion.hierarchical",
      short: "Whether the server can return nested value sets",
      definition: "Whether the server can return nested value sets.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.expansion.hierarchical",
        min: 0,
        max: "1",
      },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.expansion.hierarchical",
    parentDataPath: "root.expansion",
    basePath: "root.hierarchical",
    baseId: "TerminologyCapabilities.expansion.hierarchical",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.expansion.paging",
      path: "TerminologyCapabilities.expansion.paging",
      short: "Whether the server supports paging on expansion",
      definition: "Whether the server supports paging on expansion.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.expansion.paging",
        min: 0,
        max: "1",
      },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.expansion.paging",
    parentDataPath: "root.expansion",
    basePath: "root.paging",
    baseId: "TerminologyCapabilities.expansion.paging",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.expansion.incomplete",
      path: "TerminologyCapabilities.expansion.incomplete",
      short: "Allow request for incomplete expansions?",
      definition: "Allow request for incomplete expansions?",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.expansion.incomplete",
        min: 0,
        max: "1",
      },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.expansion.incomplete",
    parentDataPath: "root.expansion",
    basePath: "root.incomplete",
    baseId: "TerminologyCapabilities.expansion.incomplete",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.expansion.parameter",
      path: "TerminologyCapabilities.expansion.parameter",
      short: "Supported expansion parameter",
      definition: "Supported expansion parameter.",
      min: 0,
      max: "*",
      base: {
        path: "TerminologyCapabilities.expansion.parameter",
        min: 0,
        max: "*",
      },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.expansion.parameter[0]",
    parentDataPath: "root.expansion",
    basePath: "root.parameter",
    baseId: "TerminologyCapabilities.expansion.parameter",
    isPrimitive: false,
    childPaths: [
      "root.expansion.parameter.name",
      "root.expansion.parameter.documentation",
    ],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.expansion.parameter.name",
      extension: [
        {
          url: "http://hl7.org/fhir/build/StructureDefinition/no-binding",
          valueBoolean: true,
        },
      ],
      path: "TerminologyCapabilities.expansion.parameter.name",
      short: "Expansion Parameter name",
      definition: "Expansion Parameter name.",
      min: 1,
      max: "1",
      base: {
        path: "TerminologyCapabilities.expansion.parameter.name",
        min: 1,
        max: "1",
      },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.expansion.parameter.name",
    parentDataPath: "root.expansion.parameter[0]",
    basePath: "root.name",
    baseId: "TerminologyCapabilities.expansion.parameter.name",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.expansion.parameter.documentation",
      path: "TerminologyCapabilities.expansion.parameter.documentation",
      short: "Description of support for parameter",
      definition: "Description of support for parameter.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.expansion.parameter.documentation",
        min: 0,
        max: "1",
      },
      type: [{ code: "string" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.expansion.parameter.documentation",
    parentDataPath: "root.expansion.parameter[0]",
    basePath: "root.documentation",
    baseId: "TerminologyCapabilities.expansion.parameter.documentation",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.expansion.textFilter",
      path: "TerminologyCapabilities.expansion.textFilter",
      short: "Documentation about text searching works",
      definition: "Documentation about text searching works.",
      comment:
        "This documentation should cover things like case sensitivity,  use of punctuation if not ignored, what wild cards are supported (if any), whether text is starts with or contains, and whether word order matters.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.expansion.textFilter",
        min: 0,
        max: "1",
      },
      type: [{ code: "markdown" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.expansion.textFilter",
    parentDataPath: "root.expansion",
    basePath: "root.textFilter",
    baseId: "TerminologyCapabilities.expansion.textFilter",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.codeSearch",
      path: "TerminologyCapabilities.codeSearch",
      short: "explicit | all",
      definition:
        "The degree to which the server supports the code search parameter on ValueSet, if it is supported.",
      comment: "See notes on the [ValueSet](valueset.html#) resource.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.codeSearch", min: 0, max: "1" },
      type: [{ code: "code" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      binding: {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName",
            valueString: "CodeSearchSupport",
          },
        ],
        strength: "required",
        description:
          "The degree to which the server supports the code search parameter on ValueSet, if it is supported.",
        valueSet: "http://hl7.org/fhir/ValueSet/code-search-support|4.3.0",
      },
    },
    dataPath: "root.codeSearch",
    parentDataPath: "root",
    basePath: "root.codeSearch",
    baseId: "TerminologyCapabilities.codeSearch",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
    bindingCodes: [
      {
        system: "http://hl7.org/fhir/code-search-support",
        code: "explicit",
        display: "Explicit Codes",
      },
      {
        system: "http://hl7.org/fhir/code-search-support",
        code: "all",
        display: "Implicit Codes",
      },
    ],
  },
  {
    element: {
      id: "TerminologyCapabilities.validateCode",
      path: "TerminologyCapabilities.validateCode",
      short:
        "Information about the [ValueSet/$validate-code](valueset-operation-validate-code.html) operation",
      definition:
        "Information about the [ValueSet/$validate-code](valueset-operation-validate-code.html) operation.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.validateCode", min: 0, max: "1" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.validateCode",
    parentDataPath: "root",
    basePath: "root.validateCode",
    baseId: "TerminologyCapabilities.validateCode",
    isPrimitive: false,
    childPaths: ["root.validateCode.translations"],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.validateCode.translations",
      path: "TerminologyCapabilities.validateCode.translations",
      short: "Whether translations are validated",
      definition: "Whether translations are validated.",
      min: 1,
      max: "1",
      base: {
        path: "TerminologyCapabilities.validateCode.translations",
        min: 1,
        max: "1",
      },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.validateCode.translations",
    parentDataPath: "root.validateCode",
    basePath: "root.translations",
    baseId: "TerminologyCapabilities.validateCode.translations",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.translation",
      path: "TerminologyCapabilities.translation",
      short:
        "Information about the [ConceptMap/$translate](conceptmap-operation-translate.html) operation",
      definition:
        "Information about the [ConceptMap/$translate](conceptmap-operation-translate.html) operation.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.translation", min: 0, max: "1" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.translation",
    parentDataPath: "root",
    basePath: "root.translation",
    baseId: "TerminologyCapabilities.translation",
    isPrimitive: false,
    childPaths: ["root.translation.needsMap"],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.translation.needsMap",
      path: "TerminologyCapabilities.translation.needsMap",
      short: "Whether the client must identify the map",
      definition: "Whether the client must identify the map.",
      min: 1,
      max: "1",
      base: {
        path: "TerminologyCapabilities.translation.needsMap",
        min: 1,
        max: "1",
      },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.translation.needsMap",
    parentDataPath: "root.translation",
    basePath: "root.needsMap",
    baseId: "TerminologyCapabilities.translation.needsMap",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.closure",
      path: "TerminologyCapabilities.closure",
      short:
        "Information about the [ConceptMap/$closure](conceptmap-operation-closure.html) operation",
      definition: "Whether the $closure operation is supported.",
      min: 0,
      max: "1",
      base: { path: "TerminologyCapabilities.closure", min: 0, max: "1" },
      type: [{ code: "BackboneElement" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human:
            "All FHIR elements must have a @value or children unless an empty Parameters resource",
          expression:
            "hasValue() or (children().count() > id.count()) or $this is Parameters",
          xpath: "@value|f:*|h:div|self::f:Parameters",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.closure",
    parentDataPath: "root",
    basePath: "root.closure",
    baseId: "TerminologyCapabilities.closure",
    isPrimitive: false,
    childPaths: ["root.closure.translation"],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities.closure.translation",
      path: "TerminologyCapabilities.closure.translation",
      short: "If cross-system closure is supported",
      definition: "If cross-system closure is supported.",
      min: 0,
      max: "1",
      base: {
        path: "TerminologyCapabilities.closure.translation",
        min: 0,
        max: "1",
      },
      type: [{ code: "boolean" }],
      constraint: [
        {
          key: "ele-1",
          severity: "error",
          human: "All FHIR elements must have a @value or children",
          expression: "hasValue() or (children().count() > id.count())",
          xpath: "@value|f:*|h:div",
          source: "http://hl7.org/fhir/StructureDefinition/Element",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
    },
    dataPath: "root.closure.translation",
    parentDataPath: "root.closure",
    basePath: "root.translation",
    baseId: "TerminologyCapabilities.closure.translation",
    isPrimitive: true,
    isRootPrimitive: true,
    childPaths: [],
    value: "",
  },
  {
    element: {
      id: "TerminologyCapabilities",
      path: "TerminologyCapabilities",
      short: "A statement of system capabilities",
      definition:
        "A TerminologyCapabilities resource documents a set of capabilities (behaviors) of a FHIR Terminology Server that may be used as a statement of actual server functionality or a statement of required or desired server implementation.",
      min: 0,
      max: "*",
      base: { path: "TerminologyCapabilities", min: 0, max: "*" },
      constraint: [
        {
          key: "dom-2",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL NOT contain nested Resources",
          expression: "contained.contained.empty()",
          xpath: "not(parent::f:contained and f:contained)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-3",
          severity: "error",
          human:
            "If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
          expression:
            "contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()",
          xpath:
            "not(exists(for $contained in f:contained return $contained[not(exists(parent::*/descendant::f:reference/@value=concat('#', $contained/*/f:id/@value)) or exists(descendant::f:reference[@value='#']))]))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-4",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
          expression:
            "contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
          xpath:
            "not(exists(f:contained/*/f:meta/f:versionId)) and not(exists(f:contained/*/f:meta/f:lastUpdated))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "dom-5",
          severity: "error",
          human:
            "If a resource is contained in another resource, it SHALL NOT have a security label",
          expression: "contained.meta.security.empty()",
          xpath: "not(exists(f:contained/*/f:meta/f:security))",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice",
              valueBoolean: true,
            },
            {
              url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-bestpractice-explanation",
              valueMarkdown:
                "When a resource has no narrative, only systems that fully understand the data can display the resource to a human safely. Including a human readable representation in the resource makes for a much more robust eco-system and cheaper handling of resources by intermediary systems. Some ecosystems restrict distribution of resources to only those systems that do fully understand the resources, and as a consequence implementers may believe that the narrative is superfluous. However experience shows that such eco-systems often open up to new participants over time.",
            },
          ],
          key: "dom-6",
          severity: "warning",
          human: "A resource should have narrative for robust management",
          expression: "text.`div`.exists()",
          xpath: "exists(f:text/h:div)",
          source: "http://hl7.org/fhir/StructureDefinition/DomainResource",
        },
        {
          key: "tcp-0",
          severity: "warning",
          human:
            "Name should be usable as an identifier for the module by machine processing applications such as code generation",
          expression:
            "name.exists() implies name.matches('[A-Z]([A-Za-z0-9_]){0,254}')",
          xpath:
            "not(exists(f:name/@value)) or matches(f:name/@value, '[A-Z]([A-Za-z0-9_]){0,254}')",
          source:
            "http://hl7.org/fhir/StructureDefinition/TerminologyCapabilities",
        },
        {
          key: "tcp-2",
          severity: "error",
          human:
            "A Capability Statement SHALL have at least one of description, software, or implementation element.",
          expression:
            "(description.count() + software.count() + implementation.count()) > 0",
          xpath: "count(f:software | f:implementation | f:description) > 0",
          source:
            "http://hl7.org/fhir/StructureDefinition/TerminologyCapabilities",
        },
        {
          key: "tcp-3",
          severity: "error",
          human:
            "If kind = instance, implementation must be present and software may be present",
          expression: "(kind != 'instance') or implementation.exists()",
          xpath: "not(f:kind/@value='instance') or exists(f:implementation)",
          source:
            "http://hl7.org/fhir/StructureDefinition/TerminologyCapabilities",
        },
        {
          key: "tcp-4",
          severity: "error",
          human:
            "If kind = capability, implementation must be absent, software must be present",
          expression:
            "(kind != 'capability') or (implementation.exists().not() and software.exists())",
          xpath:
            " not(f:kind/@value='instance') or (not(exists(f:implementation)) and exists(f:software))",
          source:
            "http://hl7.org/fhir/StructureDefinition/TerminologyCapabilities",
        },
        {
          key: "tcp-5",
          severity: "error",
          human:
            "If kind = requirements, implementation and software must be absent",
          expression:
            "(kind!='requirements') or (implementation.exists().not() and software.exists().not())",
          xpath:
            "not(f:kind/@value='instance') or (not(exists(f:implementation)) and not(exists(f:software)))",
          source:
            "http://hl7.org/fhir/StructureDefinition/TerminologyCapabilities",
        },
      ],
      mustSupport: false,
      isModifier: false,
      isSummary: false,
      mapping: [
        { identity: "rim", map: "Entity. Role, or Act" },
        { identity: "rim", map: "n/a" },
        { identity: "w5", map: "conformance.behavior" },
      ],
    },
    dataPath: "root",
    parentDataPath: "",
    basePath: "root",
    baseId: "TerminologyCapabilities",
    isPrimitive: false,
    isRoot: true,
    childPaths: [],
    value: "",
  },
];
export default data;
